//! Renders a program's [`CShim`] description to the C source clang compiles beside the module.

use dream_abi::c_abi::shim::{CField, CShim, CStruct, CTy, Forward, Reverse, SHIM_PREFIX};
use dream_types::CScalar;
use std::fmt::Write;

pub fn render(shim: &CShim) -> String {
    Render { shim }.render()
}

struct Render<'a> {
    shim: &'a CShim,
}

#[derive(Clone, PartialEq, Eq)]
struct Proto {
    ret: CTy,
    params: Vec<CTy>,
    stdcall: bool,
}

impl Render<'_> {
    fn render(&self) -> String {
        let mut out = String::from(
            "/* Generated by the Dream compiler: the C side of this program's `@c` calls. */\n\
             #include <stdbool.h>\n#include <stdint.h>\n\n\
             #define DREAM_SHIM __attribute__((always_inline))\n\n",
        );
        for (i, s) in self.shim.structs.iter().enumerate() {
            self.render_struct(&mut out, i, s);
        }
        let declared = self.declare_symbols(&mut out);
        for f in &self.shim.forwards {
            self.render_forward(&mut out, f, &declared);
        }
        for r in &self.shim.reverses {
            self.render_reverse(&mut out, r);
        }
        for d in &self.shim.destructors {
            let _ = writeln!(
                out,
                "DREAM_SHIM void* {}(void) {{ return (void*)&{}; }}\n",
                d.getter, d.symbol
            );
        }
        out
    }

    /// One prototype per C symbol, from its first use; later uses with other types cast.
    fn declare_symbols<'s>(&'s self, out: &mut String) -> Vec<(&'s str, Proto)> {
        let mut declared: Vec<(&str, Proto)> = Vec::new();
        let destructor = Proto {
            ret: CTy::Void,
            params: vec![CTy::Ptr],
            stdcall: false,
        };
        let uses = self
            .shim
            .forwards
            .iter()
            .map(|f| (f.symbol.as_str(), proto(f)))
            .chain(
                self.shim
                    .destructors
                    .iter()
                    .map(|d| (d.symbol.as_str(), destructor.clone())),
            );
        for (symbol, proto) in uses {
            if declared.iter().any(|(s, _)| *s == symbol) {
                continue;
            }
            let _ = writeln!(out, "extern {};", self.decl(&proto, symbol));
            declared.push((symbol, proto));
        }
        for r in &self.shim.reverses {
            let carriers: Vec<String> = r.params.iter().map(|t| self.carrier(*t)).collect();
            let _ = writeln!(
                out,
                "extern {} {}({});",
                self.carrier(r.ret),
                r.body,
                param_list(&carriers)
            );
        }
        out.push('\n');
        declared
    }

    fn render_struct(&self, out: &mut String, i: usize, s: &CStruct) {
        let packed = if s.packed {
            " __attribute__((packed))"
        } else {
            ""
        };
        let _ = writeln!(out, "typedef struct{packed} {{");
        for (j, (_, f)) in s.fields.iter().enumerate() {
            let _ = writeln!(out, "    {} f{j};", self.field_ty(*f));
        }
        let _ = writeln!(out, "}} {};", struct_name(i));
        let name = struct_name(i);
        let _ = writeln!(
            out,
            "static inline void {SHIM_PREFIX}load{i}({name}* v, const unsigned char* p) {{"
        );
        for (j, (off, f)) in s.fields.iter().enumerate() {
            match f {
                CField::Scalar(CScalar::Char) => {
                    let _ = writeln!(
                        out,
                        "    int32_t c{j}; __builtin_memcpy(&c{j}, p + {off}, sizeof c{j});"
                    );
                    let _ = writeln!(
                        out,
                        "    v->f{j} = {};",
                        CScalar::Char.from_carrier(&format!("c{j}"))
                    );
                }
                CField::Scalar(_) => {
                    let _ = writeln!(
                        out,
                        "    __builtin_memcpy(&v->f{j}, p + {off}, sizeof v->f{j});"
                    );
                }
                CField::Struct(k) => {
                    let _ = writeln!(out, "    {SHIM_PREFIX}load{k}(&v->f{j}, p + {off});");
                }
            }
        }
        out.push_str("}\n");
        let _ = writeln!(
            out,
            "static inline void {SHIM_PREFIX}store{i}(unsigned char* p, const {name}* v) {{"
        );
        for (j, (off, f)) in s.fields.iter().enumerate() {
            match f {
                CField::Scalar(CScalar::Char) => {
                    let value = CScalar::Char.to_carrier(&format!("v->f{j}"));
                    let _ = writeln!(
                        out,
                        "    int32_t c{j} = {value}; __builtin_memcpy(p + {off}, &c{j}, sizeof c{j});"
                    );
                }
                CField::Scalar(_) => {
                    let _ = writeln!(
                        out,
                        "    __builtin_memcpy(p + {off}, &v->f{j}, sizeof v->f{j});"
                    );
                }
                CField::Struct(k) => {
                    let _ = writeln!(out, "    {SHIM_PREFIX}store{k}(p + {off}, &v->f{j});");
                }
            }
        }
        out.push_str("}\n\n");
    }

    fn render_forward(&self, out: &mut String, f: &Forward, declared: &[(&str, Proto)]) {
        let mut params = Vec::new();
        if let CTy::Struct(_) = f.ret {
            params.push("void* out".to_string());
        }
        let mut body = String::new();
        let mut args = Vec::new();
        for (i, t) in f.params.iter().enumerate() {
            match t {
                CTy::Struct(k) => {
                    params.push(format!("const void* p{i}"));
                    let _ = writeln!(
                        body,
                        "    {} a{i};\n    {SHIM_PREFIX}load{k}(&a{i}, (const unsigned char*)p{i});",
                        struct_name(*k)
                    );
                    args.push(format!("a{i}"));
                }
                CTy::Scalar(s) => {
                    params.push(format!("{} p{i}", s.carrier()));
                    args.push(s.from_carrier(&format!("p{i}")));
                }
                CTy::Ptr | CTy::Void => {
                    params.push(format!("void* p{i}"));
                    args.push(format!("p{i}"));
                }
            }
        }
        let call = format!(
            "{}({})",
            callee(&f.symbol, &proto(f), declared, self),
            args.join(", ")
        );
        match f.ret {
            CTy::Void => {
                let _ = writeln!(body, "    {call};");
            }
            CTy::Scalar(s) => {
                let _ = writeln!(body, "    return {};", s.to_carrier(&call));
            }
            CTy::Ptr => {
                let _ = writeln!(body, "    return {call};");
            }
            CTy::Struct(k) => {
                let _ = writeln!(
                    body,
                    "    {} r = {call};\n    {SHIM_PREFIX}store{k}((unsigned char*)out, &r);",
                    struct_name(k)
                );
            }
        }
        let ret = match f.ret {
            CTy::Struct(_) => "void".to_string(),
            t => self.carrier(t),
        };
        let _ = writeln!(
            out,
            "DREAM_SHIM {ret} {}({}) {{\n{body}}}\n",
            f.shim,
            param_list(&params)
        );
    }

    fn render_reverse(&self, out: &mut String, r: &Reverse) {
        let params: Vec<String> = r
            .params
            .iter()
            .enumerate()
            .map(|(i, t)| format!("{} c{i}", self.c_ty(*t)))
            .collect();
        let args: Vec<String> = r
            .params
            .iter()
            .enumerate()
            .map(|(i, t)| match t {
                CTy::Scalar(s) => s.to_carrier(&format!("c{i}")),
                _ => format!("c{i}"),
            })
            .collect();
        let call = format!("{}({})", r.body, args.join(", "));
        let body = match r.ret {
            CTy::Void => format!("{call};"),
            CTy::Scalar(s) => format!("return {};", s.from_carrier(&call)),
            _ => format!("return {call};"),
        };
        let _ = writeln!(
            out,
            "{} {}({}) {{\n    {body}\n}}\n",
            self.c_ty(r.ret),
            r.adapter,
            param_list(&params)
        );
    }

    fn decl(&self, p: &Proto, name: &str) -> String {
        let params: Vec<String> = p.params.iter().map(|t| self.c_ty(*t)).collect();
        format!(
            "{}{} {name}({})",
            self.c_ty(p.ret),
            conv(p.stdcall),
            param_list(&params)
        )
    }

    fn fn_ptr_ty(&self, p: &Proto) -> String {
        let params: Vec<String> = p.params.iter().map(|t| self.c_ty(*t)).collect();
        let conv = if p.stdcall {
            "__attribute__((stdcall)) "
        } else {
            ""
        };
        format!("{} ({conv}*)({})", self.c_ty(p.ret), param_list(&params))
    }

    fn c_ty(&self, t: CTy) -> String {
        match t {
            CTy::Void => "void".into(),
            CTy::Scalar(s) => s.c_name().into(),
            CTy::Ptr => "void*".into(),
            CTy::Struct(i) => struct_name(i),
        }
    }

    fn carrier(&self, t: CTy) -> String {
        match t {
            CTy::Scalar(s) => s.carrier().into(),
            CTy::Struct(_) => "void*".into(),
            t => self.c_ty(t),
        }
    }

    fn field_ty(&self, f: CField) -> String {
        match f {
            CField::Scalar(s) => s.c_name().into(),
            CField::Struct(i) => struct_name(i),
        }
    }
}

fn proto(f: &Forward) -> Proto {
    Proto {
        ret: f.ret,
        params: f.params.clone(),
        stdcall: f.stdcall,
    }
}

/// `symbol` called through `proto`: by name when that is how it was declared, else through a
/// function-pointer cast (two externs may bind one symbol with different Dream types).
fn callee(symbol: &str, proto: &Proto, declared: &[(&str, Proto)], r: &Render<'_>) -> String {
    match declared.iter().find(|(s, _)| *s == symbol) {
        Some((_, p)) if p == proto => symbol.to_string(),
        _ => format!("(({})&{symbol})", r.fn_ptr_ty(proto)),
    }
}

fn conv(stdcall: bool) -> &'static str {
    if stdcall {
        " __attribute__((stdcall))"
    } else {
        ""
    }
}

fn struct_name(i: usize) -> String {
    format!("{SHIM_PREFIX}struct{i}")
}

fn param_list(params: &[String]) -> String {
    if params.is_empty() {
        "void".into()
    } else {
        params.join(", ")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use dream_abi::c_abi::shim::Destructor;
    use dream_types::CScalar;

    fn forward(symbol: &str, params: Vec<CTy>, ret: CTy) -> Forward {
        Forward {
            shim: format!("{SHIM_PREFIX}{symbol}"),
            symbol: symbol.into(),
            stdcall: false,
            params,
            ret,
        }
    }

    #[test]
    fn narrow_results_are_reextended_from_the_c_type() {
        let mut shim = CShim::default();
        shim.forwards.push(forward(
            "is_ok",
            vec![CTy::Scalar(CScalar::Bool)],
            CTy::Scalar(CScalar::Bool),
        ));
        let c = render(&shim);
        assert!(c.contains("extern bool is_ok(bool);"), "{}", c);
        assert!(c.contains("int32_t dream_cs_is_ok(int32_t p0)"), "{}", c);
        assert!(c.contains("return (int32_t)(is_ok(((p0) != 0)));"), "{}", c);
    }

    #[test]
    fn structs_cross_by_value_and_return_through_an_out_pointer() {
        let mut shim = CShim::default();
        let v = shim.intern_struct(CStruct {
            packed: false,
            fields: vec![
                (0, CField::Scalar(CScalar::F32)),
                (4, CField::Scalar(CScalar::F32)),
            ],
        });
        let again = shim.structs[v].clone();
        assert_eq!(shim.intern_struct(again), v, "structs are interned");
        shim.forwards.push(forward(
            "scale",
            vec![CTy::Struct(v), CTy::Scalar(CScalar::F32)],
            CTy::Struct(v),
        ));
        let c = render(&shim);
        assert!(
            c.contains("extern dream_cs_struct0 scale(dream_cs_struct0, float);"),
            "{}",
            c
        );
        assert!(
            c.contains("DREAM_SHIM void dream_cs_scale(void* out, const void* p0, float p1)"),
            "{}",
            c
        );
        assert!(
            c.contains("dream_cs_store0((unsigned char*)out, &r);"),
            "{}",
            c
        );
    }

    #[test]
    fn a_symbol_bound_twice_is_declared_once_and_cast_for_the_other_types() {
        let mut shim = CShim::default();
        shim.forwards
            .push(forward("free", vec![CTy::Ptr], CTy::Void));
        shim.forwards.push(Forward {
            shim: format!("{SHIM_PREFIX}free_other"),
            stdcall: true,
            ..forward("free", vec![CTy::Scalar(CScalar::USize)], CTy::Void)
        });
        shim.destructors.push(Destructor {
            getter: format!("{SHIM_PREFIX}free__dtor"),
            symbol: "free".into(),
        });
        let c = render(&shim);
        assert_eq!(c.matches("extern void free(").count(), 1, "{}", c);
        assert!(
            c.contains("((void (__attribute__((stdcall)) *)(uintptr_t))&free)(p0);"),
            "{}",
            c
        );
        assert!(c.contains("return (void*)&free;"), "{}", c);
    }

    #[test]
    fn reverse_adapters_narrow_on_the_c_side() {
        let mut shim = CShim::default();
        shim.reverses.push(Reverse {
            adapter: "dream_ctramp_7".into(),
            body: "dream_ctramp_7__body".into(),
            params: vec![CTy::Ptr, CTy::Scalar(CScalar::Bool)],
            ret: CTy::Scalar(CScalar::U8),
        });
        let c = render(&shim);
        assert!(
            c.contains("extern int32_t dream_ctramp_7__body(void*, int32_t);"),
            "{}",
            c
        );
        assert!(
            c.contains("uint8_t dream_ctramp_7(void* c0, bool c1)"),
            "{}",
            c
        );
        assert!(
            c.contains("return (uint8_t)(dream_ctramp_7__body(c0, (int32_t)(c1)));"),
            "{}",
            c
        );
    }
}
