//! Writes one set's `shim.cpp`: an `extern "C"` function per `@cpp` member, `static_assert`
//! layout checks per `@cpp` struct, and `#line` directives so clang reports a declaration that
//! does not match the header at the `.dream` line.

use std::fmt::Write as _;

use super::desugar::last_error_symbol;
use super::model::{Class, Member, MemberKind, SetDecls, Struct};
use super::types::{Bridge, Elem, Known, Ret};

pub(crate) const BRIDGE_HEADER: &str = include_str!("../../../runtime/cpp/dream_bridge.hpp");
pub(crate) const BRIDGE_HEADER_NAME: &str = "dream_bridge.hpp";

fn c_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn line(out: &mut String, line: usize, file: &str) {
    let _ = writeln!(out, "#line {} {}", line.max(1), c_string(file));
}

pub(super) fn shim_source(set: &str, decls: &SetDecls, known: &Known) -> String {
    let mut out =
        String::from("// Generated by the Dream compiler from `@cpp` declarations; do not edit.\n");
    let _ = writeln!(out, "#include {}", c_string(BRIDGE_HEADER_NAME));
    for h in &decls.headers {
        let _ = writeln!(out, "#include {}", c_string(h));
    }
    out.push('\n');
    let _ = writeln!(
        out,
        "extern \"C\" const char* {}(void) {{ return dream::last_error(); }}\n",
        last_error_symbol(set)
    );
    for (file, s) in &decls.structs {
        layout_checks(&mut out, file, s);
    }
    for fd in &decls.files {
        for c in &fd.classes {
            line(&mut out, c.line, &fd.file);
            let _ = writeln!(
                out,
                "extern \"C\" void {}(void* h) {{ delete static_cast<{}*>(h); }}\n",
                c.delete_symbol, c.cpp
            );
            for m in &c.members {
                member(&mut out, &fd.file, Some(c), m, known);
            }
        }
        for m in &fd.free {
            member(&mut out, &fd.file, None, m, known);
        }
    }
    out
}

/// Dream lays a value struct out in declaration order with natural alignment and a minimum
/// struct alignment of 4 (`dream_hir::layout::TypeLayout`); `@packed` drops all padding.
fn dream_layout(s: &Struct) -> (Vec<u32>, u32) {
    let mut offsets = Vec::with_capacity(s.fields.len());
    let mut off = 0u32;
    let mut max_align = 4u32;
    for (_, sc) in &s.fields {
        let (size, align) = sc.prim().size_align();
        if !s.packed {
            off = off.div_ceil(align) * align;
            max_align = max_align.max(align);
        }
        offsets.push(off);
        off += size;
    }
    let size = if s.packed {
        off
    } else {
        off.div_ceil(max_align) * max_align
    };
    (offsets, size)
}

fn layout_checks(out: &mut String, file: &str, s: &Struct) {
    let (offsets, size) = dream_layout(s);
    line(out, s.line, file);
    let _ = writeln!(
        out,
        "static_assert(sizeof({cpp}) == {size}, \"@cpp struct '{name}': sizeof({cpp}) differs from the Dream declaration ({size} bytes)\");",
        cpp = s.cpp,
        name = s.name,
    );
    for ((field, _), off) in s.fields.iter().zip(offsets) {
        let _ = writeln!(
            out,
            "static_assert(offsetof({cpp}, {field}) == {off}, \"@cpp struct '{name}': field '{field}' is not at offset {off} in {cpp}\");",
            cpp = s.cpp,
            name = s.name,
        );
    }
    out.push('\n');
}

fn cpp_type<'k>(known: &'k Known, dream: &'k str) -> &'k str {
    known
        .classes
        .get(dream)
        .or_else(|| known.structs.get(dream))
        .map_or(dream, String::as_str)
}

/// The C return type for a result bridge (also the `attempt` value type).
fn c_ret(b: &Bridge) -> &'static str {
    match b {
        Bridge::Scalar(s) => s.c_name(),
        Bridge::Str { .. } => "const char*",
        _ => "void*",
    }
}

fn member(out: &mut String, file: &str, class: Option<&Class>, m: &Member, known: &Known) {
    let mut params: Vec<String> = Vec::new();
    let mut args: Vec<String> = Vec::new();
    if m.kind == MemberKind::Instance {
        params.push("void* __cpp_h".into());
    }
    for (i, p) in m.params.iter().enumerate() {
        let c = format!("p{i}");
        match &p.bridge {
            Bridge::Scalar(s) if p.is_ref => {
                params.push(format!("{}* {c}", s.c_name()));
                args.push(format!("*{c}"));
            }
            Bridge::Scalar(s) => {
                params.push(format!("{} {c}", s.c_name()));
                args.push(c);
            }
            Bridge::Str { optional } => {
                params.push(format!("const char* {c}"));
                args.push(if *optional {
                    format!("dream::opt_str{{{c}}}")
                } else {
                    c
                });
            }
            Bridge::Ptr { .. } => {
                params.push(format!("void* {c}"));
                args.push(format!("dream::any_ptr{{{c}}}"));
            }
            Bridge::Class { name, optional } => {
                let t = cpp_type(known, name);
                params.push(format!("void* {c}"));
                args.push(if *optional {
                    format!("static_cast<{t}*>({c})")
                } else {
                    format!("dream::obj<{t}>{{{c}}}")
                });
            }
            Bridge::Struct(name) => {
                let t = cpp_type(known, name);
                if p.is_ref {
                    params.push(format!("void* {c}"));
                    args.push(format!("*static_cast<{t}*>({c})"));
                } else {
                    params.push(format!("const void* {c}"));
                    args.push(format!("*static_cast<const {t}*>({c})"));
                }
            }
            Bridge::Array(elem) => {
                let t = match elem {
                    Elem::Scalar(s) => s.c_name().to_string(),
                    Elem::Struct(n) => cpp_type(known, n).to_string(),
                };
                params.push(format!("const void* {c}"));
                params.push(format!("int32_t {c}_len"));
                args.push(format!(
                    "dream::slice<{t}>{{static_cast<const {t}*>({c}), {c}_len}}"
                ));
            }
            Bridge::Fun {
                params: fps, ret, ..
            } => {
                params.push(format!("void* {c}_fn"));
                params.push(format!("void* {c}_ud"));
                let mut targs = vec![ret.as_ref().map_or("void", |r| r.callback_c()).to_string()];
                targs.extend(fps.iter().map(|b| b.callback_c().to_string()));
                args.push(format!(
                    "dream::callback<{}>({c}_fn, {c}_ud)",
                    targs.join(", ")
                ));
            }
        }
    }
    let (value, is_result) = match &m.ret {
        Ret::Void => (None, false),
        Ret::Value(b) => (Some(b), false),
        Ret::Result(b) => (Some(b), true),
    };
    if matches!(value, Some(Bridge::Class { .. })) {
        params.push("int32_t* __cpp_owned".into());
    }
    if is_result {
        params.push("int32_t* __cpp_failed".into());
    }
    let class_cpp = class.map(|c| c.cpp.as_str()).unwrap_or("");
    let args = args.join(", ");
    let call = match m.kind {
        MemberKind::Constructor => format!("new {class_cpp}({args})"),
        MemberKind::Instance => format!("static_cast<{class_cpp}*>(__cpp_h)->{}({args})", m.cpp),
        MemberKind::Static => format!("{class_cpp}::{}({args})", m.cpp),
        MemberKind::Free => format!("{}({args})", m.cpp),
    };
    let site = c_string(&match m.kind {
        MemberKind::Constructor => format!("{class_cpp} constructor"),
        MemberKind::Instance | MemberKind::Static => format!("{class_cpp}::{}", m.cpp),
        MemberKind::Free => m.cpp.clone(),
    });
    let thunk = format!("[&]() -> decltype(auto) {{ return {call}; }}");
    let (ret_c, body) = match (m.kind, value) {
        (MemberKind::Constructor, _) => ("void*", format!("static_cast<void*>({call})")),
        (_, None) => ("void", format!("(void)({call})")),
        (_, Some(b)) => (
            c_ret(b),
            match b {
                Bridge::Scalar(s) => format!("dream::out_scalar<{}>({thunk})", s.c_name()),
                Bridge::Str { optional: false } => format!("dream::out_str({thunk})"),
                Bridge::Str { optional: true } => format!("dream::out_opt_str({thunk})"),
                Bridge::Ptr { .. } => format!("dream::out_ptr({thunk})"),
                Bridge::Class { name, optional } => format!(
                    "dream::out_obj<{}, {}, {}>({site}, {thunk}, __cpp_owned)",
                    cpp_type(known, name),
                    m.owned,
                    optional
                ),
                Bridge::Struct(_) | Bridge::Array(_) | Bridge::Fun { .. } => {
                    unreachable!("rejected as a @cpp result by Known::ret")
                }
            },
        ),
    };
    let wrapped = if is_result {
        let fallback = if ret_c == "const char*" {
            "\"\"".to_string()
        } else {
            format!("static_cast<{ret_c}>(0)")
        };
        format!("dream::attempt<{ret_c}>(__cpp_failed, {fallback}, [&]() {{ return {body}; }})")
    } else {
        format!("dream::trap({site}, [&]() {{ return {body}; }})")
    };
    let params = if params.is_empty() {
        "void".to_string()
    } else {
        params.join(", ")
    };
    let _ = writeln!(out, "extern \"C\" {ret_c} {}({params}) {{", m.symbol);
    line(out, m.line, file);
    let _ = writeln!(out, "    return {wrapped};\n}}\n");
}

#[cfg(test)]
mod tests {
    use super::*;
    use dream_types::CScalar;

    #[test]
    fn layout_matches_dream_value_structs() {
        let s = Struct {
            name: "P".into(),
            cpp: "g::P".into(),
            line: 1,
            packed: false,
            fields: vec![("a".into(), CScalar::U8), ("b".into(), CScalar::F64)],
        };
        assert_eq!(dream_layout(&s), (vec![0, 8], 16));
        let packed = Struct { packed: true, ..s };
        assert_eq!(dream_layout(&packed), (vec![0, 1], 9));
    }
}
