// Generated by Dream @compute

@group(0) @binding(0) var<storage, read_write> data: array<f32>;
@group(0) @binding(1) var<storage, read_write> out: array<f32>;
struct DreamUniforms {
  n: i32,
}
@group(0) @binding(2) var<uniform> dream_uniforms: DreamUniforms;

var<workgroup> tile: array<f32, 64>;

@compute @workgroup_size(64, 1, 1)
fn dream_reduce_sum(
  @builtin(global_invocation_id) global_id: vec3<u32>,
  @builtin(local_invocation_id) local_id: vec3<u32>,
  @builtin(workgroup_id) workgroup_id: vec3<u32>,
  @builtin(num_workgroups) num_workgroups: vec3<u32>,
) {
  let global_id_i = vec3<i32>(i32(global_id.x), i32(global_id.y), i32(global_id.z));
  let local_id_i = vec3<i32>(i32(local_id.x), i32(local_id.y), i32(local_id.z));
  let workgroup_id_i = vec3<i32>(i32(workgroup_id.x), i32(workgroup_id.y), i32(workgroup_id.z));
  let num_workgroups_i = vec3<i32>(i32(num_workgroups.x), i32(num_workgroups.y), i32(num_workgroups.z));
  var lid: i32 = local_id_i.x;
  var gid: i32 = global_id_i.x;
  if ((gid < dream_uniforms.n)) {
    tile[lid] = data[u32(gid)];
  }
  else {
    tile[lid] = 0.0;
  }
  workgroupBarrier();
  var stride: i32 = 32;
  loop {
    if (!((stride > 0))) { break; }
    if ((lid < stride)) {
      tile[lid] = (tile[u32(lid)] + tile[u32((lid + stride))]);
    }
    workgroupBarrier();
    stride = (stride / 2);
  }
  if ((lid == 0)) {
    out[workgroup_id_i.x] = tile[u32(0)];
  }
}

