// Generated by Dream @compute

@group(0) @binding(0) var<storage, read_write> dream_add_a: array<f32>;
@group(0) @binding(1) var<storage, read_write> dream_add_b: array<f32>;
@group(0) @binding(2) var<storage, read_write> dream_add_out: array<f32>;
struct DreamUniforms_dream_add {
  n: i32,
}
@group(0) @binding(3) var<uniform> dream_uniforms_dream_add: DreamUniforms_dream_add;

@compute @workgroup_size(64, 1, 1)
fn dream_add(
  @builtin(global_invocation_id) global_id: vec3<u32>,
  @builtin(local_invocation_id) local_id: vec3<u32>,
  @builtin(workgroup_id) workgroup_id: vec3<u32>,
  @builtin(num_workgroups) num_workgroups: vec3<u32>,
) {
  let global_id_i = vec3<i32>(i32(global_id.x), i32(global_id.y), i32(global_id.z));
  let local_id_i = vec3<i32>(i32(local_id.x), i32(local_id.y), i32(local_id.z));
  let workgroup_id_i = vec3<i32>(i32(workgroup_id.x), i32(workgroup_id.y), i32(workgroup_id.z));
  let num_workgroups_i = vec3<i32>(i32(num_workgroups.x), i32(num_workgroups.y), i32(num_workgroups.z));
  var i: i32 = global_id_i.x;
  if ((i < dream_uniforms_dream_add.n)) {
    dream_add_out[i] = (dream_add_a[u32(i)] + dream_add_b[u32(i)]);
  }
}

