// Generated by Dream @compute

@group(0) @binding(0) var<storage, read_write> dream_add_force_vx: array<f32>;
@group(0) @binding(1) var<storage, read_write> dream_add_force_vy: array<f32>;
@group(0) @binding(2) var<storage, read_write> dream_add_force_dye: array<f32>;
struct DreamUniforms_dream_add_force {
  n: i32,
}
@group(0) @binding(3) var<uniform> dream_uniforms_dream_add_force: DreamUniforms_dream_add_force;

@compute @workgroup_size(8, 8, 1)
fn dream_add_force(
  @builtin(global_invocation_id) global_id: vec3<u32>,
  @builtin(local_invocation_id) local_id: vec3<u32>,
  @builtin(workgroup_id) workgroup_id: vec3<u32>,
  @builtin(num_workgroups) num_workgroups: vec3<u32>,
) {
  let global_id_i = vec3<i32>(i32(global_id.x), i32(global_id.y), i32(global_id.z));
  let local_id_i = vec3<i32>(i32(local_id.x), i32(local_id.y), i32(local_id.z));
  let workgroup_id_i = vec3<i32>(i32(workgroup_id.x), i32(workgroup_id.y), i32(workgroup_id.z));
  let num_workgroups_i = vec3<i32>(i32(num_workgroups.x), i32(num_workgroups.y), i32(num_workgroups.z));
  var x: i32 = global_id_i.x;
  var y: i32 = global_id_i.y;
  if (((x >= dream_uniforms_dream_add_force.n) || (y >= dream_uniforms_dream_add_force.n))) {
    return;
  }
  var i: i32 = ((y * dream_uniforms_dream_add_force.n) + x);
  var cx: f32 = f32(((dream_uniforms_dream_add_force.n / 2)));
  var cy: f32 = f32(((dream_uniforms_dream_add_force.n / 2)));
  var dx: f32 = (f32(x) - cx);
  var dy: f32 = (f32(y) - cy);
  var d2: f32 = ((dx * dx) + (dy * dy));
  var rad: f32 = 10.0;
  if ((d2 < (rad * rad))) {
    var w: f32 = (1.0 - (d2 / ((rad * rad))));
    dream_add_force_vx[u32(i)] = (dream_add_force_vx[u32(i)] + (1.5 * w));
    dream_add_force_vy[u32(i)] = (dream_add_force_vy[u32(i)] + (0.8 * w));
    dream_add_force_dye[u32(i)] = (dream_add_force_dye[u32(i)] + (0.45 * w));
    if ((dream_add_force_dye[u32(i)] > 1.0)) {
      dream_add_force_dye[u32(i)] = 1.0;
    }
  }
}

@group(0) @binding(0) var<storage, read_write> dream_advect_src: array<f32>;
@group(0) @binding(1) var<storage, read_write> dream_advect_dst: array<f32>;
@group(0) @binding(2) var<storage, read_write> dream_advect_vx: array<f32>;
@group(0) @binding(3) var<storage, read_write> dream_advect_vy: array<f32>;
struct DreamUniforms_dream_advect {
  n: i32,
}
@group(0) @binding(4) var<uniform> dream_uniforms_dream_advect: DreamUniforms_dream_advect;

@compute @workgroup_size(8, 8, 1)
fn dream_advect(
  @builtin(global_invocation_id) global_id: vec3<u32>,
  @builtin(local_invocation_id) local_id: vec3<u32>,
  @builtin(workgroup_id) workgroup_id: vec3<u32>,
  @builtin(num_workgroups) num_workgroups: vec3<u32>,
) {
  let global_id_i = vec3<i32>(i32(global_id.x), i32(global_id.y), i32(global_id.z));
  let local_id_i = vec3<i32>(i32(local_id.x), i32(local_id.y), i32(local_id.z));
  let workgroup_id_i = vec3<i32>(i32(workgroup_id.x), i32(workgroup_id.y), i32(workgroup_id.z));
  let num_workgroups_i = vec3<i32>(i32(num_workgroups.x), i32(num_workgroups.y), i32(num_workgroups.z));
  var x: i32 = global_id_i.x;
  var y: i32 = global_id_i.y;
  if (((x >= dream_uniforms_dream_advect.n) || (y >= dream_uniforms_dream_advect.n))) {
    return;
  }
  var i: i32 = ((y * dream_uniforms_dream_advect.n) + x);
  var dt: f32 = 0.85;
  var px: f32 = (f32(x) - (dt * dream_advect_vx[u32(i)]));
  var py: f32 = (f32(y) - (dt * dream_advect_vy[u32(i)]));
  if ((px < 0.5)) {
    px = 0.5;
  }
  if ((py < 0.5)) {
    py = 0.5;
  }
  var nm1: f32 = f32(((dream_uniforms_dream_advect.n - 2)));
  if ((px > nm1)) {
    px = nm1;
  }
  if ((py > nm1)) {
    py = nm1;
  }
  var x0: i32 = i32(px);
  var y0: i32 = i32(py);
  var x1: i32 = (x0 + 1);
  var y1: i32 = (y0 + 1);
  var sx: f32 = (px - f32(x0));
  var sy: f32 = (py - f32(y0));
  var v00: f32 = dream_advect_src[u32(((y0 * dream_uniforms_dream_advect.n) + x0))];
  var v10: f32 = dream_advect_src[u32(((y0 * dream_uniforms_dream_advect.n) + x1))];
  var v01: f32 = dream_advect_src[u32(((y1 * dream_uniforms_dream_advect.n) + x0))];
  var v11: f32 = dream_advect_src[u32(((y1 * dream_uniforms_dream_advect.n) + x1))];
  dream_advect_dst[u32(i)] = ((((1.0 - sx)) * (((((1.0 - sy)) * v00) + (sy * v01)))) + (sx * (((((1.0 - sy)) * v10) + (sy * v11)))));
}

@group(0) @binding(0) var<storage, read_write> dream_divergence_vx: array<f32>;
@group(0) @binding(1) var<storage, read_write> dream_divergence_vy: array<f32>;
@group(0) @binding(2) var<storage, read_write> dream_divergence_div: array<f32>;
struct DreamUniforms_dream_divergence {
  n: i32,
}
@group(0) @binding(3) var<uniform> dream_uniforms_dream_divergence: DreamUniforms_dream_divergence;

@compute @workgroup_size(8, 8, 1)
fn dream_divergence(
  @builtin(global_invocation_id) global_id: vec3<u32>,
  @builtin(local_invocation_id) local_id: vec3<u32>,
  @builtin(workgroup_id) workgroup_id: vec3<u32>,
  @builtin(num_workgroups) num_workgroups: vec3<u32>,
) {
  let global_id_i = vec3<i32>(i32(global_id.x), i32(global_id.y), i32(global_id.z));
  let local_id_i = vec3<i32>(i32(local_id.x), i32(local_id.y), i32(local_id.z));
  let workgroup_id_i = vec3<i32>(i32(workgroup_id.x), i32(workgroup_id.y), i32(workgroup_id.z));
  let num_workgroups_i = vec3<i32>(i32(num_workgroups.x), i32(num_workgroups.y), i32(num_workgroups.z));
  var x: i32 = global_id_i.x;
  var y: i32 = global_id_i.y;
  if (((((x <= 0) || (y <= 0)) || (x >= (dream_uniforms_dream_divergence.n - 1))) || (y >= (dream_uniforms_dream_divergence.n - 1)))) {
    return;
  }
  var i: i32 = ((y * dream_uniforms_dream_divergence.n) + x);
  dream_divergence_div[u32(i)] = (0.0 - (0.5 * ((((dream_divergence_vx[u32((i + 1))] - dream_divergence_vx[u32((i - 1))]) + dream_divergence_vy[u32((i + dream_uniforms_dream_divergence.n))]) - dream_divergence_vy[u32((i - dream_uniforms_dream_divergence.n))]))));
}

@group(0) @binding(0) var<storage, read_write> dream_pressure_jacobi_div: array<f32>;
@group(0) @binding(1) var<storage, read_write> dream_pressure_jacobi_p: array<f32>;
@group(0) @binding(2) var<storage, read_write> dream_pressure_jacobi_p_out: array<f32>;
struct DreamUniforms_dream_pressure_jacobi {
  n: i32,
}
@group(0) @binding(3) var<uniform> dream_uniforms_dream_pressure_jacobi: DreamUniforms_dream_pressure_jacobi;

@compute @workgroup_size(8, 8, 1)
fn dream_pressure_jacobi(
  @builtin(global_invocation_id) global_id: vec3<u32>,
  @builtin(local_invocation_id) local_id: vec3<u32>,
  @builtin(workgroup_id) workgroup_id: vec3<u32>,
  @builtin(num_workgroups) num_workgroups: vec3<u32>,
) {
  let global_id_i = vec3<i32>(i32(global_id.x), i32(global_id.y), i32(global_id.z));
  let local_id_i = vec3<i32>(i32(local_id.x), i32(local_id.y), i32(local_id.z));
  let workgroup_id_i = vec3<i32>(i32(workgroup_id.x), i32(workgroup_id.y), i32(workgroup_id.z));
  let num_workgroups_i = vec3<i32>(i32(num_workgroups.x), i32(num_workgroups.y), i32(num_workgroups.z));
  var x: i32 = global_id_i.x;
  var y: i32 = global_id_i.y;
  if (((((x <= 0) || (y <= 0)) || (x >= (dream_uniforms_dream_pressure_jacobi.n - 1))) || (y >= (dream_uniforms_dream_pressure_jacobi.n - 1)))) {
    return;
  }
  var i: i32 = ((y * dream_uniforms_dream_pressure_jacobi.n) + x);
  dream_pressure_jacobi_p_out[u32(i)] = ((((((dream_pressure_jacobi_div[u32(i)] + dream_pressure_jacobi_p[u32((i - 1))]) + dream_pressure_jacobi_p[u32((i + 1))]) + dream_pressure_jacobi_p[u32((i - dream_uniforms_dream_pressure_jacobi.n))]) + dream_pressure_jacobi_p[u32((i + dream_uniforms_dream_pressure_jacobi.n))])) * 0.25);
}

@group(0) @binding(0) var<storage, read_write> dream_subtract_gradient_vx: array<f32>;
@group(0) @binding(1) var<storage, read_write> dream_subtract_gradient_vy: array<f32>;
@group(0) @binding(2) var<storage, read_write> dream_subtract_gradient_p: array<f32>;
struct DreamUniforms_dream_subtract_gradient {
  n: i32,
}
@group(0) @binding(3) var<uniform> dream_uniforms_dream_subtract_gradient: DreamUniforms_dream_subtract_gradient;

@compute @workgroup_size(8, 8, 1)
fn dream_subtract_gradient(
  @builtin(global_invocation_id) global_id: vec3<u32>,
  @builtin(local_invocation_id) local_id: vec3<u32>,
  @builtin(workgroup_id) workgroup_id: vec3<u32>,
  @builtin(num_workgroups) num_workgroups: vec3<u32>,
) {
  let global_id_i = vec3<i32>(i32(global_id.x), i32(global_id.y), i32(global_id.z));
  let local_id_i = vec3<i32>(i32(local_id.x), i32(local_id.y), i32(local_id.z));
  let workgroup_id_i = vec3<i32>(i32(workgroup_id.x), i32(workgroup_id.y), i32(workgroup_id.z));
  let num_workgroups_i = vec3<i32>(i32(num_workgroups.x), i32(num_workgroups.y), i32(num_workgroups.z));
  var x: i32 = global_id_i.x;
  var y: i32 = global_id_i.y;
  if (((((x <= 0) || (y <= 0)) || (x >= (dream_uniforms_dream_subtract_gradient.n - 1))) || (y >= (dream_uniforms_dream_subtract_gradient.n - 1)))) {
    return;
  }
  var i: i32 = ((y * dream_uniforms_dream_subtract_gradient.n) + x);
  dream_subtract_gradient_vx[u32(i)] = (dream_subtract_gradient_vx[u32(i)] - (0.5 * ((dream_subtract_gradient_p[u32((i + 1))] - dream_subtract_gradient_p[u32((i - 1))]))));
  dream_subtract_gradient_vy[u32(i)] = (dream_subtract_gradient_vy[u32(i)] - (0.5 * ((dream_subtract_gradient_p[u32((i + dream_uniforms_dream_subtract_gradient.n))] - dream_subtract_gradient_p[u32((i - dream_uniforms_dream_subtract_gradient.n))]))));
}

