[package]
name = "dream-host-webview"
version = "0.1.0"
edition = "2021"

[lib]
name = "dream_host_webview"
crate-type = ["cdylib"]

[dependencies]
dream-host-core = { path = "../dream-host-core" }
dream-host-abi = { path = "../dream-host-abi" }
dream-abi = { path = "../dream-abi" }
indexmap = "2"
wry = { version = "0.53", features = ["devtools"] }
winit = { version = "0.30" }
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "ico"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
percent-encoding = { version = "2.3" }
rfd = { version = "0.17" }
clipboard-rs = { version = "0.3" }
open = { version = "5" }
dream-host-gui = { path = "../dream-host-gui" }

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
objc2-app-kit = { version = "0.3", default-features = false, features = ["std", "NSApplication", "NSResponder"] }
