;; Generated by scripts/build-runtime.sh from runtime/c. Edit the .c, not this file.
(func $double_to_string (param f64) (result i32)
    (local i64 i64 i32 i32 i32 i32 i32 i32)
    local.get 0
    f64.neg
    local.get 0
    local.get 0
    f64.const 0x0p+0 (;=0;)
    f64.lt
    select
    f64.const 0x1.e848p+19 (;=1e+06;)
    f64.mul
    f64.const 0x1p-1 (;=0.5;)
    f64.add
    i64.trunc_sat_f64_s
    local.tee 1
    i64.const 1000000
    i64.div_s
    local.tee 2
    call $long_to_string
    local.set 3
    i32.const 24
    i32.const 5
    call $malloc
    local.tee 4
    i32.const 8
    i32.add
    local.tee 5
    i32.const 46
    i32.store16
    local.get 4
    i32.const 20
    i32.add
    local.get 1
    local.get 2
    i64.const 1000000
    i64.mul
    i64.sub
    i32.wrap_i64
    local.tee 6
    i32.const 10
    i32.rem_s
    i32.const 48
    i32.add
    local.tee 7
    i32.store16
    local.get 4
    i32.const 10
    i32.add
    local.get 6
    i32.const 100000
    i32.div_s
    i32.const 48
    i32.add
    i32.store16
    local.get 4
    i32.const 18
    i32.add
    local.tee 8
    local.get 6
    i32.const 10
    i32.div_s
    i32.const 10
    i32.rem_s
    i32.const 48
    i32.add
    i32.store16
    local.get 4
    i32.const 16
    i32.add
    local.get 6
    i32.const 100
    i32.div_s
    i32.extend16_s
    i32.const 10
    i32.rem_s
    i32.const 48
    i32.add
    i32.store16
    local.get 4
    i32.const 14
    i32.add
    local.get 6
    i32.const 1000
    i32.div_s
    i32.extend16_s
    i32.const 10
    i32.rem_s
    i32.const 48
    i32.add
    i32.store16
    local.get 4
    i32.const 12
    i32.add
    local.get 6
    i32.const 10000
    i32.div_s
    i32.extend8_s
    i32.const 10
    i32.rem_s
    i32.const 48
    i32.add
    i32.extend8_s
    i32.store16
    block  ;; label = @1
      block  ;; label = @2
        local.get 7
        i32.const 65535
        i32.and
        i32.const 48
        i32.eq
        br_if 0 (;@2;)
        i32.const 7
        local.set 6
        br 1 (;@1;)
      end
      block  ;; label = @2
        local.get 8
        i32.load16_u
        i32.const 48
        i32.eq
        br_if 0 (;@2;)
        i32.const 6
        local.set 6
        br 1 (;@1;)
      end
      block  ;; label = @2
        local.get 4
        i32.const 16
        i32.add
        i32.load16_u
        i32.const 48
        i32.eq
        br_if 0 (;@2;)
        i32.const 5
        local.set 6
        br 1 (;@1;)
      end
      block  ;; label = @2
        local.get 4
        i32.const 14
        i32.add
        i32.load16_u
        i32.const 48
        i32.eq
        br_if 0 (;@2;)
        i32.const 4
        local.set 6
        br 1 (;@1;)
      end
      block  ;; label = @2
        local.get 4
        i32.const 12
        i32.add
        i32.load16_u
        i32.const 48
        i32.eq
        br_if 0 (;@2;)
        i32.const 3
        local.set 6
        br 1 (;@1;)
      end
      i32.const 0
      i32.const 2
      local.get 6
      i32.const 99999
      i32.add
      i32.const 199999
      i32.lt_u
      select
      local.set 6
    end
    local.get 4
    local.get 6
    i32.store
    block  ;; label = @1
      local.get 4
      i32.eqz
      br_if 0 (;@1;)
      local.get 4
      i32.const 4
      i32.add
      local.get 5
      i32.store
    end
    local.get 3
    local.get 4
    call $concat_strings
    local.set 4
    block  ;; label = @1
      local.get 0
      f64.const 0x0p+0 (;=0;)
      f64.lt
      i32.eqz
      br_if 0 (;@1;)
      call $__rt_str_minus_get
      local.get 4
      call $concat_strings
      local.set 4
    end
    local.get 4)

(func $float_to_string (param f32) (result i32)
    local.get 0
    f64.promote_f32
    call $double_to_string)
