;; Generated by scripts/build-runtime.sh from runtime/c. Edit the .c, not this file.
(func $box_int (param i32) (result i32)
    (local i32)
    i32.const 4
    i32.const 1
    call $malloc
    local.tee 1
    local.get 0
    i32.store
    local.get 1)

(func $box_float (param f32) (result i32)
    (local i32)
    i32.const 4
    i32.const 2
    call $malloc
    local.tee 1
    local.get 0
    f32.store
    local.get 1)

(func $box_double (param f64) (result i32)
    (local i32)
    i32.const 8
    i32.const 3
    call $malloc
    local.tee 1
    local.get 0
    f64.store
    local.get 1)

(func $box_bool (param i32) (result i32)
    (local i32)
    i32.const 4
    i32.const 4
    call $malloc
    local.tee 1
    local.get 0
    i32.store
    local.get 1)

(func $unbox_int (param i32) (result i32)
    local.get 0
    i32.load)

(func $unbox_float (param i32) (result f32)
    local.get 0
    f32.load)

(func $unbox_double (param i32) (result f64)
    local.get 0
    f64.load)

(func $unbox_bool (param i32) (result i32)
    local.get 0
    i32.load)

(func $hash_int (param i32) (result i32)
    local.get 0)

(func $hash_bool (param i32) (result i32)
    local.get 0)

(func $hash_float (param f32) (result i32)
    local.get 0
    i32.reinterpret_f32)

(func $hash_double (param f64) (result i32)
    local.get 0
    f32.demote_f64
    i32.reinterpret_f32)

(func $hash_string (param i32) (result i32)
    (local i32 i32 i32 i32)
    block  ;; label = @1
      local.get 0
      br_if 0 (;@1;)
      i32.const 0
      return
    end
    i32.const -2128831035
    local.set 1
    local.get 0
    i32.load
    local.set 2
    local.get 0
    i32.const 4
    i32.add
    i32.load
    local.tee 4
    local.get 0
    i32.const 8
    i32.add
    local.get 4
    select
    local.set 4
    i32.const 0
    local.set 3
    block  ;; label = @1
      loop  ;; label = @2
        local.get 3
        local.get 2
        i32.ge_s
        br_if 1 (;@1;)
        local.get 1
        local.get 4
        local.get 3
        i32.const 1
        i32.shl
        i32.add
        i32.load16_u
        i32.xor
        i32.const 16777619
        i32.mul
        local.set 1
        local.get 3
        i32.const 1
        i32.add
        local.set 3
        br 0 (;@2;)
      end
    end
    local.get 1)

(func $int_to_string (param i32) (result i32)
    (local i32 i32 i32 i32 i32 i32 i32)
    i32.const 32
    i32.const 5
    call $malloc
    local.tee 1
    i32.const 8
    i32.add
    local.set 2
    block  ;; label = @1
      block  ;; label = @2
        block  ;; label = @3
          block  ;; label = @4
            local.get 0
            i32.eqz
            br_if 0 (;@4;)
            local.get 2
            local.set 3
            i32.const 1
            local.set 4
            local.get 0
            local.set 5
            loop  ;; label = @5
              local.get 3
              local.get 5
              local.tee 6
              local.get 6
              i32.const 10
              i32.div_s
              local.tee 5
              i32.const 10
              i32.mul
              i32.sub
              local.tee 7
              local.get 7
              i32.const 31
              i32.shr_s
              local.tee 7
              i32.xor
              local.get 7
              i32.sub
              i32.const 48
              i32.add
              i32.store16
              local.get 3
              i32.const 2
              i32.add
              local.set 3
              local.get 4
              i32.const 1
              i32.add
              local.set 4
              local.get 6
              i32.const 9
              i32.add
              i32.const 18
              i32.gt_u
              br_if 0 (;@5;)
            end
            local.get 0
            i32.const -1
            i32.le_s
            br_if 1 (;@3;)
            local.get 4
            i32.const -1
            i32.add
            local.set 4
            br 2 (;@2;)
          end
          local.get 1
          i32.const 1
          i32.store
          local.get 1
          i32.const 8
          i32.add
          i32.const 48
          i32.store16
          local.get 1
          i32.eqz
          br_if 2 (;@1;)
          local.get 1
          i32.const 4
          i32.add
          local.get 2
          i32.store
          local.get 1
          return
        end
        local.get 3
        i32.const 45
        i32.store16
      end
      local.get 1
      local.get 4
      i32.store
      block  ;; label = @2
        local.get 1
        i32.eqz
        br_if 0 (;@2;)
        local.get 1
        i32.const 4
        i32.add
        local.get 2
        i32.store
      end
      local.get 4
      i32.const 2
      i32.lt_s
      br_if 0 (;@1;)
      local.get 4
      i32.const -1
      i32.add
      local.set 5
      local.get 1
      local.get 4
      i32.const 1
      i32.shl
      i32.add
      i32.const 6
      i32.add
      local.set 3
      i32.const 1
      local.set 6
      loop  ;; label = @2
        local.get 2
        i32.load16_u
        local.set 4
        local.get 2
        local.get 3
        i32.load16_u
        i32.store16
        local.get 3
        local.get 4
        i32.store16
        local.get 2
        i32.const 2
        i32.add
        local.set 2
        local.get 3
        i32.const -2
        i32.add
        local.set 3
        local.get 6
        local.get 5
        i32.const -1
        i32.add
        local.tee 5
        i32.lt_s
        local.set 4
        local.get 6
        i32.const 1
        i32.add
        local.set 6
        local.get 4
        br_if 0 (;@2;)
      end
    end
    local.get 1)

(func $box_char (param i32) (result i32)
    (local i32)
    i32.const 4
    i32.const 7
    call $malloc
    local.tee 1
    local.get 0
    i32.store
    local.get 1)

(func $unbox_char (param i32) (result i32)
    local.get 0
    i32.load)

(func $char_to_string (param i32) (result i32)
    (local i32 i32)
    i32.const 16
    i32.const 5
    call $malloc
    local.set 1
    local.get 1
    local.get 1
    i32.const 8
    i32.add
    local.tee 2
    i32.const 0
    local.get 0
    call $utf16_encode_at
    i32.store
    block  ;; label = @1
      local.get 1
      i32.eqz
      br_if 0 (;@1;)
      local.get 1
      i32.const 4
      i32.add
      local.get 2
      i32.store
    end
    local.get 1)

(func $box_byte (param i32) (result i32)
    (local i32)
    i32.const 4
    i32.const 11
    call $malloc
    local.tee 1
    local.get 0
    i32.store
    local.get 1)

(func $box_uint (param i32) (result i32)
    (local i32)
    i32.const 4
    i32.const 9
    call $malloc
    local.tee 1
    local.get 0
    i32.store
    local.get 1)

(func $box_long (param i64) (result i32)
    (local i32)
    i32.const 8
    i32.const 8
    call $malloc
    local.tee 1
    local.get 0
    i64.store
    local.get 1)

(func $box_ulong (param i64) (result i32)
    (local i32)
    i32.const 8
    i32.const 10
    call $malloc
    local.tee 1
    local.get 0
    i64.store
    local.get 1)

(func $unbox_byte (param i32) (result i32)
    local.get 0
    i32.load)

(func $unbox_uint (param i32) (result i32)
    local.get 0
    i32.load)

(func $unbox_long (param i32) (result i64)
    local.get 0
    i64.load)

(func $unbox_ulong (param i32) (result i64)
    local.get 0
    i64.load)

(func $byte_to_string (param i32) (result i32)
    (local i32 i32 i32 i32 i32 i32 i32)
    i32.const 32
    i32.const 5
    call $malloc
    local.tee 1
    i32.const 8
    i32.add
    local.set 2
    block  ;; label = @1
      block  ;; label = @2
        block  ;; label = @3
          block  ;; label = @4
            local.get 0
            i32.eqz
            br_if 0 (;@4;)
            local.get 2
            local.set 3
            i32.const 1
            local.set 4
            local.get 0
            local.set 5
            loop  ;; label = @5
              local.get 3
              local.get 5
              local.tee 6
              local.get 6
              i32.const 10
              i32.div_s
              local.tee 5
              i32.const 10
              i32.mul
              i32.sub
              local.tee 7
              local.get 7
              i32.const 31
              i32.shr_s
              local.tee 7
              i32.xor
              local.get 7
              i32.sub
              i32.const 48
              i32.add
              i32.store16
              local.get 3
              i32.const 2
              i32.add
              local.set 3
              local.get 4
              i32.const 1
              i32.add
              local.set 4
              local.get 6
              i32.const 9
              i32.add
              i32.const 18
              i32.gt_u
              br_if 0 (;@5;)
            end
            local.get 0
            i32.const -1
            i32.le_s
            br_if 1 (;@3;)
            local.get 4
            i32.const -1
            i32.add
            local.set 4
            br 2 (;@2;)
          end
          local.get 1
          i32.const 1
          i32.store
          local.get 1
          i32.const 8
          i32.add
          i32.const 48
          i32.store16
          local.get 1
          i32.eqz
          br_if 2 (;@1;)
          local.get 1
          i32.const 4
          i32.add
          local.get 2
          i32.store
          local.get 1
          return
        end
        local.get 3
        i32.const 45
        i32.store16
      end
      local.get 1
      local.get 4
      i32.store
      block  ;; label = @2
        local.get 1
        i32.eqz
        br_if 0 (;@2;)
        local.get 1
        i32.const 4
        i32.add
        local.get 2
        i32.store
      end
      local.get 4
      i32.const 2
      i32.lt_s
      br_if 0 (;@1;)
      local.get 4
      i32.const -1
      i32.add
      local.set 5
      local.get 1
      local.get 4
      i32.const 1
      i32.shl
      i32.add
      i32.const 6
      i32.add
      local.set 3
      i32.const 1
      local.set 6
      loop  ;; label = @2
        local.get 2
        i32.load16_u
        local.set 4
        local.get 2
        local.get 3
        i32.load16_u
        i32.store16
        local.get 3
        local.get 4
        i32.store16
        local.get 2
        i32.const 2
        i32.add
        local.set 2
        local.get 3
        i32.const -2
        i32.add
        local.set 3
        local.get 6
        local.get 5
        i32.const -1
        i32.add
        local.tee 5
        i32.lt_s
        local.set 4
        local.get 6
        i32.const 1
        i32.add
        local.set 6
        local.get 4
        br_if 0 (;@2;)
      end
    end
    local.get 1)

(func $uint_to_string (param i32) (result i32)
    (local i32 i32 i32 i64 i64 i32 i32)
    i32.const 56
    i32.const 5
    call $malloc
    local.tee 1
    i32.const 8
    i32.add
    local.set 2
    block  ;; label = @1
      block  ;; label = @2
        local.get 0
        i32.eqz
        br_if 0 (;@2;)
        local.get 1
        i32.const 6
        i32.add
        local.set 3
        local.get 0
        i64.extend_i32_u
        local.set 4
        i32.const -1
        local.set 0
        loop  ;; label = @3
          local.get 3
          i32.const 2
          i32.add
          local.tee 3
          local.get 4
          local.get 4
          i64.const 10
          i64.div_u
          local.tee 5
          i64.const 10
          i64.mul
          i64.sub
          i32.wrap_i64
          i32.const 48
          i32.or
          i32.store16
          local.get 0
          i32.const 1
          i32.add
          local.set 0
          local.get 4
          i64.const 9
          i64.gt_u
          local.set 6
          local.get 5
          local.set 4
          local.get 6
          br_if 0 (;@3;)
        end
        local.get 1
        local.get 0
        i32.const 1
        i32.add
        i32.store
        block  ;; label = @3
          local.get 1
          i32.eqz
          br_if 0 (;@3;)
          local.get 1
          i32.const 4
          i32.add
          local.get 2
          i32.store
        end
        local.get 0
        i32.eqz
        br_if 1 (;@1;)
        i32.const 1
        local.set 6
        loop  ;; label = @3
          local.get 2
          i32.load16_u
          local.set 7
          local.get 2
          local.get 3
          i32.load16_u
          i32.store16
          local.get 3
          local.get 7
          i32.store16
          local.get 2
          i32.const 2
          i32.add
          local.set 2
          local.get 3
          i32.const -2
          i32.add
          local.set 3
          local.get 6
          local.get 0
          i32.const -1
          i32.add
          local.tee 0
          i32.lt_s
          local.set 7
          local.get 6
          i32.const 1
          i32.add
          local.set 6
          local.get 7
          br_if 0 (;@3;)
          br 2 (;@1;)
        end
      end
      local.get 1
      i32.const 1
      i32.store
      local.get 1
      i32.const 8
      i32.add
      i32.const 48
      i32.store16
      local.get 1
      i32.eqz
      br_if 0 (;@1;)
      local.get 1
      i32.const 4
      i32.add
      local.get 2
      i32.store
    end
    local.get 1)

(func $ulong_to_string (param i64) (result i32)
    (local i32 i32 i32 i32 i64 i32 i32)
    i32.const 56
    i32.const 5
    call $malloc
    local.tee 1
    i32.const 8
    i32.add
    local.set 2
    block  ;; label = @1
      block  ;; label = @2
        local.get 0
        i64.eqz
        br_if 0 (;@2;)
        local.get 1
        i32.const 6
        i32.add
        local.set 3
        i32.const -1
        local.set 4
        loop  ;; label = @3
          local.get 3
          i32.const 2
          i32.add
          local.tee 3
          local.get 0
          local.get 0
          i64.const 10
          i64.div_u
          local.tee 5
          i64.const 10
          i64.mul
          i64.sub
          i32.wrap_i64
          i32.const 48
          i32.or
          i32.store16
          local.get 4
          i32.const 1
          i32.add
          local.set 4
          local.get 0
          i64.const 9
          i64.gt_u
          local.set 6
          local.get 5
          local.set 0
          local.get 6
          br_if 0 (;@3;)
        end
        local.get 1
        local.get 4
        i32.const 1
        i32.add
        i32.store
        block  ;; label = @3
          local.get 1
          i32.eqz
          br_if 0 (;@3;)
          local.get 1
          i32.const 4
          i32.add
          local.get 2
          i32.store
        end
        local.get 4
        i32.eqz
        br_if 1 (;@1;)
        i32.const 1
        local.set 6
        loop  ;; label = @3
          local.get 2
          i32.load16_u
          local.set 7
          local.get 2
          local.get 3
          i32.load16_u
          i32.store16
          local.get 3
          local.get 7
          i32.store16
          local.get 2
          i32.const 2
          i32.add
          local.set 2
          local.get 3
          i32.const -2
          i32.add
          local.set 3
          local.get 6
          local.get 4
          i32.const -1
          i32.add
          local.tee 4
          i32.lt_s
          local.set 7
          local.get 6
          i32.const 1
          i32.add
          local.set 6
          local.get 7
          br_if 0 (;@3;)
          br 2 (;@1;)
        end
      end
      local.get 1
      i32.const 1
      i32.store
      local.get 1
      i32.const 8
      i32.add
      i32.const 48
      i32.store16
      local.get 1
      i32.eqz
      br_if 0 (;@1;)
      local.get 1
      i32.const 4
      i32.add
      local.get 2
      i32.store
    end
    local.get 1)

(func $hash_long (param i64) (result i32)
    local.get 0
    i64.const 32
    i64.shr_u
    local.get 0
    i64.xor
    i32.wrap_i64)

(func $long_to_string (param i64) (result i32)
    (local i32 i32 i32 i32 i64 i64 i64 i32 i32)
    i32.const 56
    i32.const 5
    call $malloc
    local.tee 1
    i32.const 8
    i32.add
    local.set 2
    block  ;; label = @1
      block  ;; label = @2
        block  ;; label = @3
          block  ;; label = @4
            local.get 0
            i64.eqz
            br_if 0 (;@4;)
            local.get 2
            local.set 3
            i32.const 1
            local.set 4
            local.get 0
            local.set 5
            loop  ;; label = @5
              local.get 3
              i32.const 0
              local.get 5
              local.get 5
              i64.const 10
              i64.div_s
              local.tee 6
              i64.const 10
              i64.mul
              i64.sub
              local.tee 7
              i32.wrap_i64
              local.tee 8
              i32.sub
              local.get 8
              local.get 7
              i64.const 0
              i64.lt_s
              select
              i32.const 48
              i32.add
              i32.store16
              local.get 3
              i32.const 2
              i32.add
              local.set 3
              local.get 4
              i32.const 1
              i32.add
              local.set 4
              local.get 5
              i64.const 9
              i64.add
              local.set 7
              local.get 6
              local.set 5
              local.get 7
              i64.const 18
              i64.gt_u
              br_if 0 (;@5;)
            end
            local.get 0
            i64.const -1
            i64.le_s
            br_if 1 (;@3;)
            local.get 4
            i32.const -1
            i32.add
            local.set 4
            br 2 (;@2;)
          end
          local.get 1
          i32.const 1
          i32.store
          local.get 1
          i32.const 8
          i32.add
          i32.const 48
          i32.store16
          local.get 1
          i32.eqz
          br_if 2 (;@1;)
          local.get 1
          i32.const 4
          i32.add
          local.get 2
          i32.store
          local.get 1
          return
        end
        local.get 3
        i32.const 45
        i32.store16
      end
      local.get 1
      local.get 4
      i32.store
      block  ;; label = @2
        local.get 1
        i32.eqz
        br_if 0 (;@2;)
        local.get 1
        i32.const 4
        i32.add
        local.get 2
        i32.store
      end
      local.get 4
      i32.const 2
      i32.lt_s
      br_if 0 (;@1;)
      local.get 4
      i32.const -1
      i32.add
      local.set 8
      local.get 1
      local.get 4
      i32.const 1
      i32.shl
      i32.add
      i32.const 6
      i32.add
      local.set 3
      i32.const 1
      local.set 4
      loop  ;; label = @2
        local.get 2
        i32.load16_u
        local.set 9
        local.get 2
        local.get 3
        i32.load16_u
        i32.store16
        local.get 3
        local.get 9
        i32.store16
        local.get 2
        i32.const 2
        i32.add
        local.set 2
        local.get 3
        i32.const -2
        i32.add
        local.set 3
        local.get 4
        local.get 8
        i32.const -1
        i32.add
        local.tee 8
        i32.lt_s
        local.set 9
        local.get 4
        i32.const 1
        i32.add
        local.set 4
        local.get 9
        br_if 0 (;@2;)
      end
    end
    local.get 1)
