;; Generated by scripts/build-runtime.sh from runtime/c. Edit the .c, not this file.
(func $string_fini (param i32)
    (local i32)
    block  ;; label = @1
      local.get 0
      i32.eqz
      br_if 0 (;@1;)
      local.get 0
      i32.const -8
      i32.add
      i32.load
      i32.const 5
      i32.ne
      br_if 0 (;@1;)
      local.get 0
      i32.const 4
      i32.add
      i32.load
      local.tee 1
      i32.eqz
      br_if 0 (;@1;)
      local.get 1
      local.get 0
      i32.const 8
      i32.add
      local.tee 0
      i32.eq
      br_if 0 (;@1;)
      local.get 0
      i32.load
      call $release_generic
    end)

(func $string_release (param i32)
    (local i32 i32)
    block  ;; label = @1
      local.get 0
      i32.eqz
      br_if 0 (;@1;)
      local.get 0
      i32.const -8
      i32.add
      i32.load
      i32.const 5
      i32.ne
      br_if 0 (;@1;)
      local.get 0
      i32.const 4
      i32.add
      i32.load
      local.tee 1
      i32.eqz
      br_if 0 (;@1;)
      local.get 1
      local.get 0
      i32.const 8
      i32.add
      local.tee 2
      i32.eq
      br_if 0 (;@1;)
      local.get 2
      i32.load
      call $release_generic
    end
    local.get 0
    call $release_generic)

(func $str_byte_size (param i32) (result i32)
    local.get 0
    i32.load
    i32.const 1
    i32.shl)

(func $strlen (param i32) (result i32)
    local.get 0
    i32.load
    i32.const 1
    i32.shl)

(func $utf8_width_at (param i32 i32) (result i32)
    i32.const 2)

(func $utf8_decode_at (param i32 i32) (result i32)
    (local i32)
    block  ;; label = @1
      block  ;; label = @2
        local.get 0
        br_if 0 (;@2;)
        i32.const 0
        local.set 0
        br 1 (;@1;)
      end
      local.get 0
      i32.const 4
      i32.add
      i32.load
      local.tee 2
      local.get 0
      i32.const 8
      i32.add
      local.get 2
      select
      local.set 0
    end
    local.get 0
    local.get 1
    i32.add
    i32.load16_u)

(func $utf8_width_raw (param i32 i32) (result i32)
    block  ;; label = @1
      local.get 1
      local.get 0
      i32.add
      i32.load8_s
      local.tee 0
      i32.const -1
      i32.le_s
      br_if 0 (;@1;)
      i32.const 1
      return
    end
    block  ;; label = @1
      local.get 0
      i32.const 255
      i32.and
      local.tee 0
      i32.const 224
      i32.and
      i32.const 192
      i32.ne
      br_if 0 (;@1;)
      i32.const 2
      return
    end
    i32.const 3
    i32.const 4
    local.get 0
    i32.const 240
    i32.and
    i32.const 224
    i32.eq
    select)

(func $utf8_decode_raw (param i32 i32) (result i32)
    (local i32 i32)
    local.get 1
    local.get 0
    i32.add
    local.tee 2
    i32.load8_s
    local.tee 1
    i32.const 255
    i32.and
    local.set 0
    block  ;; label = @1
      local.get 1
      i32.const -1
      i32.gt_s
      br_if 0 (;@1;)
      block  ;; label = @2
        local.get 0
        i32.const 224
        i32.and
        i32.const 192
        i32.ne
        br_if 0 (;@2;)
        local.get 0
        i32.const 6
        i32.shl
        i32.const 1984
        i32.and
        local.get 2
        i32.const 1
        i32.add
        i32.load8_u
        i32.const 63
        i32.and
        i32.or
        return
      end
      local.get 2
      i32.const 2
      i32.add
      i32.load8_u
      local.set 1
      local.get 2
      i32.const 1
      i32.add
      i32.load8_u
      local.set 3
      block  ;; label = @2
        local.get 0
        i32.const 240
        i32.and
        i32.const 224
        i32.ne
        br_if 0 (;@2;)
        local.get 3
        i32.const 63
        i32.and
        i32.const 6
        i32.shl
        local.get 0
        i32.const 12
        i32.shl
        i32.const 61440
        i32.and
        i32.or
        local.get 1
        i32.const 63
        i32.and
        i32.or
        return
      end
      local.get 3
      i32.const 63
      i32.and
      i32.const 12
      i32.shl
      local.get 0
      i32.const 18
      i32.shl
      i32.const 1835008
      i32.and
      i32.or
      local.get 1
      i32.const 63
      i32.and
      i32.const 6
      i32.shl
      i32.or
      local.get 2
      i32.const 3
      i32.add
      i32.load8_u
      i32.const 63
      i32.and
      i32.or
      local.set 0
    end
    local.get 0)

(func $utf16_encode_at (param i32 i32 i32) (result i32)
    (local i32)
    i32.const 1
    local.set 3
    local.get 1
    i32.const 1
    i32.shl
    local.get 0
    i32.add
    local.set 1
    block  ;; label = @1
      local.get 2
      i32.const 65535
      i32.le_u
      br_if 0 (;@1;)
      local.get 1
      local.get 2
      i32.const 67043328
      i32.add
      i32.const 10
      i32.shr_u
      i32.const -10240
      i32.add
      i32.store16
      local.get 2
      i32.const 1023
      i32.and
      i32.const -9216
      i32.or
      local.set 2
      i32.const 2
      local.set 3
      local.get 1
      i32.const 2
      i32.add
      local.set 1
    end
    local.get 1
    local.get 2
    i32.store16
    local.get 3)

(func $str_scalar_len (param i32) (result i32)
    local.get 0
    i32.load)

(func $concat_strings (param i32 i32) (result i32)
    (local i32 i32 i32 i32 i32 i32 i32 i32 i32)
    local.get 1
    i32.load
    local.tee 2
    i32.const 1
    i32.shl
    local.set 3
    block  ;; label = @1
      local.get 0
      i32.load
      local.tee 4
      i32.const 1
      i32.shl
      local.tee 5
      br_if 0 (;@1;)
      block  ;; label = @2
        local.get 3
        br_if 0 (;@2;)
        call $__rt_str_empty_get
        local.set 1
      end
      local.get 1
      call $retain
      local.get 1
      return
    end
    block  ;; label = @1
      local.get 3
      br_if 0 (;@1;)
      local.get 0
      local.tee 0
      call $retain
      local.get 0
      return
    end
    local.get 5
    local.get 3
    i32.add
    i32.const 8
    i32.add
    i32.const 5
    call $malloc
    local.tee 6
    local.get 2
    local.get 4
    i32.add
    i32.store
    block  ;; label = @1
      local.get 6
      i32.eqz
      br_if 0 (;@1;)
      local.get 6
      i32.const 4
      i32.add
      local.get 6
      i32.const 8
      i32.add
      i32.store
    end
    block  ;; label = @1
      block  ;; label = @2
        local.get 0
        br_if 0 (;@2;)
        i32.const 0
        local.set 7
        br 1 (;@1;)
      end
      local.get 0
      i32.const 4
      i32.add
      i32.load
      local.tee 2
      local.get 0
      i32.const 8
      i32.add
      local.get 2
      select
      local.set 7
    end
    block  ;; label = @1
      local.get 5
      i32.const 1
      i32.lt_s
      br_if 0 (;@1;)
      i32.const 0
      local.set 0
      i32.const 0
      local.set 2
      block  ;; label = @2
        local.get 5
        i32.const 4
        i32.lt_u
        br_if 0 (;@2;)
        local.get 5
        i32.const 2
        i32.and
        local.set 8
        local.get 5
        i32.const 2147483644
        i32.and
        local.set 9
        i32.const 0
        local.set 2
        loop  ;; label = @3
          local.get 6
          local.get 2
          i32.add
          local.tee 4
          i32.const 8
          i32.add
          local.get 7
          local.get 2
          i32.add
          local.tee 10
          i32.load8_u
          i32.store8
          local.get 4
          i32.const 9
          i32.add
          local.get 10
          i32.const 1
          i32.add
          i32.load8_u
          i32.store8
          local.get 4
          i32.const 10
          i32.add
          local.get 10
          i32.const 2
          i32.add
          i32.load8_u
          i32.store8
          local.get 4
          i32.const 11
          i32.add
          local.get 10
          i32.const 3
          i32.add
          i32.load8_u
          i32.store8
          local.get 9
          local.get 2
          i32.const 4
          i32.add
          local.tee 2
          i32.ne
          br_if 0 (;@3;)
        end
        local.get 8
        i32.eqz
        br_if 1 (;@1;)
      end
      local.get 7
      local.get 2
      i32.add
      local.set 4
      local.get 6
      local.get 2
      i32.add
      i32.const 8
      i32.add
      local.set 2
      loop  ;; label = @2
        local.get 2
        local.get 0
        i32.add
        local.get 4
        local.get 0
        i32.add
        i32.load8_u
        i32.store8
        local.get 0
        i32.const 1
        i32.add
        local.tee 0
        i32.const 2
        i32.ne
        br_if 0 (;@2;)
      end
    end
    block  ;; label = @1
      block  ;; label = @2
        local.get 1
        br_if 0 (;@2;)
        i32.const 0
        local.set 7
        br 1 (;@1;)
      end
      local.get 1
      i32.const 4
      i32.add
      i32.load
      local.tee 0
      local.get 1
      i32.const 8
      i32.add
      local.get 0
      select
      local.set 7
    end
    block  ;; label = @1
      local.get 3
      i32.const 1
      i32.lt_s
      br_if 0 (;@1;)
      i32.const 0
      local.set 0
      i32.const 0
      local.set 2
      block  ;; label = @2
        local.get 3
        i32.const 4
        i32.lt_u
        br_if 0 (;@2;)
        local.get 3
        i32.const 2
        i32.and
        local.set 8
        local.get 6
        local.get 5
        i32.add
        local.set 9
        local.get 3
        i32.const 2147483644
        i32.and
        local.set 1
        i32.const 0
        local.set 2
        loop  ;; label = @3
          local.get 9
          local.get 2
          i32.add
          local.tee 4
          i32.const 8
          i32.add
          local.get 7
          local.get 2
          i32.add
          local.tee 10
          i32.load8_u
          i32.store8
          local.get 4
          i32.const 9
          i32.add
          local.get 10
          i32.const 1
          i32.add
          i32.load8_u
          i32.store8
          local.get 4
          i32.const 10
          i32.add
          local.get 10
          i32.const 2
          i32.add
          i32.load8_u
          i32.store8
          local.get 4
          i32.const 11
          i32.add
          local.get 10
          i32.const 3
          i32.add
          i32.load8_u
          i32.store8
          local.get 1
          local.get 2
          i32.const 4
          i32.add
          local.tee 2
          i32.ne
          br_if 0 (;@3;)
        end
        local.get 8
        i32.eqz
        br_if 1 (;@1;)
      end
      local.get 7
      local.get 2
      i32.add
      local.set 4
      local.get 6
      local.get 2
      i32.add
      local.get 5
      i32.add
      i32.const 8
      i32.add
      local.set 2
      loop  ;; label = @2
        local.get 2
        local.get 0
        i32.add
        local.get 4
        local.get 0
        i32.add
        i32.load8_u
        i32.store8
        local.get 0
        i32.const 1
        i32.add
        local.tee 0
        i32.const 2
        i32.ne
        br_if 0 (;@2;)
      end
    end
    local.get 6)

(func $concat_strings3 (param i32 i32 i32) (result i32)
    (local i32 i32 i32 i32 i32 i32 i32 i32 i32 i32)
    block  ;; label = @1
      local.get 1
      i32.load
      local.tee 3
      i32.const 1
      i32.shl
      local.tee 4
      local.get 0
      i32.load
      local.tee 5
      i32.const 1
      i32.shl
      local.tee 6
      i32.add
      local.get 2
      i32.load
      local.tee 7
      i32.const 1
      i32.shl
      local.tee 8
      i32.add
      local.tee 9
      br_if 0 (;@1;)
      call $__rt_str_empty_get
      local.tee 0
      call $retain
      local.get 0
      return
    end
    block  ;; label = @1
      local.get 6
      br_if 0 (;@1;)
      local.get 1
      local.get 2
      call $concat_strings
      return
    end
    block  ;; label = @1
      local.get 4
      br_if 0 (;@1;)
      local.get 0
      local.get 2
      call $concat_strings
      return
    end
    block  ;; label = @1
      local.get 8
      br_if 0 (;@1;)
      local.get 0
      local.get 1
      call $concat_strings
      return
    end
    local.get 9
    i32.const 8
    i32.add
    i32.const 5
    call $malloc
    local.tee 9
    local.get 3
    local.get 5
    i32.add
    local.get 7
    i32.add
    i32.store
    block  ;; label = @1
      local.get 9
      i32.eqz
      br_if 0 (;@1;)
      local.get 9
      i32.const 4
      i32.add
      local.get 9
      i32.const 8
      i32.add
      i32.store
    end
    block  ;; label = @1
      block  ;; label = @2
        local.get 0
        br_if 0 (;@2;)
        i32.const 0
        local.set 10
        br 1 (;@1;)
      end
      local.get 0
      i32.const 4
      i32.add
      i32.load
      local.tee 3
      local.get 0
      i32.const 8
      i32.add
      local.get 3
      select
      local.set 10
    end
    block  ;; label = @1
      local.get 6
      i32.const 1
      i32.lt_s
      br_if 0 (;@1;)
      i32.const 0
      local.set 0
      i32.const 0
      local.set 3
      block  ;; label = @2
        local.get 6
        i32.const 4
        i32.lt_u
        br_if 0 (;@2;)
        local.get 6
        i32.const 2
        i32.and
        local.set 11
        local.get 6
        i32.const 2147483644
        i32.and
        local.set 12
        i32.const 0
        local.set 3
        loop  ;; label = @3
          local.get 9
          local.get 3
          i32.add
          local.tee 5
          i32.const 8
          i32.add
          local.get 10
          local.get 3
          i32.add
          local.tee 7
          i32.load8_u
          i32.store8
          local.get 5
          i32.const 9
          i32.add
          local.get 7
          i32.const 1
          i32.add
          i32.load8_u
          i32.store8
          local.get 5
          i32.const 10
          i32.add
          local.get 7
          i32.const 2
          i32.add
          i32.load8_u
          i32.store8
          local.get 5
          i32.const 11
          i32.add
          local.get 7
          i32.const 3
          i32.add
          i32.load8_u
          i32.store8
          local.get 12
          local.get 3
          i32.const 4
          i32.add
          local.tee 3
          i32.ne
          br_if 0 (;@3;)
        end
        local.get 11
        i32.eqz
        br_if 1 (;@1;)
      end
      local.get 10
      local.get 3
      i32.add
      local.set 5
      local.get 9
      local.get 3
      i32.add
      i32.const 8
      i32.add
      local.set 3
      loop  ;; label = @2
        local.get 3
        local.get 0
        i32.add
        local.get 5
        local.get 0
        i32.add
        i32.load8_u
        i32.store8
        local.get 0
        i32.const 1
        i32.add
        local.tee 0
        i32.const 2
        i32.ne
        br_if 0 (;@2;)
      end
    end
    block  ;; label = @1
      block  ;; label = @2
        local.get 1
        br_if 0 (;@2;)
        i32.const 0
        local.set 1
        br 1 (;@1;)
      end
      local.get 1
      i32.const 4
      i32.add
      i32.load
      local.tee 0
      local.get 1
      i32.const 8
      i32.add
      local.get 0
      select
      local.set 1
    end
    block  ;; label = @1
      local.get 4
      i32.const 1
      i32.lt_s
      br_if 0 (;@1;)
      i32.const 0
      local.set 0
      i32.const 0
      local.set 3
      block  ;; label = @2
        local.get 4
        i32.const 4
        i32.lt_u
        br_if 0 (;@2;)
        local.get 4
        i32.const 2
        i32.and
        local.set 11
        local.get 9
        local.get 6
        i32.add
        local.set 10
        local.get 4
        i32.const 2147483644
        i32.and
        local.set 12
        i32.const 0
        local.set 3
        loop  ;; label = @3
          local.get 10
          local.get 3
          i32.add
          local.tee 5
          i32.const 8
          i32.add
          local.get 1
          local.get 3
          i32.add
          local.tee 7
          i32.load8_u
          i32.store8
          local.get 5
          i32.const 9
          i32.add
          local.get 7
          i32.const 1
          i32.add
          i32.load8_u
          i32.store8
          local.get 5
          i32.const 10
          i32.add
          local.get 7
          i32.const 2
          i32.add
          i32.load8_u
          i32.store8
          local.get 5
          i32.const 11
          i32.add
          local.get 7
          i32.const 3
          i32.add
          i32.load8_u
          i32.store8
          local.get 12
          local.get 3
          i32.const 4
          i32.add
          local.tee 3
          i32.ne
          br_if 0 (;@3;)
        end
        local.get 11
        i32.eqz
        br_if 1 (;@1;)
      end
      local.get 1
      local.get 3
      i32.add
      local.set 5
      local.get 9
      local.get 3
      i32.add
      local.get 6
      i32.add
      i32.const 8
      i32.add
      local.set 3
      loop  ;; label = @2
        local.get 3
        local.get 0
        i32.add
        local.get 5
        local.get 0
        i32.add
        i32.load8_u
        i32.store8
        local.get 0
        i32.const 1
        i32.add
        local.tee 0
        i32.const 2
        i32.ne
        br_if 0 (;@2;)
      end
    end
    block  ;; label = @1
      block  ;; label = @2
        local.get 2
        br_if 0 (;@2;)
        i32.const 0
        local.set 2
        br 1 (;@1;)
      end
      local.get 2
      i32.const 4
      i32.add
      i32.load
      local.tee 0
      local.get 2
      i32.const 8
      i32.add
      local.get 0
      select
      local.set 2
    end
    block  ;; label = @1
      local.get 8
      i32.const 1
      i32.lt_s
      br_if 0 (;@1;)
      i32.const 0
      local.set 0
      i32.const 0
      local.set 3
      block  ;; label = @2
        local.get 8
        i32.const 4
        i32.lt_u
        br_if 0 (;@2;)
        local.get 8
        i32.const 2
        i32.and
        local.set 12
        local.get 8
        i32.const 2147483644
        i32.and
        local.set 1
        local.get 9
        local.get 6
        i32.add
        local.get 4
        i32.add
        local.set 10
        i32.const 0
        local.set 3
        loop  ;; label = @3
          local.get 10
          local.get 3
          i32.add
          local.tee 5
          i32.const 8
          i32.add
          local.get 2
          local.get 3
          i32.add
          local.tee 7
          i32.load8_u
          i32.store8
          local.get 5
          i32.const 9
          i32.add
          local.get 7
          i32.const 1
          i32.add
          i32.load8_u
          i32.store8
          local.get 5
          i32.const 10
          i32.add
          local.get 7
          i32.const 2
          i32.add
          i32.load8_u
          i32.store8
          local.get 5
          i32.const 11
          i32.add
          local.get 7
          i32.const 3
          i32.add
          i32.load8_u
          i32.store8
          local.get 1
          local.get 3
          i32.const 4
          i32.add
          local.tee 3
          i32.ne
          br_if 0 (;@3;)
        end
        local.get 12
        i32.eqz
        br_if 1 (;@1;)
      end
      local.get 2
      local.get 3
      i32.add
      local.set 5
      local.get 9
      local.get 3
      i32.add
      local.get 4
      i32.add
      local.get 6
      i32.add
      i32.const 8
      i32.add
      local.set 3
      loop  ;; label = @2
        local.get 3
        local.get 0
        i32.add
        local.get 5
        local.get 0
        i32.add
        i32.load8_u
        i32.store8
        local.get 0
        i32.const 1
        i32.add
        local.tee 0
        i32.const 2
        i32.ne
        br_if 0 (;@2;)
      end
    end
    local.get 9)

(func $concat_str_int_str (param i32 i32 i32) (result i32)
    (local i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32)
    local.get 2
    i32.load
    local.set 3
    local.get 0
    i32.load
    local.set 4
    block  ;; label = @1
      block  ;; label = @2
        local.get 1
        br_if 0 (;@2;)
        i32.const 1
        local.set 5
        br 1 (;@1;)
      end
      block  ;; label = @2
        block  ;; label = @3
          local.get 1
          local.get 1
          i32.const 31
          i32.shr_s
          local.tee 5
          i32.xor
          local.get 5
          i32.sub
          local.tee 5
          i32.const 10
          i32.ge_u
          br_if 0 (;@3;)
          i32.const 1
          local.set 5
          br 1 (;@2;)
        end
        block  ;; label = @3
          local.get 5
          i32.const 100
          i32.ge_u
          br_if 0 (;@3;)
          i32.const 2
          local.set 5
          br 1 (;@2;)
        end
        block  ;; label = @3
          local.get 5
          i32.const 1000
          i32.ge_u
          br_if 0 (;@3;)
          i32.const 3
          local.set 5
          br 1 (;@2;)
        end
        block  ;; label = @3
          local.get 5
          i32.const 10000
          i32.ge_u
          br_if 0 (;@3;)
          i32.const 4
          local.set 5
          br 1 (;@2;)
        end
        block  ;; label = @3
          local.get 5
          i32.const 100000
          i32.ge_u
          br_if 0 (;@3;)
          i32.const 5
          local.set 5
          br 1 (;@2;)
        end
        block  ;; label = @3
          local.get 5
          i32.const 1000000
          i32.ge_u
          br_if 0 (;@3;)
          i32.const 6
          local.set 5
          br 1 (;@2;)
        end
        block  ;; label = @3
          local.get 5
          i32.const 10000000
          i32.ge_u
          br_if 0 (;@3;)
          i32.const 7
          local.set 5
          br 1 (;@2;)
        end
        block  ;; label = @3
          local.get 5
          i32.const 100000000
          i32.ge_u
          br_if 0 (;@3;)
          i32.const 8
          local.set 5
          br 1 (;@2;)
        end
        i32.const 9
        i32.const 10
        local.get 5
        i32.const 1000000000
        i32.lt_u
        select
        local.set 5
      end
      local.get 5
      local.get 1
      i32.const 31
      i32.shr_u
      i32.add
      local.set 5
    end
    block  ;; label = @1
      local.get 5
      local.get 4
      i32.add
      local.tee 6
      local.get 3
      i32.add
      local.tee 5
      br_if 0 (;@1;)
      call $__rt_str_empty_get
      local.tee 4
      call $retain
      local.get 4
      return
    end
    i32.const 8
    local.set 7
    local.get 5
    i32.const 1
    i32.shl
    i32.const 8
    i32.add
    i32.const 5
    call $malloc
    local.tee 8
    local.get 5
    i32.store
    block  ;; label = @1
      local.get 8
      i32.eqz
      br_if 0 (;@1;)
      local.get 8
      i32.const 4
      i32.add
      local.get 8
      i32.const 8
      i32.add
      local.tee 7
      i32.store
    end
    block  ;; label = @1
      block  ;; label = @2
        local.get 4
        br_if 0 (;@2;)
        i32.const 0
        local.set 9
        br 1 (;@1;)
      end
      block  ;; label = @2
        block  ;; label = @3
          local.get 0
          br_if 0 (;@3;)
          i32.const 0
          local.set 10
          br 1 (;@2;)
        end
        local.get 0
        i32.const 4
        i32.add
        i32.load
        local.tee 5
        local.get 0
        i32.const 8
        i32.add
        local.get 5
        select
        local.set 10
      end
      local.get 4
      i32.const 1
      i32.shl
      local.tee 9
      i32.const 1
      i32.lt_s
      br_if 0 (;@1;)
      i32.const 0
      local.set 4
      i32.const 0
      local.set 0
      block  ;; label = @2
        local.get 9
        i32.const 4
        i32.lt_u
        br_if 0 (;@2;)
        local.get 9
        i32.const 2
        i32.and
        local.set 11
        local.get 9
        i32.const 2147483644
        i32.and
        local.set 12
        i32.const 0
        local.set 0
        loop  ;; label = @3
          local.get 8
          local.get 0
          i32.add
          local.tee 5
          i32.const 8
          i32.add
          local.get 10
          local.get 0
          i32.add
          local.tee 13
          i32.load8_u
          i32.store8
          local.get 5
          i32.const 9
          i32.add
          local.get 13
          i32.const 1
          i32.add
          i32.load8_u
          i32.store8
          local.get 5
          i32.const 10
          i32.add
          local.get 13
          i32.const 2
          i32.add
          i32.load8_u
          i32.store8
          local.get 5
          i32.const 11
          i32.add
          local.get 13
          i32.const 3
          i32.add
          i32.load8_u
          i32.store8
          local.get 12
          local.get 0
          i32.const 4
          i32.add
          local.tee 0
          i32.ne
          br_if 0 (;@3;)
        end
        local.get 11
        i32.eqz
        br_if 1 (;@1;)
      end
      local.get 10
      local.get 0
      i32.add
      local.set 5
      local.get 8
      local.get 0
      i32.add
      i32.const 8
      i32.add
      local.set 0
      loop  ;; label = @2
        local.get 0
        local.get 4
        i32.add
        local.get 5
        local.get 4
        i32.add
        i32.load8_u
        i32.store8
        local.get 4
        i32.const 1
        i32.add
        local.tee 4
        i32.const 2
        i32.ne
        br_if 0 (;@2;)
      end
    end
    local.get 7
    local.get 9
    i32.add
    local.set 4
    block  ;; label = @1
      block  ;; label = @2
        local.get 1
        br_if 0 (;@2;)
        local.get 4
        i32.const 48
        i32.store16
        br 1 (;@1;)
      end
      block  ;; label = @2
        local.get 1
        i32.const -1
        i32.gt_s
        br_if 0 (;@2;)
        local.get 4
        i32.const 45
        i32.store16
      end
      local.get 1
      local.get 1
      i32.const 31
      i32.shr_s
      local.tee 4
      i32.xor
      local.get 4
      i32.sub
      local.set 4
      local.get 8
      local.get 6
      i32.const 1
      i32.shl
      i32.add
      i32.const 6
      i32.add
      local.set 0
      loop  ;; label = @2
        local.get 0
        local.get 4
        local.get 4
        i32.const 10
        i32.div_u
        local.tee 5
        i32.const 10
        i32.mul
        i32.sub
        i32.const 48
        i32.or
        i32.store16
        local.get 0
        i32.const -2
        i32.add
        local.set 0
        local.get 4
        i32.const 9
        i32.gt_u
        local.set 13
        local.get 5
        local.set 4
        local.get 13
        br_if 0 (;@2;)
      end
    end
    block  ;; label = @1
      local.get 3
      i32.eqz
      br_if 0 (;@1;)
      block  ;; label = @2
        block  ;; label = @3
          local.get 2
          br_if 0 (;@3;)
          i32.const 0
          local.set 1
          br 1 (;@2;)
        end
        local.get 2
        i32.const 4
        i32.add
        i32.load
        local.tee 4
        local.get 2
        i32.const 8
        i32.add
        local.get 4
        select
        local.set 1
      end
      local.get 3
      i32.const 1
      i32.shl
      local.tee 5
      i32.const 1
      i32.lt_s
      br_if 0 (;@1;)
      local.get 6
      i32.const 1
      i32.shl
      local.set 3
      i32.const 0
      local.set 4
      i32.const 0
      local.set 0
      block  ;; label = @2
        local.get 5
        i32.const 4
        i32.lt_u
        br_if 0 (;@2;)
        local.get 5
        i32.const 2
        i32.and
        local.set 2
        local.get 8
        local.get 3
        i32.add
        local.set 10
        local.get 5
        i32.const 2147483644
        i32.and
        local.set 12
        i32.const 0
        local.set 0
        loop  ;; label = @3
          local.get 10
          local.get 0
          i32.add
          local.tee 5
          i32.const 8
          i32.add
          local.get 1
          local.get 0
          i32.add
          local.tee 13
          i32.load8_u
          i32.store8
          local.get 5
          i32.const 9
          i32.add
          local.get 13
          i32.const 1
          i32.add
          i32.load8_u
          i32.store8
          local.get 5
          i32.const 10
          i32.add
          local.get 13
          i32.const 2
          i32.add
          i32.load8_u
          i32.store8
          local.get 5
          i32.const 11
          i32.add
          local.get 13
          i32.const 3
          i32.add
          i32.load8_u
          i32.store8
          local.get 12
          local.get 0
          i32.const 4
          i32.add
          local.tee 0
          i32.ne
          br_if 0 (;@3;)
        end
        local.get 2
        i32.eqz
        br_if 1 (;@1;)
      end
      local.get 1
      local.get 0
      i32.add
      local.set 5
      local.get 8
      local.get 0
      i32.add
      local.get 3
      i32.add
      i32.const 8
      i32.add
      local.set 0
      loop  ;; label = @2
        local.get 0
        local.get 4
        i32.add
        local.get 5
        local.get 4
        i32.add
        i32.load8_u
        i32.store8
        local.get 4
        i32.const 1
        i32.add
        local.tee 4
        i32.const 2
        i32.ne
        br_if 0 (;@2;)
      end
    end
    local.get 8)

(func $debug_get_free_list_head (result i32)
    call $free_list_head_get)

(func $debug_get_heap_ptr (result i32)
    i32.const 0
    i32.atomic.load offset=48)

(func $debug_get_live_objects (result i32)
    call $live_objects_get)

(func $debug_get_total_allocations (result i32)
    call $total_allocations_get)

(func $debug_get_ref_count (param i32) (result i32)
    block  ;; label = @1
      local.get 0
      br_if 0 (;@1;)
      i32.const 0
      return
    end
    local.get 0
    i32.const -4
    i32.add
    i32.load)

(func $string_eq (param i32 i32) (result i32)
    (local i32 i32 i32 i32 i32)
    i32.const 1
    local.set 2
    block  ;; label = @1
      local.get 0
      local.get 1
      i32.eq
      br_if 0 (;@1;)
      block  ;; label = @2
        local.get 0
        i32.eqz
        br_if 0 (;@2;)
        local.get 1
        i32.eqz
        br_if 0 (;@2;)
        local.get 0
        i32.load
        local.tee 3
        local.get 1
        i32.load
        i32.ne
        br_if 0 (;@2;)
        i32.const 1
        local.set 2
        block  ;; label = @3
          local.get 3
          i32.const 1
          i32.shl
          local.tee 4
          i32.const 2
          i32.shr_u
          local.tee 5
          i32.eqz
          br_if 0 (;@3;)
          local.get 1
          i32.const 4
          i32.add
          i32.load
          local.tee 3
          local.get 1
          i32.const 8
          i32.add
          local.get 3
          select
          local.set 3
          local.get 0
          i32.const 4
          i32.add
          i32.load
          local.tee 6
          local.get 0
          i32.const 8
          i32.add
          local.get 6
          select
          local.set 6
          loop  ;; label = @4
            local.get 6
            i32.load
            local.get 3
            i32.load
            i32.ne
            br_if 2 (;@2;)
            local.get 6
            i32.const 4
            i32.add
            local.set 6
            local.get 3
            i32.const 4
            i32.add
            local.set 3
            local.get 5
            i32.const -1
            i32.add
            local.tee 5
            br_if 0 (;@4;)
          end
        end
        local.get 4
        i32.const -4
        i32.and
        local.tee 3
        local.get 4
        i32.eq
        br_if 1 (;@1;)
        local.get 1
        i32.const 4
        i32.add
        i32.load
        local.tee 6
        local.get 1
        i32.const 8
        i32.add
        local.get 6
        select
        local.set 6
        local.get 0
        i32.const 4
        i32.add
        i32.load
        local.tee 2
        local.get 0
        i32.const 8
        i32.add
        local.get 2
        select
        local.set 0
        loop  ;; label = @3
          local.get 0
          local.get 3
          i32.add
          i32.load8_u
          local.get 6
          local.get 3
          i32.add
          i32.load8_u
          i32.ne
          br_if 1 (;@2;)
          i32.const 1
          local.set 2
          local.get 3
          i32.const 1
          i32.add
          local.tee 3
          local.get 4
          i32.ge_u
          br_if 2 (;@1;)
          br 0 (;@3;)
        end
      end
      i32.const 0
      local.set 2
    end
    local.get 2)

(func $string_compare (param i32 i32) (result i32)
    (local i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32)
    block  ;; label = @1
      local.get 0
      local.get 1
      i32.ne
      br_if 0 (;@1;)
      i32.const 0
      return
    end
    i32.const 0
    local.set 2
    i32.const 0
    local.set 3
    block  ;; label = @1
      local.get 0
      i32.eqz
      br_if 0 (;@1;)
      local.get 0
      i32.load
      i32.const 1
      i32.shl
      local.set 3
    end
    block  ;; label = @1
      local.get 1
      i32.eqz
      br_if 0 (;@1;)
      local.get 1
      i32.load
      i32.const 1
      i32.shl
      local.set 2
    end
    block  ;; label = @1
      block  ;; label = @2
        block  ;; label = @3
          local.get 3
          local.get 2
          local.get 3
          local.get 2
          i32.lt_u
          local.tee 4
          select
          local.tee 5
          i32.const 2
          i32.shr_u
          local.tee 6
          i32.eqz
          br_if 0 (;@3;)
          local.get 1
          i32.const 8
          i32.add
          local.set 7
          block  ;; label = @4
            local.get 0
            br_if 0 (;@4;)
            local.get 1
            i32.eqz
            br_if 2 (;@2;)
            local.get 1
            i32.const 4
            i32.add
            i32.load
            local.tee 8
            local.get 7
            local.get 8
            select
            local.set 8
            i32.const -1
            local.set 7
            loop  ;; label = @5
              local.get 8
              i32.load
              br_if 4 (;@1;)
              local.get 8
              i32.const 4
              i32.add
              local.set 8
              local.get 6
              i32.const -1
              i32.add
              local.tee 6
              br_if 0 (;@5;)
              br 2 (;@3;)
            end
          end
          local.get 0
          i32.const 4
          i32.add
          i32.load
          local.tee 8
          local.get 0
          i32.const 8
          i32.add
          local.get 8
          select
          local.set 8
          block  ;; label = @4
            local.get 1
            br_if 0 (;@4;)
            loop  ;; label = @5
              block  ;; label = @6
                local.get 8
                i32.load
                i32.eqz
                br_if 0 (;@6;)
                i32.const 1
                return
              end
              local.get 8
              i32.const 4
              i32.add
              local.set 8
              local.get 6
              i32.const -1
              i32.add
              local.tee 6
              br_if 0 (;@5;)
              br 2 (;@3;)
            end
          end
          local.get 1
          i32.const 4
          i32.add
          i32.load
          local.tee 9
          local.get 7
          local.get 9
          select
          local.set 7
          loop  ;; label = @4
            block  ;; label = @5
              local.get 8
              i32.load
              local.tee 9
              local.get 7
              i32.load
              local.tee 10
              i32.eq
              br_if 0 (;@5;)
              block  ;; label = @6
                local.get 9
                i32.const 255
                i32.and
                local.tee 11
                local.get 10
                i32.const 255
                i32.and
                local.tee 12
                i32.ne
                br_if 0 (;@6;)
                local.get 9
                i32.const 8
                i32.shr_u
                i32.const 255
                i32.and
                local.tee 11
                local.get 10
                i32.const 8
                i32.shr_u
                i32.const 255
                i32.and
                local.tee 12
                i32.ne
                br_if 0 (;@6;)
                local.get 9
                i32.const 16
                i32.shr_u
                i32.const 255
                i32.and
                local.tee 11
                local.get 10
                i32.const 16
                i32.shr_u
                i32.const 255
                i32.and
                local.tee 12
                i32.ne
                br_if 0 (;@6;)
                local.get 9
                i32.const 24
                i32.shr_u
                local.tee 11
                local.get 10
                i32.const 24
                i32.shr_u
                local.tee 12
                i32.eq
                br_if 1 (;@5;)
              end
              i32.const -1
              i32.const 1
              local.get 11
              local.get 12
              i32.lt_u
              select
              return
            end
            local.get 8
            i32.const 4
            i32.add
            local.set 8
            local.get 7
            i32.const 4
            i32.add
            local.set 7
            local.get 6
            i32.const -1
            i32.add
            local.tee 6
            br_if 0 (;@4;)
          end
        end
        local.get 5
        i32.const -4
        i32.and
        local.tee 6
        local.get 5
        i32.eq
        br_if 0 (;@2;)
        local.get 1
        i32.const 8
        i32.add
        local.set 7
        block  ;; label = @3
          local.get 0
          br_if 0 (;@3;)
          local.get 1
          i32.eqz
          br_if 1 (;@2;)
          local.get 1
          i32.const 4
          i32.add
          i32.load
          local.tee 8
          local.get 7
          local.get 8
          select
          local.set 8
          loop  ;; label = @4
            block  ;; label = @5
              local.get 8
              local.get 6
              i32.add
              i32.load8_u
              i32.eqz
              br_if 0 (;@5;)
              i32.const -1
              return
            end
            local.get 6
            i32.const 1
            i32.add
            local.tee 6
            local.get 5
            i32.lt_u
            br_if 0 (;@4;)
            br 2 (;@2;)
          end
        end
        local.get 0
        i32.const 4
        i32.add
        i32.load
        local.tee 8
        local.get 0
        i32.const 8
        i32.add
        local.get 8
        select
        local.set 8
        block  ;; label = @3
          local.get 1
          br_if 0 (;@3;)
          i32.const 1
          local.set 7
          loop  ;; label = @4
            local.get 8
            local.get 6
            i32.add
            i32.load8_u
            br_if 3 (;@1;)
            local.get 6
            i32.const 1
            i32.add
            local.tee 6
            local.get 5
            i32.lt_u
            br_if 0 (;@4;)
            br 2 (;@2;)
          end
        end
        local.get 1
        i32.const 4
        i32.add
        i32.load
        local.tee 1
        local.get 7
        local.get 1
        select
        local.set 7
        block  ;; label = @3
          loop  ;; label = @4
            local.get 8
            local.get 6
            i32.add
            i32.load8_u
            local.tee 1
            local.get 7
            local.get 6
            i32.add
            i32.load8_u
            local.tee 9
            i32.ne
            br_if 1 (;@3;)
            local.get 6
            i32.const 1
            i32.add
            local.tee 6
            local.get 5
            i32.ge_u
            br_if 2 (;@2;)
            br 0 (;@4;)
          end
        end
        i32.const -1
        i32.const 1
        local.get 1
        local.get 9
        i32.lt_u
        select
        return
      end
      block  ;; label = @2
        local.get 4
        i32.eqz
        br_if 0 (;@2;)
        i32.const -1
        return
      end
      local.get 3
      local.get 2
      i32.gt_u
      local.set 7
    end
    local.get 7)

(func $string_substring_raw (param i32 i32 i32) (result i32)
    (local i32)
    block  ;; label = @1
      local.get 0
      i32.eqz
      br_if 0 (;@1;)
      local.get 2
      i32.const 0
      local.get 2
      i32.const 0
      i32.gt_s
      select
      local.tee 2
      local.get 0
      i32.load
      local.tee 3
      local.get 2
      local.get 3
      i32.lt_u
      select
      local.tee 3
      local.get 1
      i32.const 0
      local.get 1
      i32.const 0
      i32.gt_s
      select
      local.tee 2
      i32.le_u
      br_if 0 (;@1;)
      i32.const 12
      i32.const 5
      call $malloc
      local.tee 1
      local.get 3
      local.get 2
      i32.sub
      i32.store
      local.get 0
      i32.const 4
      i32.add
      i32.load
      local.set 3
      local.get 1
      i32.const 8
      i32.add
      local.get 0
      i32.store
      local.get 1
      i32.const 4
      i32.add
      local.get 3
      local.get 0
      i32.const 8
      i32.add
      local.get 3
      select
      local.get 2
      i32.const 1
      i32.shl
      i32.add
      i32.store
      local.get 0
      call $retain
      local.get 1
      return
    end
    call $__rt_str_empty_get
    local.tee 0
    call $retain
    local.get 0)

(func $string_clone (param i32) (result i32)
    (local i32 i32 i32 i32 i32 i32 i32)
    block  ;; label = @1
      local.get 0
      i32.eqz
      br_if 0 (;@1;)
      local.get 0
      i32.load
      local.tee 1
      i32.const 1
      i32.lt_s
      br_if 0 (;@1;)
      local.get 1
      i32.const 1
      i32.shl
      local.tee 2
      i32.const 8
      i32.add
      i32.const 5
      call $malloc
      local.tee 3
      local.get 1
      i32.store
      block  ;; label = @2
        local.get 3
        i32.eqz
        br_if 0 (;@2;)
        local.get 3
        i32.const 4
        i32.add
        local.get 3
        i32.const 8
        i32.add
        i32.store
      end
      block  ;; label = @2
        local.get 2
        i32.const 1
        i32.lt_s
        br_if 0 (;@2;)
        local.get 0
        i32.const 4
        i32.add
        i32.load
        local.tee 4
        local.get 0
        i32.const 8
        i32.add
        local.get 4
        select
        local.set 5
        i32.const 0
        local.set 0
        i32.const 0
        local.set 4
        block  ;; label = @3
          local.get 1
          i32.const 1
          i32.eq
          br_if 0 (;@3;)
          local.get 2
          i32.const 2
          i32.and
          local.set 6
          local.get 2
          i32.const 2147483644
          i32.and
          local.set 7
          i32.const 0
          local.set 4
          loop  ;; label = @4
            local.get 3
            local.get 4
            i32.add
            local.tee 1
            i32.const 8
            i32.add
            local.get 5
            local.get 4
            i32.add
            local.tee 2
            i32.load8_u
            i32.store8
            local.get 1
            i32.const 9
            i32.add
            local.get 2
            i32.const 1
            i32.add
            i32.load8_u
            i32.store8
            local.get 1
            i32.const 10
            i32.add
            local.get 2
            i32.const 2
            i32.add
            i32.load8_u
            i32.store8
            local.get 1
            i32.const 11
            i32.add
            local.get 2
            i32.const 3
            i32.add
            i32.load8_u
            i32.store8
            local.get 7
            local.get 4
            i32.const 4
            i32.add
            local.tee 4
            i32.ne
            br_if 0 (;@4;)
          end
          local.get 6
          i32.eqz
          br_if 1 (;@2;)
        end
        local.get 5
        local.get 4
        i32.add
        local.set 1
        local.get 3
        local.get 4
        i32.add
        i32.const 8
        i32.add
        local.set 4
        loop  ;; label = @3
          local.get 4
          local.get 0
          i32.add
          local.get 1
          local.get 0
          i32.add
          i32.load8_u
          i32.store8
          local.get 0
          i32.const 1
          i32.add
          local.tee 0
          i32.const 2
          i32.ne
          br_if 0 (;@3;)
        end
      end
      local.get 3
      return
    end
    call $__rt_str_empty_get
    local.tee 0
    call $retain
    local.get 0)

(func $string_copy_utf8 (param i32 i32 i32 i32 i32)
    (local i32 i32 i32 i32 i32 i32)
    block  ;; label = @1
      local.get 2
      i32.eqz
      br_if 0 (;@1;)
      local.get 0
      i32.eqz
      br_if 0 (;@1;)
      local.get 4
      i32.eqz
      br_if 0 (;@1;)
      local.get 4
      i32.const 1
      i32.lt_s
      br_if 0 (;@1;)
      local.get 2
      i32.const 4
      i32.add
      i32.load
      local.tee 5
      local.get 2
      i32.const 8
      i32.add
      local.get 5
      select
      local.set 6
      local.get 4
      i32.const 3
      i32.and
      local.set 7
      i32.const 0
      local.set 2
      block  ;; label = @2
        local.get 4
        i32.const 4
        i32.lt_u
        br_if 0 (;@2;)
        local.get 6
        local.get 3
        i32.add
        local.set 8
        local.get 1
        local.get 0
        i32.add
        local.set 9
        local.get 4
        i32.const 2147483644
        i32.and
        local.set 10
        i32.const 0
        local.set 2
        loop  ;; label = @3
          local.get 9
          local.get 2
          i32.add
          local.tee 4
          i32.const 4
          i32.add
          local.get 8
          local.get 2
          i32.add
          local.tee 5
          i32.load8_u
          i32.store8
          local.get 4
          i32.const 5
          i32.add
          local.get 5
          i32.const 1
          i32.add
          i32.load8_u
          i32.store8
          local.get 4
          i32.const 6
          i32.add
          local.get 5
          i32.const 2
          i32.add
          i32.load8_u
          i32.store8
          local.get 4
          i32.const 7
          i32.add
          local.get 5
          i32.const 3
          i32.add
          i32.load8_u
          i32.store8
          local.get 10
          local.get 2
          i32.const 4
          i32.add
          local.tee 2
          i32.ne
          br_if 0 (;@3;)
        end
        local.get 7
        i32.eqz
        br_if 1 (;@1;)
      end
      local.get 6
      local.get 2
      i32.add
      local.get 3
      i32.add
      local.set 4
      local.get 2
      local.get 1
      i32.add
      local.get 0
      i32.add
      i32.const 4
      i32.add
      local.set 2
      loop  ;; label = @2
        local.get 2
        local.get 4
        i32.load8_u
        i32.store8
        local.get 2
        i32.const 1
        i32.add
        local.set 2
        local.get 4
        i32.const 1
        i32.add
        local.set 4
        local.get 7
        i32.const -1
        i32.add
        local.tee 7
        br_if 0 (;@2;)
      end
    end)

(func $char_at (param i32 i32) (result i32)
    (local i32)
    block  ;; label = @1
      block  ;; label = @2
        local.get 0
        br_if 0 (;@2;)
        i32.const 0
        local.set 0
        br 1 (;@1;)
      end
      local.get 0
      i32.const 4
      i32.add
      i32.load
      local.tee 2
      local.get 0
      i32.const 8
      i32.add
      local.get 2
      select
      local.set 0
    end
    local.get 0
    local.get 1
    i32.const 1
    i32.shl
    i32.add
    i32.load16_u)

(func $byte_at (param i32 i32) (result i32)
    (local i32)
    block  ;; label = @1
      block  ;; label = @2
        local.get 0
        br_if 0 (;@2;)
        i32.const 0
        local.set 0
        br 1 (;@1;)
      end
      local.get 0
      i32.const 4
      i32.add
      i32.load
      local.tee 2
      local.get 0
      i32.const 8
      i32.add
      local.get 2
      select
      local.set 0
    end
    local.get 0
    local.get 1
    i32.add
    i32.load8_u)

(func $string_alloc (param i32) (result i32)
    local.get 0
    i32.const 1
    i32.shl
    i32.const 8
    i32.add
    i32.const 5
    call $malloc
    local.tee 0
    i32.const 0
    i32.store
    block  ;; label = @1
      local.get 0
      i32.eqz
      br_if 0 (;@1;)
      local.get 0
      i32.const 4
      i32.add
      local.get 0
      i32.const 8
      i32.add
      i32.store
    end
    local.get 0)

(func $utf8_bytes_to_string (param i32 i32) (result i32)
    (local i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32)
    block  ;; label = @1
      local.get 1
      br_if 0 (;@1;)
      call $__rt_str_empty_get
      local.tee 2
      call $retain
      local.get 2
      return
    end
    local.get 1
    i32.const 1
    i32.shl
    i32.const 8
    i32.add
    i32.const 5
    call $malloc
    local.tee 3
    i32.const 10
    i32.add
    local.set 4
    local.get 3
    i32.const 8
    i32.add
    local.set 5
    i32.const 0
    local.set 6
    i32.const 0
    local.set 7
    loop  ;; label = @1
      local.get 6
      local.get 0
      i32.add
      local.tee 8
      i32.load8_s
      local.tee 9
      i32.const 255
      i32.and
      local.set 2
      block  ;; label = @2
        block  ;; label = @3
          block  ;; label = @4
            local.get 9
            i32.const -1
            i32.gt_s
            br_if 0 (;@4;)
            block  ;; label = @5
              local.get 2
              i32.const 224
              i32.and
              i32.const 192
              i32.ne
              br_if 0 (;@5;)
              local.get 2
              i32.const 6
              i32.shl
              i32.const 1984
              i32.and
              local.get 8
              i32.const 1
              i32.add
              i32.load8_u
              i32.const 63
              i32.and
              i32.or
              local.set 2
              br 1 (;@4;)
            end
            local.get 8
            i32.const 2
            i32.add
            i32.load8_u
            local.set 9
            local.get 8
            i32.const 1
            i32.add
            i32.load8_u
            local.set 10
            local.get 2
            i32.const 240
            i32.and
            i32.const 224
            i32.ne
            br_if 1 (;@3;)
            local.get 10
            i32.const 63
            i32.and
            i32.const 6
            i32.shl
            local.get 2
            i32.const 12
            i32.shl
            i32.const 61440
            i32.and
            i32.or
            local.get 9
            i32.const 63
            i32.and
            i32.or
            local.set 2
          end
          local.get 7
          i32.const 1
          i32.shl
          local.get 5
          i32.add
          local.set 9
          i32.const 1
          local.set 10
          br 1 (;@2;)
        end
        local.get 9
        i32.const 63
        i32.and
        i32.const 6
        i32.shl
        local.get 8
        i32.const 3
        i32.add
        i32.load8_u
        i32.const 63
        i32.and
        i32.or
        local.tee 11
        local.get 10
        i32.const 63
        i32.and
        i32.const 12
        i32.shl
        local.get 2
        i32.const 18
        i32.shl
        i32.const 1835008
        i32.and
        i32.or
        local.tee 10
        i32.or
        local.set 2
        local.get 7
        i32.const 1
        i32.shl
        local.tee 12
        local.get 5
        i32.add
        local.set 9
        block  ;; label = @3
          local.get 10
          i32.const 65535
          i32.gt_u
          br_if 0 (;@3;)
          i32.const 1
          local.set 10
          br 1 (;@2;)
        end
        local.get 9
        local.get 2
        i32.const 67043328
        i32.add
        i32.const 10
        i32.shr_u
        i32.const -10240
        i32.add
        i32.store16
        local.get 11
        i32.const -9216
        i32.or
        local.set 2
        local.get 4
        local.get 12
        i32.add
        local.set 9
        i32.const 2
        local.set 10
      end
      local.get 9
      local.get 2
      i32.store16
      block  ;; label = @2
        block  ;; label = @3
          local.get 8
          i32.load8_s
          local.tee 2
          i32.const -1
          i32.le_s
          br_if 0 (;@3;)
          i32.const 1
          local.set 2
          br 1 (;@2;)
        end
        block  ;; label = @3
          local.get 2
          i32.const 255
          i32.and
          local.tee 2
          i32.const 224
          i32.and
          i32.const 192
          i32.ne
          br_if 0 (;@3;)
          i32.const 2
          local.set 2
          br 1 (;@2;)
        end
        i32.const 3
        i32.const 4
        local.get 2
        i32.const 240
        i32.and
        i32.const 224
        i32.eq
        select
        local.set 2
      end
      local.get 10
      local.get 7
      i32.add
      local.set 7
      local.get 2
      local.get 6
      i32.add
      local.tee 6
      local.get 1
      i32.lt_u
      br_if 0 (;@1;)
    end
    local.get 3
    local.get 7
    i32.store
    block  ;; label = @1
      local.get 3
      br_if 0 (;@1;)
      i32.const 0
      return
    end
    local.get 3
    i32.const 4
    i32.add
    local.get 5
    i32.store
    local.get 3)

(func $string_from_utf8 (param i32) (result i32)
    block  ;; label = @1
      local.get 0
      br_if 0 (;@1;)
      call $__rt_str_empty_get
      local.tee 0
      call $retain
      local.get 0
      return
    end
    local.get 0
    i32.const 4
    i32.add
    local.get 0
    i32.load
    call $utf8_bytes_to_string)

(func $string_set (param i32 i32 i32)
    (local i32 i32 i32)
    local.get 0
    i32.load
    local.set 3
    block  ;; label = @1
      block  ;; label = @2
        block  ;; label = @3
          block  ;; label = @4
            local.get 2
            i32.const 65536
            i32.ge_u
            br_if 0 (;@4;)
            local.get 2
            local.set 4
            br 1 (;@3;)
          end
          i32.const 65533
          local.set 4
          local.get 1
          local.get 3
          i32.ne
          br_if 0 (;@3;)
          block  ;; label = @4
            block  ;; label = @5
              local.get 0
              br_if 0 (;@5;)
              i32.const 0
              local.set 3
              br 1 (;@4;)
            end
            local.get 0
            i32.const 4
            i32.add
            i32.load
            local.tee 3
            local.get 0
            i32.const 8
            i32.add
            local.get 3
            select
            local.set 3
          end
          i32.const 2
          local.set 5
          local.get 3
          local.get 1
          i32.const 1
          i32.shl
          i32.add
          local.tee 3
          i32.const 2
          i32.add
          local.get 2
          i32.const 1023
          i32.and
          i32.const 56320
          i32.or
          i32.store16
          local.get 3
          local.get 2
          i32.const 67043328
          i32.add
          i32.const 10
          i32.shr_u
          i32.const -10240
          i32.add
          i32.store16
          br 1 (;@2;)
        end
        block  ;; label = @3
          block  ;; label = @4
            local.get 0
            br_if 0 (;@4;)
            i32.const 0
            local.set 2
            br 1 (;@3;)
          end
          local.get 0
          i32.const 4
          i32.add
          i32.load
          local.tee 2
          local.get 0
          i32.const 8
          i32.add
          local.get 2
          select
          local.set 2
        end
        i32.const 1
        local.set 5
        local.get 2
        local.get 1
        i32.const 1
        i32.shl
        i32.add
        local.get 4
        i32.store16
        local.get 1
        local.get 3
        i32.ne
        br_if 1 (;@1;)
      end
      local.get 0
      local.get 1
      local.get 5
      i32.add
      i32.store
    end)

(func $string_from_utf8_prefix (param i32 i32) (result i32)
    block  ;; label = @1
      local.get 0
      br_if 0 (;@1;)
      call $__rt_str_empty_get
      local.tee 0
      call $retain
      local.get 0
      return
    end
    local.get 0
    i32.const 4
    i32.add
    local.get 1
    i32.const 0
    local.get 1
    i32.const 0
    i32.gt_s
    select
    local.tee 1
    local.get 0
    i32.load
    local.tee 0
    local.get 1
    local.get 0
    i32.lt_s
    select
    call $utf8_bytes_to_string)

(func $string_from_utf8_prefix_n (param i32 i32 i32) (result i32)
    (local i32 i32 i32 i32)
    block  ;; label = @1
      local.get 0
      i32.eqz
      br_if 0 (;@1;)
      local.get 1
      i32.const 0
      local.get 1
      i32.const 0
      i32.gt_s
      select
      local.tee 1
      local.get 0
      i32.load
      local.tee 3
      local.get 1
      local.get 3
      i32.lt_s
      select
      local.tee 3
      i32.eqz
      br_if 0 (;@1;)
      local.get 3
      i32.const 8
      i32.add
      i32.const 5
      call $malloc
      local.tee 4
      local.get 3
      i32.const 1
      i32.shr_u
      local.get 2
      local.get 2
      i32.const 0
      i32.lt_s
      select
      i32.store
      block  ;; label = @2
        local.get 4
        i32.eqz
        br_if 0 (;@2;)
        local.get 4
        i32.const 4
        i32.add
        local.get 4
        i32.const 8
        i32.add
        i32.store
      end
      block  ;; label = @2
        local.get 3
        i32.const 1
        i32.lt_s
        br_if 0 (;@2;)
        local.get 3
        i32.const 3
        i32.and
        local.set 5
        i32.const 0
        local.set 1
        block  ;; label = @3
          local.get 3
          i32.const 4
          i32.lt_u
          br_if 0 (;@3;)
          local.get 3
          i32.const 2147483644
          i32.and
          local.set 6
          i32.const 0
          local.set 1
          loop  ;; label = @4
            local.get 4
            local.get 1
            i32.add
            local.tee 3
            i32.const 8
            i32.add
            local.get 0
            local.get 1
            i32.add
            local.tee 2
            i32.const 4
            i32.add
            i32.load8_u
            i32.store8
            local.get 3
            i32.const 9
            i32.add
            local.get 2
            i32.const 5
            i32.add
            i32.load8_u
            i32.store8
            local.get 3
            i32.const 10
            i32.add
            local.get 2
            i32.const 6
            i32.add
            i32.load8_u
            i32.store8
            local.get 3
            i32.const 11
            i32.add
            local.get 2
            i32.const 7
            i32.add
            i32.load8_u
            i32.store8
            local.get 6
            local.get 1
            i32.const 4
            i32.add
            local.tee 1
            i32.ne
            br_if 0 (;@4;)
          end
          local.get 5
          i32.eqz
          br_if 1 (;@2;)
        end
        local.get 1
        i32.const 4
        i32.add
        local.set 1
        loop  ;; label = @3
          local.get 4
          local.get 1
          i32.add
          i32.const 4
          i32.add
          local.get 0
          local.get 1
          i32.add
          i32.load8_u
          i32.store8
          local.get 1
          i32.const 1
          i32.add
          local.set 1
          local.get 5
          i32.const -1
          i32.add
          local.tee 5
          br_if 0 (;@3;)
        end
      end
      local.get 4
      return
    end
    call $__rt_str_empty_get
    local.tee 1
    call $retain
    local.get 1)

(func $array_store16 (param i32 i32 i32)
    block  ;; label = @1
      local.get 0
      i32.eqz
      br_if 0 (;@1;)
      local.get 0
      local.get 1
      i32.add
      i32.const 4
      i32.add
      local.get 2
      i32.store16
    end)

(func $string_builder_append (param i32 i32 i32) (result i32)
    (local i32 i32 i32 i32 i32 i32 i32 i32)
    block  ;; label = @1
      local.get 0
      i32.eqz
      br_if 0 (;@1;)
      local.get 2
      i32.eqz
      br_if 0 (;@1;)
      local.get 2
      i32.load
      i32.const 1
      i32.shl
      local.tee 3
      i32.const 1
      i32.lt_s
      br_if 0 (;@1;)
      local.get 2
      i32.const 4
      i32.add
      i32.load
      local.tee 4
      local.get 2
      i32.const 8
      i32.add
      local.get 4
      select
      local.set 5
      i32.const 0
      local.set 2
      i32.const 0
      local.set 4
      block  ;; label = @2
        block  ;; label = @3
          local.get 3
          i32.const 4
          i32.lt_u
          br_if 0 (;@3;)
          local.get 3
          i32.const 2
          i32.and
          local.set 6
          local.get 1
          local.get 0
          i32.add
          local.set 7
          local.get 3
          i32.const 2147483644
          i32.and
          local.set 8
          i32.const 0
          local.set 4
          loop  ;; label = @4
            local.get 7
            local.get 4
            i32.add
            local.tee 9
            i32.const 8
            i32.add
            local.get 5
            local.get 4
            i32.add
            local.tee 10
            i32.load8_u
            i32.store8
            local.get 9
            i32.const 9
            i32.add
            local.get 10
            i32.const 1
            i32.add
            i32.load8_u
            i32.store8
            local.get 9
            i32.const 10
            i32.add
            local.get 10
            i32.const 2
            i32.add
            i32.load8_u
            i32.store8
            local.get 9
            i32.const 11
            i32.add
            local.get 10
            i32.const 3
            i32.add
            i32.load8_u
            i32.store8
            local.get 8
            local.get 4
            i32.const 4
            i32.add
            local.tee 4
            i32.ne
            br_if 0 (;@4;)
          end
          local.get 6
          i32.eqz
          br_if 1 (;@2;)
        end
        local.get 5
        local.get 4
        i32.add
        local.set 9
        local.get 4
        local.get 1
        i32.add
        local.get 0
        i32.add
        i32.const 8
        i32.add
        local.set 4
        loop  ;; label = @3
          local.get 4
          local.get 2
          i32.add
          local.get 9
          local.get 2
          i32.add
          i32.load8_u
          i32.store8
          local.get 2
          i32.const 1
          i32.add
          local.tee 2
          i32.const 2
          i32.ne
          br_if 0 (;@3;)
        end
      end
      local.get 3
      local.get 1
      i32.add
      local.set 1
    end
    local.get 1)

(func $string_from_builder (param i32 i32 i32) (result i32)
    (local i32 i32 i32 i32)
    block  ;; label = @1
      block  ;; label = @2
        local.get 0
        i32.eqz
        br_if 0 (;@2;)
        local.get 1
        i32.const 0
        i32.gt_s
        br_if 1 (;@1;)
      end
      call $__rt_str_empty_get
      local.tee 2
      call $retain
      local.get 2
      return
    end
    local.get 1
    i32.const 1
    i32.shr_u
    local.get 2
    local.get 2
    i32.const 0
    i32.lt_s
    select
    local.set 2
    block  ;; label = @1
      local.get 0
      i32.const -4
      i32.add
      i32.load
      i32.const 1
      i32.ne
      br_if 0 (;@1;)
      local.get 0
      local.get 2
      i32.store
      local.get 0
      i32.const 4
      i32.add
      local.get 0
      i32.const 8
      i32.add
      i32.store
      local.get 0
      i32.const -8
      i32.add
      i32.const 5
      i32.store
      local.get 0
      return
    end
    local.get 1
    i32.const 8
    i32.add
    i32.const 5
    call $malloc
    local.tee 3
    local.get 2
    i32.store
    block  ;; label = @1
      local.get 3
      i32.eqz
      br_if 0 (;@1;)
      local.get 3
      i32.const 4
      i32.add
      local.get 3
      i32.const 8
      i32.add
      i32.store
    end
    local.get 1
    i32.const 3
    i32.and
    local.set 4
    i32.const 0
    local.set 2
    block  ;; label = @1
      block  ;; label = @2
        local.get 1
        i32.const -1
        i32.add
        i32.const 3
        i32.lt_u
        br_if 0 (;@2;)
        local.get 1
        i32.const 2147483644
        i32.and
        local.set 5
        i32.const 0
        local.set 2
        loop  ;; label = @3
          local.get 3
          local.get 2
          i32.add
          local.tee 1
          i32.const 8
          i32.add
          local.get 0
          local.get 2
          i32.add
          local.tee 6
          i32.const 8
          i32.add
          i32.load8_u
          i32.store8
          local.get 1
          i32.const 9
          i32.add
          local.get 6
          i32.const 9
          i32.add
          i32.load8_u
          i32.store8
          local.get 1
          i32.const 10
          i32.add
          local.get 6
          i32.const 10
          i32.add
          i32.load8_u
          i32.store8
          local.get 1
          i32.const 11
          i32.add
          local.get 6
          i32.const 11
          i32.add
          i32.load8_u
          i32.store8
          local.get 5
          local.get 2
          i32.const 4
          i32.add
          local.tee 2
          i32.ne
          br_if 0 (;@3;)
        end
        local.get 4
        i32.eqz
        br_if 1 (;@1;)
      end
      local.get 2
      i32.const 8
      i32.add
      local.set 2
      loop  ;; label = @2
        local.get 3
        local.get 2
        i32.add
        local.get 0
        local.get 2
        i32.add
        i32.load8_u
        i32.store8
        local.get 2
        i32.const 1
        i32.add
        local.set 2
        local.get 4
        i32.const -1
        i32.add
        local.tee 4
        br_if 0 (;@2;)
      end
    end
    local.get 3)
