use super::StdPackage;

pub(super) const PACKAGE: StdPackage = StdPackage {
    name: "system.core",
    deps: &[],
    files: &[
        (
            "<std>/system/core/buffer.dream",
            include_str!("../system/core/buffer.dream"),
        ),
        (
            "<std>/system/core/bytes.dream",
            include_str!("../system/core/bytes.dream"),
        ),
        (
            "<std>/system/core/span.dream",
            include_str!("../system/core/span.dream"),
        ),
        (
            "<std>/system/core/pointer.dream",
            include_str!("../system/core/pointer.dream"),
        ),
        (
            "<std>/system/core/scratch_arena.dream",
            include_str!("../system/core/scratch_arena.dream"),
        ),
        (
            "<std>/system/core/closure.dream",
            include_str!("../system/core/closure.dream"),
        ),
        (
            "<std>/system/core/cell.dream",
            include_str!("../system/core/cell.dream"),
        ),
        (
            "<std>/system/core/ref_box.dream",
            include_str!("../system/core/ref_box.dream"),
        ),
        (
            "<std>/system/core/string_abi.dream",
            include_str!("../system/core/string_abi.dream"),
        ),
        (
            "<std>/system/core/string_builder.dream",
            include_str!("../system/core/string_builder.dream"),
        ),
        (
            "<std>/system/core/weak.dream",
            include_str!("../system/core/weak.dream"),
        ),
        (
            "<std>/system/core/collection_tuning.dream",
            include_str!("../system/core/collection_tuning.dream"),
        ),
        (
            "<std>/system/core/equatable.dream",
            include_str!("../system/core/equatable.dream"),
        ),
        (
            "<std>/system/core/comparable.dream",
            include_str!("../system/core/comparable.dream"),
        ),
        (
            "<std>/system/core/error.dream",
            include_str!("../system/core/error.dream"),
        ),
        (
            "<std>/system/core/parse_error.dream",
            include_str!("../system/core/parse_error.dream"),
        ),
        (
            "<std>/system/core/cancelled_error.dream",
            include_str!("../system/core/cancelled_error.dream"),
        ),
        (
            "<std>/system/core/cancellation_source.dream",
            include_str!("../system/core/cancellation_source.dream"),
        ),
        (
            "<std>/system/core/cancellation_token.dream",
            include_str!("../system/core/cancellation_token.dream"),
        ),
        (
            "<std>/system/core/option.dream",
            include_str!("../system/core/option.dream"),
        ),
        (
            "<std>/system/core/panic.dream",
            include_str!("../system/core/panic.dream"),
        ),
        (
            "<std>/system/core/iterator.dream",
            include_str!("../system/core/iterator.dream"),
        ),
        (
            "<std>/system/core/collection.dream",
            include_str!("../system/core/collection.dream"),
        ),
        (
            "<std>/system/core/indexed_collection.dream",
            include_str!("../system/core/indexed_collection.dream"),
        ),
        (
            "<std>/system/core/array_iterator.dream",
            include_str!("../system/core/array_iterator.dream"),
        ),
        (
            "<std>/system/core/array_collection.dream",
            include_str!("../system/core/array_collection.dream"),
        ),
        (
            "<std>/system/core/result.dream",
            include_str!("../system/core/result.dream"),
        ),
        (
            "<std>/system/core/promise.dream",
            include_str!("../system/core/promise.dream"),
        ),
        (
            "<std>/system/core/lock.dream",
            include_str!("../system/core/lock.dream"),
        ),
        (
            "<std>/system/core/semaphore.dream",
            include_str!("../system/core/semaphore.dream"),
        ),
        (
            "<std>/system/core/js.dream",
            include_str!("../system/core/js.dream"),
        ),
        (
            "<std>/system/core/math.dream",
            include_str!("../system/core/math.dream"),
        ),
    ],
};
