use super::StdPackage;

pub(super) const PACKAGE: StdPackage = StdPackage {
    name: "system.gpu",
    deps: &[
        "system.core",
        "system.primitives",
        "system",
        "system.encoding",
    ],
    files: &[
        (
            "<std>/system/gpu/gpu_error.dream",
            include_str!("../system/gpu/gpu_error.dream"),
        ),
        (
            "<std>/system/gpu/gpu_id3.dream",
            include_str!("../system/gpu/gpu_id3.dream"),
        ),
        (
            "<std>/system/gpu/gpu_vec.dream",
            include_str!("../system/gpu/gpu_vec.dream"),
        ),
        (
            "<std>/system/gpu/gpu_buffer.dream",
            include_str!("../system/gpu/gpu_buffer.dream"),
        ),
        (
            "<std>/system/gpu/gpu_enums.dream",
            include_str!("../system/gpu/gpu_enums.dream"),
        ),
        (
            "<std>/system/gpu/gpu_swap.dream",
            include_str!("../system/gpu/gpu_swap.dream"),
        ),
        (
            "<std>/system/gpu/uniforms.dream",
            include_str!("../system/gpu/uniforms.dream"),
        ),
        (
            "<std>/system/gpu/gpu_shader.dream",
            include_str!("../system/gpu/gpu_shader.dream"),
        ),
        (
            "<std>/system/gpu/gpu_sampler_desc.dream",
            include_str!("../system/gpu/gpu_sampler_desc.dream"),
        ),
        (
            "<std>/system/gpu/gpu_sampler.dream",
            include_str!("../system/gpu/gpu_sampler.dream"),
        ),
        (
            "<std>/system/gpu/gpu_texture_desc.dream",
            include_str!("../system/gpu/gpu_texture_desc.dream"),
        ),
        (
            "<std>/system/gpu/gpu_texture.dream",
            include_str!("../system/gpu/gpu_texture.dream"),
        ),
        (
            "<std>/system/gpu/gpu_bind_list.dream",
            include_str!("../system/gpu/gpu_bind_list.dream"),
        ),
        (
            "<std>/system/gpu/compute.dream",
            include_str!("../system/gpu/compute.dream"),
        ),
        (
            "<std>/system/gpu/gpu_dispatch_indirect.dream",
            include_str!("../system/gpu/gpu_dispatch_indirect.dream"),
        ),
        (
            "<std>/system/gpu/compute_pass.dream",
            include_str!("../system/gpu/compute_pass.dream"),
        ),
        (
            "<std>/system/gpu/gpu_pointer.dream",
            include_str!("../system/gpu/gpu_pointer.dream"),
        ),
        (
            "<std>/system/gpu/gpu_mods.dream",
            include_str!("../system/gpu/gpu_mods.dream"),
        ),
        (
            "<std>/system/gpu/gpu_key_code.dream",
            include_str!("../system/gpu/gpu_key_code.dream"),
        ),
        (
            "<std>/system/gpu/gpu_gamepad.dream",
            include_str!("../system/gpu/gpu_gamepad.dream"),
        ),
        (
            "<std>/system/gpu/gpu_input_event.dream",
            include_str!("../system/gpu/gpu_input_event.dream"),
        ),
        (
            "<std>/system/gpu/gpu_input_codec.dream",
            include_str!("../system/gpu/gpu_input_codec.dream"),
        ),
        (
            "<std>/system/gpu/gpu_capabilities.dream",
            include_str!("../system/gpu/gpu_capabilities.dream"),
        ),
        (
            "<std>/system/gpu/gpu_query_set.dream",
            include_str!("../system/gpu/gpu_query_set.dream"),
        ),
        (
            "<std>/system/gpu/gpu_surface_desc.dream",
            include_str!("../system/gpu/gpu_surface_desc.dream"),
        ),
        (
            "<std>/system/gpu/gpu_surface.dream",
            include_str!("../system/gpu/gpu_surface.dream"),
        ),
        (
            "<std>/system/gpu/gpu_render_pipeline_desc.dream",
            include_str!("../system/gpu/gpu_render_pipeline_desc.dream"),
        ),
        (
            "<std>/system/gpu/gpu_render_pipeline.dream",
            include_str!("../system/gpu/gpu_render_pipeline.dream"),
        ),
        (
            "<std>/system/gpu/gpu_bind_group.dream",
            include_str!("../system/gpu/gpu_bind_group.dream"),
        ),
        (
            "<std>/system/gpu/gpu_cmd.dream",
            include_str!("../system/gpu/gpu_cmd.dream"),
        ),
        (
            "<std>/system/gpu/gpu_render_target.dream",
            include_str!("../system/gpu/gpu_render_target.dream"),
        ),
        (
            "<std>/system/gpu/gpu_encoder.dream",
            include_str!("../system/gpu/gpu_encoder.dream"),
        ),
        (
            "<std>/system/gpu/gpu_render_pass.dream",
            include_str!("../system/gpu/gpu_render_pass.dream"),
        ),
        (
            "<std>/system/gpu/gpu.dream",
            include_str!("../system/gpu/gpu.dream"),
        ),
        (
            "<std>/system/gpu/gpu_math.dream",
            include_str!("../system/gpu/gpu_math.dream"),
        ),
        (
            "<std>/system/gpu/gpu_math_vec.dream",
            include_str!("../system/gpu/gpu_math_vec.dream"),
        ),
        (
            "<std>/system/gpu/gpu_math_transform.dream",
            include_str!("../system/gpu/gpu_math_transform.dream"),
        ),
    ],
};
