use super::StdPackage;

pub(super) const PACKAGE: StdPackage = StdPackage {
    name: "system.net",
    deps: &[
        "system.core",
        "system.primitives",
        "system.collections",
        "system.text",
        "system.json",
        "system.encoding",
    ],
    files: &[
        (
            "<std>/system/net/http_error.dream",
            include_str!("../system/net/http_error.dream"),
        ),
        (
            "<std>/system/net/http_headers.dream",
            include_str!("../system/net/http_headers.dream"),
        ),
        (
            "<std>/system/net/http_headers_iterator.dream",
            include_str!("../system/net/http_headers_iterator.dream"),
        ),
        (
            "<std>/system/net/url.dream",
            include_str!("../system/net/url.dream"),
        ),
        (
            "<std>/system/net/http_response.dream",
            include_str!("../system/net/http_response.dream"),
        ),
        (
            "<std>/system/net/net_wire_reader.dream",
            include_str!("../system/net/net_wire_reader.dream"),
        ),
        (
            "<std>/system/net/http_stream_response.dream",
            include_str!("../system/net/http_stream_response.dream"),
        ),
        (
            "<std>/system/net/cookie_jar.dream",
            include_str!("../system/net/cookie_jar.dream"),
        ),
        (
            "<std>/system/net/multipart_form.dream",
            include_str!("../system/net/multipart_form.dream"),
        ),
        (
            "<std>/system/net/multipart_built.dream",
            include_str!("../system/net/multipart_built.dream"),
        ),
        (
            "<std>/system/net/http_client.dream",
            include_str!("../system/net/http_client.dream"),
        ),
        (
            "<std>/system/net/net_error.dream",
            include_str!("../system/net/net_error.dream"),
        ),
        (
            "<std>/system/net/tcp_client.dream",
            include_str!("../system/net/tcp_client.dream"),
        ),
        (
            "<std>/system/net/websocket_message.dream",
            include_str!("../system/net/websocket_message.dream"),
        ),
        (
            "<std>/system/net/websocket.dream",
            include_str!("../system/net/websocket.dream"),
        ),
    ],
};
