[package]
name = "dream-host-unicode"
version = "0.1.0"
edition.workspace = true

[lib]
name = "dream_host_unicode"
crate-type = ["cdylib"]

[dependencies]
dream-host-core = { path = "../dream-host-core" }
dream-host-abi = { path = "../dream-host-abi" }
unicode-normalization = "0.1"
unicode-segmentation = "1.12"
