[package]
name = "dream-host"
version = "0.1.0"
edition = "2021"

[dependencies]
dream-host-core = { path = "../dream-host-core", optional = true }
dream-host-net = { path = "../dream-host-net", optional = true }
dream-host-gpu = { path = "../dream-host-gpu", optional = true }
dream-host-webview = { path = "../dream-host-webview", optional = true }

[features]
default = ["core", "net", "gpu", "webview"]
core = ["dep:dream-host-core"]
net = ["core", "dep:dream-host-net"]
gpu = ["core", "dep:dream-host-gpu"]
webview = ["core", "dep:dream-host-webview"]
