[package]
name = "dream-host"
version = "0.1.0"
edition.workspace = true

[dependencies]
dream-host-core = { path = "../dream-host-core", optional = true }

dream-host-unicode = { path = "../dream-host-unicode", optional = true }
dream-host-crypto = { path = "../dream-host-crypto", optional = true }
dream-host-process = { path = "../dream-host-process", optional = true }
dream-host-timezone = { path = "../dream-host-timezone", optional = true }

[features]
default = ["core", "unicode", "crypto", "process", "timezone"]
core = ["dep:dream-host-core"]
unicode = ["core", "dep:dream-host-unicode"]
crypto = ["core", "dep:dream-host-crypto"]
process = ["core", "dep:dream-host-process"]
timezone = ["core", "dep:dream-host-timezone"]
