//! Dream `@compute` kernel → WGSL emitter.
//!
//! Kernel bodies never enter MIR/WAT. This pass walks the AST of every `@compute` function and
//! emits WGSL text plus binding metadata for the `.abi.json` `"gpu"` section / `.wgsl` sidecar.

use dream_abi::attributes::{compute_workgroup_size, has_compute_attr};
use dream_syntax::nodes::expression::ExpressionNode;
use dream_syntax::nodes::function::FunctionNode;
use dream_syntax::nodes::statement::StatementNode;
use dream_syntax::nodes::types::Type;
use dream_syntax::nodes::ProgramNode;
use dream_syntax::token::token_kind::TokenKind;

/// One storage/uniform binding derived from a kernel parameter.
#[derive(Debug, Clone)]
pub struct GpuBinding {
    pub name: String,
    pub binding: u32,
    /// `"storage"` or `"uniform"`.
    pub kind: &'static str,
    /// WGSL element / scalar type (`f32`, `i32`, …).
    pub wgsl_ty: String,
    pub read_write: bool,
}

/// Metadata for one `@compute` kernel.
#[derive(Debug, Clone)]
pub struct GpuKernelInfo {
    pub name: String,
    pub entry: String,
    pub workgroup: (u32, u32, u32),
    pub bindings: Vec<GpuBinding>,
    pub wgsl: String,
}

/// Emit WGSL for every `@compute` function in `program`.
pub fn collect_compute_kernels(program: &ProgramNode<'_>) -> Vec<GpuKernelInfo> {
    let mut out = Vec::new();
    for func in &program.functions {
        if has_compute_attr(&func.attributes) {
            out.push(emit_kernel(func));
        }
    }
    out
}

/// Concatenate all kernels into a single WGSL module (shared by the `.wgsl` sidecar).
pub fn join_wgsl_module(kernels: &[GpuKernelInfo]) -> String {
    let mut s = String::from("// Generated by Dream @compute\n\n");
    for k in kernels {
        s.push_str(&k.wgsl);
        s.push('\n');
    }
    s
}

/// JSON fragment for the `"gpu"` section of `.abi.json` (no outer braces).
/// Each kernel embeds its own WGSL `source` so the browser host can create one shader module per
/// kernel (joined modules cannot reuse `@binding(N)` across entry points).
pub fn gpu_abi_json(kernels: &[GpuKernelInfo]) -> String {
    let mut entries = Vec::new();
    for k in kernels {
        let binds: Vec<String> = k
            .bindings
            .iter()
            .map(|b| {
                format!(
                    "{{ \"name\": \"{}\", \"binding\": {}, \"kind\": \"{}\", \"type\": \"{}\", \"read_write\": {} }}",
                    json_escape(&b.name),
                    b.binding,
                    b.kind,
                    json_escape(&b.wgsl_ty),
                    b.read_write
                )
            })
            .collect();
        entries.push(format!(
            "{{ \"name\": \"{}\", \"entry\": \"{}\", \"workgroup\": [{}, {}, {}], \"bindings\": [{}], \"source\": \"{}\" }}",
            json_escape(&k.name),
            json_escape(&k.entry),
            k.workgroup.0,
            k.workgroup.1,
            k.workgroup.2,
            binds.join(", "),
            json_escape(&k.wgsl)
        ));
    }
    format!("\"kernels\": [{}]", entries.join(", "))
}

fn json_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out
}

/// Per-kernel emit context: module-scope WGSL names are prefixed with `entry` so joined multi-kernel
/// modules do not redeclare the same storage/uniform/workgroup globals.
struct EmitCtx<'a> {
    /// Unique entry name (`dream_<fn>`), used as the prefix for module-scope identifiers.
    prefix: &'a str,
    bindings: &'a [GpuBinding],
    /// Dream names of `@workgroup` locals declared in this kernel (rewritten with `prefix_`).
    workgroup_names: &'a [String],
}

impl EmitCtx<'_> {
    fn mangle(&self, dream_name: &str) -> String {
        format!("{}_{}", self.prefix, dream_name)
    }

    fn uniforms_var(&self) -> String {
        format!("dream_uniforms_{}", self.prefix)
    }

    fn is_uniform(&self, name: &str) -> bool {
        self.bindings
            .iter()
            .any(|b| b.kind == "uniform" && b.name == name)
    }

    fn is_storage(&self, name: &str) -> bool {
        self.bindings
            .iter()
            .any(|b| b.kind == "storage" && b.name == name)
    }

    fn is_workgroup(&self, name: &str) -> bool {
        self.workgroup_names.iter().any(|n| n == name)
    }

    /// Map a Dream identifier that refers to module-scope storage/workgroup memory.
    fn rewrite_ident(&self, name: &str) -> String {
        if self.is_uniform(name) {
            format!("{}.{}", self.uniforms_var(), name)
        } else if self.is_storage(name) || self.is_workgroup(name) {
            self.mangle(name)
        } else {
            name.to_string()
        }
    }
}

fn collect_workgroup_names(stmts: &[StatementNode<'_>], out: &mut Vec<String>) {
    for s in stmts {
        match s {
            StatementNode::WorkgroupDecl(name, _, _) => out.push(name.text.clone()),
            StatementNode::IfElse(_, then_b, elifs, else_b) => {
                collect_workgroup_names(then_b, out);
                for (_, b) in elifs {
                    collect_workgroup_names(b, out);
                }
                if let Some(eb) = else_b {
                    collect_workgroup_names(eb, out);
                }
            }
            StatementNode::While(_, body) | StatementNode::DoWhile(body, _) => {
                collect_workgroup_names(body, out);
            }
            StatementNode::For(init, _, step, body) => {
                if let Some(i) = init {
                    collect_workgroup_names(std::slice::from_ref(i), out);
                }
                collect_workgroup_names(body, out);
                if let Some(st) = step {
                    collect_workgroup_names(std::slice::from_ref(st), out);
                }
            }
            StatementNode::Labeled(_, inner) => {
                collect_workgroup_names(std::slice::from_ref(inner), out);
            }
            StatementNode::Switch(_, cases, default) => {
                for (_, b) in cases {
                    collect_workgroup_names(b, out);
                }
                if let Some(db) = default {
                    collect_workgroup_names(db, out);
                }
            }
            _ => {}
        }
    }
}

fn emit_kernel(func: &FunctionNode<'_>) -> GpuKernelInfo {
    let name = func.name.text.clone();
    let entry = format!("dream_{}", name);
    let workgroup = compute_workgroup_size(&func.attributes);
    let mut bindings = Vec::new();
    let mut binding_idx = 0u32;
    let mut header = String::new();
    let mut uniform_fields = String::new();
    let mut has_uniform = false;

    for param in &func.parameters {
        let pname = param.name.text.clone();
        match classify_param(&param.type_) {
            ParamClass::Storage { elem, read_write } => {
                let access = if read_write {
                    "read_write"
                } else {
                    "read"
                };
                let wgsl_name = format!("{entry}_{pname}");
                header.push_str(&format!(
                    "@group(0) @binding({binding_idx}) var<storage, {access}> {wgsl_name}: array<{elem}>;\n"
                ));
                bindings.push(GpuBinding {
                    name: pname,
                    binding: binding_idx,
                    kind: "storage",
                    wgsl_ty: elem,
                    read_write,
                });
                binding_idx += 1;
            }
            ParamClass::Uniform { ty } => {
                has_uniform = true;
                uniform_fields.push_str(&format!("  {pname}: {ty},\n"));
                bindings.push(GpuBinding {
                    name: pname,
                    binding: binding_idx, // assigned after we know the uniform struct binding
                    kind: "uniform",
                    wgsl_ty: ty,
                    read_write: false,
                });
            }
        }
    }

    if has_uniform {
        // Uniforms share one binding struct at the end of the storage bindings.
        let u_bind = binding_idx;
        let u_struct = format!("DreamUniforms_{entry}");
        let u_var = format!("dream_uniforms_{entry}");
        header.push_str(&format!("struct {u_struct} {{\n"));
        header.push_str(&uniform_fields);
        header.push_str("}\n");
        header.push_str(&format!(
            "@group(0) @binding({u_bind}) var<uniform> {u_var}: {u_struct};\n"
        ));
        for b in bindings.iter_mut() {
            if b.kind == "uniform" {
                b.binding = u_bind;
            }
        }
        binding_idx += 1;
    }
    let _ = binding_idx;

    let mut workgroup_names = Vec::new();
    collect_workgroup_names(func.body, &mut workgroup_names);
    let ctx = EmitCtx {
        prefix: &entry,
        bindings: &bindings,
        workgroup_names: &workgroup_names,
    };

    let mut workgroup_decls = String::new();
    let mut body = String::new();
    emit_stmts(func.body, &mut body, &mut workgroup_decls, 1, &ctx);

    let mut wgsl = String::new();
    wgsl.push_str(&header);
    wgsl.push('\n');
    wgsl.push_str(&workgroup_decls);
    if !workgroup_decls.is_empty() {
        wgsl.push('\n');
    }
    wgsl.push_str(&format!(
        "@compute @workgroup_size({}, {}, {})\nfn {entry}(\n",
        workgroup.0, workgroup.1, workgroup.2
    ));
    wgsl.push_str("  @builtin(global_invocation_id) global_id: vec3<u32>,\n");
    wgsl.push_str("  @builtin(local_invocation_id) local_id: vec3<u32>,\n");
    wgsl.push_str("  @builtin(workgroup_id) workgroup_id: vec3<u32>,\n");
    wgsl.push_str("  @builtin(num_workgroups) num_workgroups: vec3<u32>,\n");
    wgsl.push_str(") {\n");
    // Shadow builtins as i32 structs so Dream-style `.x` field access typechecks in source
    // (`GpuId3`) while WGSL uses `vec3<u32>` builtins.
    wgsl.push_str("  let global_id_i = vec3<i32>(i32(global_id.x), i32(global_id.y), i32(global_id.z));\n");
    wgsl.push_str("  let local_id_i = vec3<i32>(i32(local_id.x), i32(local_id.y), i32(local_id.z));\n");
    wgsl.push_str(
        "  let workgroup_id_i = vec3<i32>(i32(workgroup_id.x), i32(workgroup_id.y), i32(workgroup_id.z));\n",
    );
    wgsl.push_str(
        "  let num_workgroups_i = vec3<i32>(i32(num_workgroups.x), i32(num_workgroups.y), i32(num_workgroups.z));\n",
    );
    // Remap Dream identifiers to the i32 vectors.
    let body_mapped = body
        .replace("global_id.", "global_id_i.")
        .replace("local_id.", "local_id_i.")
        .replace("workgroup_id.", "workgroup_id_i.")
        .replace("num_workgroups.", "num_workgroups_i.");
    wgsl.push_str(&body_mapped);
    wgsl.push_str("}\n");

    GpuKernelInfo {
        name,
        entry,
        workgroup,
        bindings,
        wgsl,
    }
}

enum ParamClass {
    Storage { elem: String, read_write: bool },
    Uniform { ty: String },
}

fn classify_param(ty: &Type) -> ParamClass {
    match ty {
        // Bare `T[]` params are rejected in sema; only `GpuBuffer<T>` is storage.
        Type::Struct(tok, Some(args)) if tok.text == "GpuBuffer" && args.len() == 1 => {
            ParamClass::Storage {
                elem: dream_ty_to_wgsl(&args[0]),
                read_write: true,
            }
        }
        other => ParamClass::Uniform {
            ty: dream_ty_to_wgsl(other),
        },
    }
}

fn dream_ty_to_wgsl(ty: &Type) -> String {
    match ty {
        Type::Float(_) | Type::Double(_) => "f32".into(),
        Type::Integer(_) | Type::Byte(_) => "i32".into(),
        Type::UInt(_) => "u32".into(),
        Type::Boolean(_) => "bool".into(),
        Type::Long(_) => "i32".into(),
        Type::ULong(_) => "u32".into(),
        Type::Struct(tok, _) => match tok.text.as_str() {
            "GpuId3" => "vec3<i32>".into(),
            other => other.to_string(),
        },
        Type::Array(inner) => format!("array<{}>", dream_ty_to_wgsl(inner)),
        _ => "i32".into(),
    }
}

/// Best-effort WGSL type for unannotated `let` bindings (casts/literals/float ops).
fn infer_wgsl_ty(expr: &ExpressionNode<'_>, ctx: &EmitCtx<'_>) -> String {
    match expr {
        ExpressionNode::Cast(ty, _) | ExpressionNode::Literal(ty) => dream_ty_to_wgsl(ty),
        ExpressionNode::Parenthesized(inner)
        | ExpressionNode::NamedArg(_, inner)
        | ExpressionNode::RefArgument(inner)
        | ExpressionNode::Unary(_, inner) => infer_wgsl_ty(inner, ctx),
        ExpressionNode::Binary(l, _, r) => {
            let lt = infer_wgsl_ty(l, ctx);
            let rt = infer_wgsl_ty(r, ctx);
            if lt == "f32" || rt == "f32" {
                "f32".into()
            } else {
                lt
            }
        }
        ExpressionNode::Ternary(_, t, e) => {
            let tt = infer_wgsl_ty(t, ctx);
            let et = infer_wgsl_ty(e, ctx);
            if tt == "f32" || et == "f32" {
                "f32".into()
            } else {
                tt
            }
        }
        ExpressionNode::IndexAccess(arr, _) => {
            if let ExpressionNode::Identifier(name) = &**arr {
                if let Some(b) = ctx.bindings.iter().find(|b| b.name == name.text) {
                    return b.wgsl_ty.clone();
                }
            }
            "f32".into()
        }
        ExpressionNode::Identifier(name) => {
            if let Some(b) = ctx.bindings.iter().find(|b| b.name == name.text) {
                return b.wgsl_ty.clone();
            }
            "i32".into()
        }
        _ => "i32".into(),
    }
}

fn emit_stmts(
    stmts: &[StatementNode<'_>],
    out: &mut String,
    wg: &mut String,
    indent: usize,
    ctx: &EmitCtx<'_>,
) {
    for s in stmts {
        emit_stmt(s, out, wg, indent, ctx);
    }
}

fn pad(n: usize) -> String {
    "  ".repeat(n)
}

fn emit_stmt(
    stmt: &StatementNode<'_>,
    out: &mut String,
    wg: &mut String,
    indent: usize,
    ctx: &EmitCtx<'_>,
) {
    let p = pad(indent);
    match stmt {
        StatementNode::WorkgroupDecl(name, ty, size) => {
            let elem = dream_ty_to_wgsl(ty);
            wg.push_str(&format!(
                "var<workgroup> {}: array<{}, {}>;\n",
                ctx.mangle(&name.text),
                elem,
                size
            ));
        }
        StatementNode::Declaration(name, ty, init, _) => {
            let t = ty
                .as_ref()
                .map(dream_ty_to_wgsl)
                .unwrap_or_else(|| infer_wgsl_ty(init, ctx));
            out.push_str(&format!(
                "{}var {}: {} = {};\n",
                p,
                name.text,
                t,
                emit_expr(init, ctx)
            ));
        }
        StatementNode::Assignment(name, value) => {
            let lhs = ctx.rewrite_ident(&name.text);
            out.push_str(&format!("{}{} = {};\n", p, lhs, emit_expr(value, ctx)));
        }
        StatementNode::IndexAssignment(arr, idx, value) => {
            out.push_str(&format!(
                "{}{}[u32({})] = {};\n",
                p,
                emit_expr(arr, ctx),
                emit_expr(idx, ctx),
                emit_expr(value, ctx)
            ));
        }
        StatementNode::MemberAssignment(obj, member, value) => {
            out.push_str(&format!(
                "{}.{} = {};\n",
                emit_expr(obj, ctx),
                member.text,
                emit_expr(value, ctx)
            ));
        }
        StatementNode::Return(None) => out.push_str(&format!("{}return;\n", p)),
        StatementNode::Return(Some(_)) => out.push_str(&format!("{}return;\n", p)),
        StatementNode::IfElse(cond, then_b, elifs, else_b) => {
            out.push_str(&format!("{}if ({}) {{\n", p, emit_expr(cond, ctx)));
            emit_stmts(then_b, out, wg, indent + 1, ctx);
            out.push_str(&format!("{}}}\n", p));
            for (c, body) in elifs {
                out.push_str(&format!("{}else if ({}) {{\n", p, emit_expr(c, ctx)));
                emit_stmts(body, out, wg, indent + 1, ctx);
                out.push_str(&format!("{}}}\n", p));
            }
            if let Some(eb) = else_b {
                out.push_str(&format!("{}else {{\n", p));
                emit_stmts(eb, out, wg, indent + 1, ctx);
                out.push_str(&format!("{}}}\n", p));
            }
        }
        StatementNode::While(cond, body) => {
            out.push_str(&format!("{}loop {{\n", p));
            out.push_str(&format!(
                "{}  if (!({})) {{ break; }}\n",
                p,
                emit_expr(cond, ctx)
            ));
            emit_stmts(body, out, wg, indent + 1, ctx);
            out.push_str(&format!("{}}}\n", p));
        }
        StatementNode::DoWhile(body, cond) => {
            out.push_str(&format!("{}loop {{\n", p));
            emit_stmts(body, out, wg, indent + 1, ctx);
            out.push_str(&format!(
                "{}  if (!({})) {{ break; }}\n",
                p,
                emit_expr(cond, ctx)
            ));
            out.push_str(&format!("{}}}\n", p));
        }
        StatementNode::For(init, cond, step, body) => {
            if let Some(i) = init {
                emit_stmt(i, out, wg, indent, ctx);
            }
            out.push_str(&format!("{}loop {{\n", p));
            if let Some(c) = cond {
                out.push_str(&format!(
                    "{}  if (!({})) {{ break; }}\n",
                    p,
                    emit_expr(c, ctx)
                ));
            }
            emit_stmts(body, out, wg, indent + 1, ctx);
            if let Some(s) = step {
                emit_stmt(s, out, wg, indent + 1, ctx);
            }
            out.push_str(&format!("{}}}\n", p));
        }
        StatementNode::Break(_) => out.push_str(&format!("{}break;\n", p)),
        StatementNode::Continue(_) => out.push_str(&format!("{}continue;\n", p)),
        StatementNode::Labeled(_, inner) => emit_stmt(inner, out, wg, indent, ctx),
        StatementNode::Switch(subject, cases, default) => {
            // Lower to if-else chain (WGSL switch is more limited).
            let sub = emit_expr(subject, ctx);
            let mut first = true;
            for (labels, body) in cases {
                let conds: Vec<String> = labels
                    .iter()
                    .map(|l| format!("({}) == ({})", sub, emit_expr(l, ctx)))
                    .collect();
                let kw = if first { "if" } else { "else if" };
                first = false;
                out.push_str(&format!("{}{} ({}) {{\n", p, kw, conds.join(" || ")));
                emit_stmts(body, out, wg, indent + 1, ctx);
                out.push_str(&format!("{}}}\n", p));
            }
            if let Some(db) = default {
                out.push_str(&format!("{}else {{\n", p));
                emit_stmts(db, out, wg, indent + 1, ctx);
                out.push_str(&format!("{}}}\n", p));
            }
        }
        StatementNode::FunctionInvocation(name, _, args)
        | StatementNode::MethodInvocation(_, name, _, args) => {
            let call = emit_call(&name.text, args, ctx);
            out.push_str(&format!("{}{};\n", p, call));
        }
        StatementNode::ExpressionStatement(e) => {
            out.push_str(&format!("{}{};\n", p, emit_expr(e, ctx)));
        }
        StatementNode::ForEach(..)
        | StatementNode::AwaitStmt(_)
        | StatementNode::Lock(..)
        | StatementNode::TupleDeclaration { .. } => {
            out.push_str(&format!("{}/* unsupported in @compute */\n", p));
        }
    }
}

fn emit_call(name: &str, args: &[ExpressionNode<'_>], ctx: &EmitCtx<'_>) -> String {
    let args_s: Vec<String> = args.iter().map(|a| emit_expr(a, ctx)).collect();
    match name {
        "workgroup_barrier" => "workgroupBarrier()".into(),
        "storage_barrier" => "storageBarrier()".into(),
        "min" => format!(
            "min({}, {})",
            args_s.first().cloned().unwrap_or_else(|| "0".into()),
            args_s.get(1).cloned().unwrap_or_else(|| "0".into())
        ),
        "max" => format!(
            "max({}, {})",
            args_s.first().cloned().unwrap_or_else(|| "0".into()),
            args_s.get(1).cloned().unwrap_or_else(|| "0".into())
        ),
        "abs" => format!(
            "abs({})",
            args_s.first().cloned().unwrap_or_else(|| "0".into())
        ),
        "sqrt" => format!(
            "sqrt({})",
            args_s.first().cloned().unwrap_or_else(|| "0.0".into())
        ),
        "clamp" => format!(
            "clamp({}, {}, {})",
            args_s.first().cloned().unwrap_or_else(|| "0.0".into()),
            args_s.get(1).cloned().unwrap_or_else(|| "0.0".into()),
            args_s.get(2).cloned().unwrap_or_else(|| "0.0".into())
        ),
        "floor" => format!(
            "floor({})",
            args_s.first().cloned().unwrap_or_else(|| "0.0".into())
        ),
        "ceil" => format!(
            "ceil({})",
            args_s.first().cloned().unwrap_or_else(|| "0.0".into())
        ),
        "sin" => format!(
            "sin({})",
            args_s.first().cloned().unwrap_or_else(|| "0.0".into())
        ),
        "cos" => format!(
            "cos({})",
            args_s.first().cloned().unwrap_or_else(|| "0.0".into())
        ),
        "tan" => format!(
            "tan({})",
            args_s.first().cloned().unwrap_or_else(|| "0.0".into())
        ),
        "asin" => format!(
            "asin({})",
            args_s.first().cloned().unwrap_or_else(|| "0.0".into())
        ),
        "acos" => format!(
            "acos({})",
            args_s.first().cloned().unwrap_or_else(|| "0.0".into())
        ),
        "atan" => format!(
            "atan({})",
            args_s.first().cloned().unwrap_or_else(|| "0.0".into())
        ),
        "atan2" => format!(
            "atan2({}, {})",
            args_s.first().cloned().unwrap_or_else(|| "0.0".into()),
            args_s.get(1).cloned().unwrap_or_else(|| "0.0".into())
        ),
        other => format!("{}({})", other, args_s.join(", ")),
    }
}

fn literal_text(ty: &Type) -> String {
    match ty {
        Type::Integer(t)
        | Type::Float(t)
        | Type::Double(t)
        | Type::Long(t)
        | Type::UInt(t)
        | Type::ULong(t)
        | Type::Byte(t)
        | Type::Boolean(t)
        | Type::Char(t)
        | Type::String(t) => {
            let mut s = t.text.clone();
            if matches!(ty, Type::Float(_) | Type::Double(_))
                && !s.contains('.')
                && !s.contains('e')
                && !s.contains('E')
            {
                s.push_str(".0");
            }
            s
        }
        _ => "0".into(),
    }
}

fn emit_expr(expr: &ExpressionNode<'_>, ctx: &EmitCtx<'_>) -> String {
    match expr {
        ExpressionNode::Literal(ty) => literal_text(ty),
        ExpressionNode::Identifier(t) => ctx.rewrite_ident(&t.text),
        ExpressionNode::Binary(l, op, r) => {
            let op_s = match op.kind {
                TokenKind::PlusToken => "+",
                TokenKind::MinusToken => "-",
                TokenKind::StarToken => "*",
                TokenKind::SlashToken => "/",
                TokenKind::ModulusToken => "%",
                TokenKind::EqualEqualToken => "==",
                TokenKind::NotEqualToken => "!=",
                TokenKind::SmallerThanToken => "<",
                TokenKind::SmallerThanEqualToken => "<=",
                TokenKind::GreaterThanToken => ">",
                TokenKind::GreaterThanEqualToken => ">=",
                TokenKind::AmpersandAmpersandToken => "&&",
                TokenKind::PipePipeToken => "||",
                TokenKind::BitWiseAmpersandToken => "&",
                TokenKind::BitWisePipeToken => "|",
                _ => "+",
            };
            format!(
                "({} {} {})",
                emit_expr(l, ctx),
                op_s,
                emit_expr(r, ctx)
            )
        }
        ExpressionNode::Unary(op, e) => {
            let op_s = match op.kind {
                TokenKind::MinusToken => "-",
                TokenKind::BangToken => "!",
                TokenKind::TildeToken => "~",
                _ => "-",
            };
            format!("({}{})", op_s, emit_expr(e, ctx))
        }
        ExpressionNode::Parenthesized(e) => format!("({})", emit_expr(e, ctx)),
        ExpressionNode::IndexAccess(arr, idx) => {
            format!(
                "{}[u32({})]",
                emit_expr(arr, ctx),
                emit_expr(idx, ctx)
            )
        }
        ExpressionNode::MemberAccess(obj, member) => {
            let base = emit_expr(obj, ctx);
            if member.text == "length" {
                format!("i32(arrayLength(&{}))", base)
            } else {
                format!("{}.{}", base, member.text)
            }
        }
        ExpressionNode::FunctionCall(name, _, args) => emit_call(&name.text, args, ctx),
        ExpressionNode::MethodCall(obj, method, _, args) => {
            if method.text == "length" {
                format!("i32(arrayLength(&{}))", emit_expr(obj, ctx))
            } else {
                emit_call(&method.text, args, ctx)
            }
        }
        ExpressionNode::Call(callee, _, args) => match &**callee {
            ExpressionNode::Identifier(n) => emit_call(&n.text, args, ctx),
            ExpressionNode::MemberAccess(obj, method) => {
                if method.text == "length" {
                    format!("i32(arrayLength(&{}))", emit_expr(obj, ctx))
                } else {
                    emit_call(&method.text, args, ctx)
                }
            }
            _ => "0".into(),
        },
        ExpressionNode::Ternary(c, t, e) => format!(
            "select({}, {}, {})",
            emit_expr(e, ctx),
            emit_expr(t, ctx),
            emit_expr(c, ctx)
        ),
        ExpressionNode::Cast(ty, e) => {
            let wty = dream_ty_to_wgsl(ty);
            format!("{}({})", wty, emit_expr(e, ctx))
        }
        ExpressionNode::NamedArg(_, inner) | ExpressionNode::RefArgument(inner) => {
            emit_expr(inner, ctx)
        }
        _ => "0".into(),
    }
}
