//! Dream `@compute` kernel → WGSL emitter.
//!
//! Kernel bodies never enter MIR/WAT. This pass walks the AST of every `@compute` function and
//! emits WGSL text plus binding metadata for the `.abi.json` `"gpu"` section / `.wgsl` sidecar.

use dream_abi::attributes::{compute_workgroup_size, has_compute_attr, has_readonly_attr};
use dream_diagnostics::DiagnosticBag;
use dream_syntax::nodes::expression::ExpressionNode;
use dream_syntax::nodes::function::{FunctionNode, ParameterNode};
use dream_syntax::nodes::statement::StatementNode;
use dream_syntax::nodes::types::Type;
use dream_syntax::nodes::ProgramNode;
use dream_syntax::token::token_kind::TokenKind;
use dream_text::text_span::TextSpan;
use indexmap::{IndexMap, IndexSet};
use std::cell::RefCell;

/// One storage/uniform/texture/sampler binding derived from a kernel parameter.
#[derive(Debug, Clone)]
pub struct GpuBinding {
    pub name: String,
    pub binding: u32,
    /// `"storage"`, `"uniform"`, `"texture"`, `"storage_texture"`, or `"sampler"`.
    pub kind: &'static str,
    /// WGSL element / scalar / texture type (`f32`, `i32`, `texture_2d<f32>`, …).
    pub wgsl_ty: String,
    pub read_write: bool,
    /// When true, storage element type is `atomic<…>` (int/uint buffers used with atomics).
    pub atomic: bool,
}

/// Metadata for one `@compute` kernel.
#[derive(Debug, Clone)]
pub struct GpuKernelInfo {
    pub name: String,
    pub entry: String,
    pub workgroup: (u32, u32, u32),
    pub bindings: Vec<GpuBinding>,
    pub wgsl: String,
}

/// Emit WGSL for every `@compute` function in `program`.
/// Unsupported statements are reported on `diagnostics` (and omitted from WGSL).
pub fn collect_compute_kernels(
    program: &ProgramNode<'_>,
    diagnostics: &mut DiagnosticBag,
) -> Vec<GpuKernelInfo> {
    let mut out = Vec::new();
    for func in &program.functions {
        if has_compute_attr(&func.attributes) {
            let saved = diagnostics.file_path.clone();
            if let Some(path) = &func.file_path {
                diagnostics.file_path = Some(path.to_string());
            }
            out.push(emit_kernel(func, diagnostics));
            diagnostics.file_path = saved;
        }
    }
    out
}

/// Concatenate all kernels into a single WGSL module (shared by the `.wgsl` sidecar).
pub fn join_wgsl_module(kernels: &[GpuKernelInfo]) -> String {
    let mut s = String::from("// Generated by Dream @compute\n\n");
    for k in kernels {
        s.push_str(&k.wgsl);
        s.push('\n');
    }
    s
}

/// JSON fragment for the `"gpu"` section of `.abi.json` (no outer braces).
/// Each kernel embeds its own WGSL `source` so the browser host can create one shader module per
/// kernel (joined modules cannot reuse `@binding(N)` across entry points).
pub fn gpu_abi_json(kernels: &[GpuKernelInfo]) -> String {
    let mut entries = Vec::new();
    for k in kernels {
        let binds: Vec<String> = k
            .bindings
            .iter()
            .map(|b| {
                format!(
                    "{{ \"name\": \"{}\", \"binding\": {}, \"kind\": \"{}\", \"type\": \"{}\", \"read_write\": {}, \"atomic\": {} }}",
                    json_escape(&b.name),
                    b.binding,
                    b.kind,
                    json_escape(&b.wgsl_ty),
                    b.read_write,
                    b.atomic
                )
            })
            .collect();
        entries.push(format!(
            "{{ \"name\": \"{}\", \"entry\": \"{}\", \"workgroup\": [{}, {}, {}], \"bindings\": [{}], \"source\": \"{}\" }}",
            json_escape(&k.name),
            json_escape(&k.entry),
            k.workgroup.0,
            k.workgroup.1,
            k.workgroup.2,
            binds.join(", "),
            json_escape(&k.wgsl)
        ));
    }
    format!("\"kernels\": [{}]", entries.join(", "))
}

fn json_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out
}

/// Per-kernel emit context: module-scope WGSL names are prefixed with `entry` so joined multi-kernel
/// modules do not redeclare the same storage/uniform/workgroup globals.
struct EmitCtx<'a> {
    /// Unique entry name (`dream_<fn>`), used as the prefix for module-scope identifiers.
    prefix: &'a str,
    bindings: &'a [GpuBinding],
    /// Dream names of `@workgroup` locals declared in this kernel (rewritten with `prefix_`).
    workgroup_names: &'a [String],
    /// WGSL types of `var` locals declared so far (for mixed-type arithmetic casts).
    locals: RefCell<IndexMap<String, String>>,
}

impl EmitCtx<'_> {
    fn mangle(&self, dream_name: &str) -> String {
        format!("{}_{}", self.prefix, dream_name)
    }

    fn uniforms_var(&self) -> String {
        format!("dream_uniforms_{}", self.prefix)
    }

    fn is_uniform(&self, name: &str) -> bool {
        self.bindings
            .iter()
            .any(|b| b.kind == "uniform" && b.name == name)
    }

    fn is_resource(&self, name: &str) -> bool {
        self.bindings.iter().any(|b| {
            matches!(
                b.kind,
                "storage" | "texture" | "storage_texture" | "sampler"
            ) && b.name == name
        })
    }

    fn is_atomic_buf(&self, name: &str) -> bool {
        self.bindings
            .iter()
            .any(|b| b.kind == "storage" && b.atomic && b.name == name)
    }

    fn is_workgroup(&self, name: &str) -> bool {
        self.workgroup_names.iter().any(|n| n == name)
    }

    /// Map a Dream identifier that refers to module-scope storage/workgroup/texture memory.
    fn rewrite_ident(&self, name: &str) -> String {
        if self.is_uniform(name) {
            format!("{}.{}", self.uniforms_var(), name)
        } else if self.is_resource(name) || self.is_workgroup(name) {
            self.mangle(name)
        } else {
            name.to_string()
        }
    }
}

fn collect_workgroup_names(stmts: &[StatementNode<'_>], out: &mut Vec<String>) {
    for s in stmts {
        match s {
            StatementNode::WorkgroupDecl(name, _, _) => out.push(name.text.clone()),
            StatementNode::IfElse(_, then_b, elifs, else_b) => {
                collect_workgroup_names(then_b, out);
                for (_, b) in elifs {
                    collect_workgroup_names(b, out);
                }
                if let Some(eb) = else_b {
                    collect_workgroup_names(eb, out);
                }
            }
            StatementNode::While(_, body) | StatementNode::DoWhile(body, _) => {
                collect_workgroup_names(body, out);
            }
            StatementNode::For(init, _, step, body) => {
                if let Some(i) = init {
                    collect_workgroup_names(std::slice::from_ref(i), out);
                }
                collect_workgroup_names(body, out);
                if let Some(st) = step {
                    collect_workgroup_names(std::slice::from_ref(st), out);
                }
            }
            StatementNode::Labeled(_, inner) => {
                collect_workgroup_names(std::slice::from_ref(inner), out);
            }
            StatementNode::Switch(_, cases, default) => {
                for (_, b) in cases {
                    collect_workgroup_names(b, out);
                }
                if let Some(db) = default {
                    collect_workgroup_names(db, out);
                }
            }
            _ => {}
        }
    }
}

fn emit_kernel(func: &FunctionNode<'_>, diagnostics: &mut DiagnosticBag) -> GpuKernelInfo {
    let name = func.name.text.clone();
    let entry = format!("dream_{}", name);
    let workgroup = compute_workgroup_size(&func.attributes);
    let atomic_bufs = collect_atomic_buffer_names(func.body);

    let mut bindings = Vec::new();
    let mut binding_idx = 0u32;
    let mut header = String::new();
    let mut uniform_fields = String::new();
    let mut has_uniform = false;

    for param in &func.parameters {
        let pname = param.name.text.clone();
        let is_atomic = atomic_bufs.contains(pname.as_str());
        match classify_param(param, is_atomic) {
            ParamClass::Storage {
                elem,
                read_write,
                atomic,
            } => {
                let access = if read_write {
                    "read_write"
                } else {
                    "read"
                };
                let elem_ty = if atomic {
                    format!("atomic<{elem}>")
                } else {
                    elem.clone()
                };
                let wgsl_name = format!("{entry}_{pname}");
                header.push_str(&format!(
                    "@group(0) @binding({binding_idx}) var<storage, {access}> {wgsl_name}: array<{elem_ty}>;\n"
                ));
                bindings.push(GpuBinding {
                    name: pname,
                    binding: binding_idx,
                    kind: "storage",
                    wgsl_ty: elem,
                    read_write,
                    atomic,
                });
                binding_idx += 1;
            }
            ParamClass::Texture { storage } => {
                let wgsl_name = format!("{entry}_{pname}");
                let (kind, decl) = if storage {
                    (
                        "storage_texture",
                        format!(
                            "@group(0) @binding({binding_idx}) var {wgsl_name}: texture_storage_2d<rgba8unorm, write>;\n"
                        ),
                    )
                } else {
                    (
                        "texture",
                        format!(
                            "@group(0) @binding({binding_idx}) var {wgsl_name}: texture_2d<f32>;\n"
                        ),
                    )
                };
                header.push_str(&decl);
                bindings.push(GpuBinding {
                    name: pname,
                    binding: binding_idx,
                    kind,
                    wgsl_ty: if storage {
                        "texture_storage_2d<rgba8unorm, write>".into()
                    } else {
                        "texture_2d<f32>".into()
                    },
                    read_write: storage,
                    atomic: false,
                });
                binding_idx += 1;
            }
            ParamClass::Sampler => {
                let wgsl_name = format!("{entry}_{pname}");
                header.push_str(&format!(
                    "@group(0) @binding({binding_idx}) var {wgsl_name}: sampler;\n"
                ));
                bindings.push(GpuBinding {
                    name: pname,
                    binding: binding_idx,
                    kind: "sampler",
                    wgsl_ty: "sampler".into(),
                    read_write: false,
                    atomic: false,
                });
                binding_idx += 1;
            }
            ParamClass::Uniform { ty } => {
                has_uniform = true;
                uniform_fields.push_str(&format!("  {pname}: {ty},\n"));
                bindings.push(GpuBinding {
                    name: pname,
                    binding: binding_idx, // assigned after we know the uniform struct binding
                    kind: "uniform",
                    wgsl_ty: ty,
                    read_write: false,
                    atomic: false,
                });
            }
        }
    }

    if has_uniform {
        // Uniforms share one binding struct at the end of the storage bindings.
        let u_bind = binding_idx;
        let u_struct = format!("DreamUniforms_{entry}");
        let u_var = format!("dream_uniforms_{entry}");
        header.push_str(&format!("struct {u_struct} {{\n"));
        header.push_str(&uniform_fields);
        header.push_str("}\n");
        header.push_str(&format!(
            "@group(0) @binding({u_bind}) var<uniform> {u_var}: {u_struct};\n"
        ));
        for b in bindings.iter_mut() {
            if b.kind == "uniform" {
                b.binding = u_bind;
            }
        }
        binding_idx += 1;
    }
    let _ = binding_idx;

    let mut workgroup_names = Vec::new();
    collect_workgroup_names(func.body, &mut workgroup_names);
    let ctx = EmitCtx {
        prefix: &entry,
        bindings: &bindings,
        workgroup_names: &workgroup_names,
        locals: RefCell::new(IndexMap::new()),
    };

    let mut workgroup_decls = String::new();
    let mut body = String::new();
    emit_stmts(
        func.body,
        &mut body,
        &mut workgroup_decls,
        1,
        &ctx,
        diagnostics,
        &func.name.text,
    );

    let mut wgsl = String::new();
    wgsl.push_str(&header);
    wgsl.push('\n');
    wgsl.push_str(&workgroup_decls);
    if !workgroup_decls.is_empty() {
        wgsl.push('\n');
    }
    wgsl.push_str(&format!(
        "@compute @workgroup_size({}, {}, {})\nfn {entry}(\n",
        workgroup.0, workgroup.1, workgroup.2
    ));
    wgsl.push_str("  @builtin(global_invocation_id) global_id: vec3<u32>,\n");
    wgsl.push_str("  @builtin(local_invocation_id) local_id: vec3<u32>,\n");
    wgsl.push_str("  @builtin(workgroup_id) workgroup_id: vec3<u32>,\n");
    wgsl.push_str("  @builtin(num_workgroups) num_workgroups: vec3<u32>,\n");
    wgsl.push_str(") {\n");
    // Shadow builtins as i32 structs so Dream-style `.x` field access typechecks in source
    // (`GpuId3`) while WGSL uses `vec3<u32>` builtins.
    wgsl.push_str("  let global_id_i = vec3<i32>(i32(global_id.x), i32(global_id.y), i32(global_id.z));\n");
    wgsl.push_str("  let local_id_i = vec3<i32>(i32(local_id.x), i32(local_id.y), i32(local_id.z));\n");
    wgsl.push_str(
        "  let workgroup_id_i = vec3<i32>(i32(workgroup_id.x), i32(workgroup_id.y), i32(workgroup_id.z));\n",
    );
    wgsl.push_str(
        "  let num_workgroups_i = vec3<i32>(i32(num_workgroups.x), i32(num_workgroups.y), i32(num_workgroups.z));\n",
    );
    // Remap Dream identifiers to the i32 vectors.
    let body_mapped = body
        .replace("global_id.", "global_id_i.")
        .replace("local_id.", "local_id_i.")
        .replace("workgroup_id.", "workgroup_id_i.")
        .replace("num_workgroups.", "num_workgroups_i.");
    wgsl.push_str(&body_mapped);
    wgsl.push_str("}\n");

    GpuKernelInfo {
        name,
        entry,
        workgroup,
        bindings,
        wgsl,
    }
}

enum ParamClass {
    Storage {
        elem: String,
        read_write: bool,
        atomic: bool,
    },
    Texture {
        /// `true` → `texture_storage_2d` (write); `false` → sampled `texture_2d`.
        storage: bool,
    },
    Sampler,
    Uniform {
        ty: String,
    },
}

fn classify_param(param: &ParameterNode, is_atomic: bool) -> ParamClass {
    let readonly = has_readonly_attr(&param.attributes);
    match &param.type_ {
        // Bare `T[]` params are rejected in sema; only `GpuBuffer<T>` is storage.
        Type::Struct(tok, Some(args)) if tok.text == "GpuBuffer" && args.len() == 1 => {
            let elem = dream_ty_to_wgsl(&args[0]);
            let atomic = is_atomic && matches!(elem.as_str(), "i32" | "u32");
            ParamClass::Storage {
                elem,
                read_write: !readonly,
                atomic,
            }
        }
        Type::Struct(tok, None) if tok.text == "GpuTexture" => {
            // `@readonly GpuTexture` → sampled; otherwise storage texture (write).
            ParamClass::Texture {
                storage: !readonly,
            }
        }
        Type::Struct(tok, None) if tok.text == "GpuSampler" => ParamClass::Sampler,
        other => ParamClass::Uniform {
            ty: dream_ty_to_wgsl(other),
        },
    }
}

/// Buffer names passed to `Gpu.atomic_*` helpers — those storage bindings become `atomic<T>`.
fn collect_atomic_buffer_names(stmts: &[StatementNode<'_>]) -> IndexSet<String> {
    let mut out = IndexSet::new();
    walk_stmts_atomics(stmts, &mut out);
    out
}

fn walk_stmts_atomics(stmts: &[StatementNode<'_>], out: &mut IndexSet<String>) {
    for s in stmts {
        match s {
            StatementNode::ExpressionStatement(e)
            | StatementNode::Return(Some(e))
            | StatementNode::AwaitStmt(e) => walk_expr_atomics(e, out),
            StatementNode::Assignment(_, e)
            | StatementNode::Declaration(_, _, e, _)
            | StatementNode::MemberAssignment(_, _, e) => walk_expr_atomics(e, out),
            StatementNode::IndexAssignment(arr, idx, value) => {
                walk_expr_atomics(arr, out);
                walk_expr_atomics(idx, out);
                walk_expr_atomics(value, out);
            }
            StatementNode::FunctionInvocation(_, _, args) => {
                for a in args {
                    walk_expr_atomics(a, out);
                }
            }
            StatementNode::MethodInvocation(obj, method, _, args) => {
                if matches!(
                    method.text.as_str(),
                    "atomic_load" | "atomic_add" | "atomic_exchange" | "atomic_store"
                ) {
                    if let Some(ExpressionNode::Identifier(name)) = args.first() {
                        out.insert(name.text.clone());
                    }
                }
                walk_expr_atomics(obj, out);
                for a in args {
                    walk_expr_atomics(a, out);
                }
            }
            StatementNode::IfElse(cond, then_b, elifs, else_b) => {
                walk_expr_atomics(cond, out);
                walk_stmts_atomics(then_b, out);
                for (c, body) in elifs {
                    walk_expr_atomics(c, out);
                    walk_stmts_atomics(body, out);
                }
                if let Some(eb) = else_b {
                    walk_stmts_atomics(eb, out);
                }
            }
            StatementNode::While(cond, body) => {
                walk_expr_atomics(cond, out);
                walk_stmts_atomics(body, out);
            }
            StatementNode::DoWhile(body, cond) => {
                walk_stmts_atomics(body, out);
                walk_expr_atomics(cond, out);
            }
            StatementNode::For(init, cond, step, body) => {
                if let Some(i) = init {
                    walk_stmts_atomics(std::slice::from_ref(i), out);
                }
                if let Some(c) = cond {
                    walk_expr_atomics(c, out);
                }
                if let Some(s) = step {
                    walk_stmts_atomics(std::slice::from_ref(s), out);
                }
                walk_stmts_atomics(body, out);
            }
            StatementNode::Switch(subj, cases, default) => {
                walk_expr_atomics(subj, out);
                for (_, body) in cases {
                    walk_stmts_atomics(body, out);
                }
                if let Some(d) = default {
                    walk_stmts_atomics(d, out);
                }
            }
            StatementNode::Labeled(_, inner) => walk_stmts_atomics(std::slice::from_ref(inner), out),
            StatementNode::Lock(e, body) => {
                walk_expr_atomics(e, out);
                walk_stmts_atomics(body, out);
            }
            _ => {}
        }
    }
}

fn walk_expr_atomics(expr: &ExpressionNode<'_>, out: &mut IndexSet<String>) {
    match expr {
        ExpressionNode::MethodCall(obj, method, _, args)
            if matches!(
                method.text.as_str(),
                "atomic_load" | "atomic_add" | "atomic_exchange" | "atomic_store"
            ) =>
        {
            if let Some(ExpressionNode::Identifier(name)) = args.first() {
                out.insert(name.text.clone());
            }
            walk_expr_atomics(obj, out);
            for a in args {
                walk_expr_atomics(a, out);
            }
        }
        ExpressionNode::FunctionCall(name, _, args)
            if matches!(
                name.text.as_str(),
                "atomic_load" | "atomic_add" | "atomic_exchange" | "atomic_store"
            ) =>
        {
            if let Some(ExpressionNode::Identifier(n)) = args.first() {
                out.insert(n.text.clone());
            }
            for a in args {
                walk_expr_atomics(a, out);
            }
        }
        ExpressionNode::Binary(l, _, r) | ExpressionNode::IndexAccess(l, r) => {
            walk_expr_atomics(l, out);
            walk_expr_atomics(r, out);
        }
        ExpressionNode::MemberAccess(l, _) => walk_expr_atomics(l, out),
        ExpressionNode::Ternary(c, t, e) => {
            walk_expr_atomics(c, out);
            walk_expr_atomics(t, out);
            walk_expr_atomics(e, out);
        }
        ExpressionNode::Unary(_, e)
        | ExpressionNode::Parenthesized(e)
        | ExpressionNode::Cast(_, e)
        | ExpressionNode::NamedArg(_, e)
        | ExpressionNode::RefArgument(e)
        | ExpressionNode::Await(e)
        | ExpressionNode::Try(e)
        | ExpressionNode::IncDec { target: e, .. } => walk_expr_atomics(e, out),
        ExpressionNode::FunctionCall(_, _, args) => {
            for a in args {
                walk_expr_atomics(a, out);
            }
        }
        ExpressionNode::MethodCall(obj, _, _, args) | ExpressionNode::Call(obj, _, args) => {
            walk_expr_atomics(obj, out);
            for a in args {
                walk_expr_atomics(a, out);
            }
        }
        _ => {}
    }
}

fn dream_ty_to_wgsl(ty: &Type) -> String {
    match ty {
        Type::Float(_) | Type::Double(_) => "f32".into(),
        Type::Integer(_) | Type::Byte(_) => "i32".into(),
        Type::UInt(_) => "u32".into(),
        Type::Boolean(_) => "bool".into(),
        Type::Long(_) => "i32".into(),
        Type::ULong(_) => "u32".into(),
        Type::Struct(tok, _) => match tok.text.as_str() {
            "GpuId3" => "vec3<i32>".into(),
            other => other.to_string(),
        },
        Type::Array(inner) => format!("array<{}>", dream_ty_to_wgsl(inner)),
        _ => "i32".into(),
    }
}

/// Emit `expr`, inserting a WGSL constructor cast when the inferred type differs from `want`.
fn coerce_expr_to_wgsl_ty(expr: &ExpressionNode<'_>, want: &str, ctx: &EmitCtx<'_>) -> String {
    let got = infer_wgsl_ty(expr, ctx);
    let rendered = emit_expr(expr, ctx);
    cast_wgsl_if_needed(rendered, &got, want)
}

fn cast_wgsl_if_needed(rendered: String, got: &str, want: &str) -> String {
    if got == want || want.is_empty() {
        rendered
    } else {
        format!("{want}({rendered})")
    }
}

fn common_numeric_wgsl_ty(lt: &str, rt: &str) -> String {
    if lt == "f32" || rt == "f32" {
        "f32".into()
    } else if lt == "u32" && rt == "u32" {
        "u32".into()
    } else if lt == "bool" || rt == "bool" {
        "bool".into()
    } else {
        // Default integer lane (i32), including mixed i32/u32.
        "i32".into()
    }
}

fn is_bool_producing_binop(kind: TokenKind) -> bool {
    matches!(
        kind,
        TokenKind::EqualEqualToken
            | TokenKind::NotEqualToken
            | TokenKind::SmallerThanToken
            | TokenKind::SmallerThanEqualToken
            | TokenKind::GreaterThanToken
            | TokenKind::GreaterThanEqualToken
            | TokenKind::AmpersandAmpersandToken
            | TokenKind::PipePipeToken
    )
}

/// Best-effort WGSL type for unannotated `let` bindings (casts/literals/float ops).
fn infer_wgsl_ty(expr: &ExpressionNode<'_>, ctx: &EmitCtx<'_>) -> String {
    match expr {
        ExpressionNode::Cast(ty, _) | ExpressionNode::Literal(ty) => dream_ty_to_wgsl(ty),
        ExpressionNode::Parenthesized(inner)
        | ExpressionNode::NamedArg(_, inner)
        | ExpressionNode::RefArgument(inner)
        | ExpressionNode::IncDec { target: inner, .. } => infer_wgsl_ty(inner, ctx),
        ExpressionNode::Unary(op, inner) => {
            if op.kind == TokenKind::BangToken {
                "bool".into()
            } else {
                infer_wgsl_ty(inner, ctx)
            }
        }
        ExpressionNode::Binary(l, op, r) => {
            if is_bool_producing_binop(op.kind) {
                return "bool".into();
            }
            let lt = infer_wgsl_ty(l, ctx);
            let rt = infer_wgsl_ty(r, ctx);
            if lt == "f32" || rt == "f32" {
                "f32".into()
            } else {
                lt
            }
        }
        ExpressionNode::Ternary(_, t, e) => {
            let tt = infer_wgsl_ty(t, ctx);
            let et = infer_wgsl_ty(e, ctx);
            if tt == "f32" || et == "f32" {
                "f32".into()
            } else {
                tt
            }
        }
        ExpressionNode::IndexAccess(arr, _) => {
            if let ExpressionNode::Identifier(name) = &**arr {
                if let Some(b) = ctx.bindings.iter().find(|b| b.name == name.text) {
                    return b.wgsl_ty.clone();
                }
            }
            "f32".into()
        }
        ExpressionNode::Identifier(name) => {
            if let Some(b) = ctx.bindings.iter().find(|b| b.name == name.text) {
                return b.wgsl_ty.clone();
            }
            if let Some(t) = ctx.locals.borrow().get(&name.text) {
                return t.clone();
            }
            "i32".into()
        }
        _ => "i32".into(),
    }
}


fn stmt_span(stmt: &StatementNode<'_>) -> Option<TextSpan> {
    match stmt {
        StatementNode::Assignment(tok, _)
        | StatementNode::Declaration(tok, _, _, _)
        | StatementNode::WorkgroupDecl(tok, _, _)
        | StatementNode::FunctionInvocation(tok, _, _)
        | StatementNode::MethodInvocation(_, tok, _, _)
        | StatementNode::MemberAssignment(_, tok, _)
        | StatementNode::ForEach(tok, _, _, _, _) => Some(tok.position),
        StatementNode::TupleDeclaration { names, init, .. } => names
            .first()
            .map(|n| n.position)
            .or_else(|| init.position()),
        StatementNode::IndexAssignment(arr, _, _) => arr.position(),
        StatementNode::Return(Some(e))
        | StatementNode::ExpressionStatement(e)
        | StatementNode::AwaitStmt(e)
        | StatementNode::While(e, _)
        | StatementNode::DoWhile(_, e)
        | StatementNode::Lock(e, _)
        | StatementNode::IfElse(e, _, _, _)
        | StatementNode::Switch(e, _, _) => e.position(),
        StatementNode::For(_, Some(cond), _, _) => cond.position(),
        StatementNode::Labeled(_, inner) => stmt_span(inner),
        StatementNode::Return(None)
        | StatementNode::For(_, None, _, _)
        | StatementNode::Break(_)
        | StatementNode::Continue(_) => None,
    }
}

fn emit_stmts(
    stmts: &[StatementNode<'_>],
    out: &mut String,
    wg: &mut String,
    indent: usize,
    ctx: &EmitCtx<'_>,
    diagnostics: &mut DiagnosticBag,
    kernel: &str,
) {
    for s in stmts {
        emit_stmt(s, out, wg, indent, ctx, diagnostics, kernel);
    }
}

fn pad(n: usize) -> String {
    "  ".repeat(n)
}

fn emit_stmt(
    stmt: &StatementNode<'_>,
    out: &mut String,
    wg: &mut String,
    indent: usize,
    ctx: &EmitCtx<'_>,
    diagnostics: &mut DiagnosticBag,
    kernel: &str,
) {
    let p = pad(indent);
    match stmt {
        StatementNode::WorkgroupDecl(name, ty, size) => {
            let elem = dream_ty_to_wgsl(ty);
            wg.push_str(&format!(
                "var<workgroup> {}: array<{}, {}>;\n",
                ctx.mangle(&name.text),
                elem,
                size
            ));
        }
        StatementNode::Declaration(name, ty, init, _) => {
            if let ExpressionNode::IncDec {
                prefix,
                is_inc,
                target,
                ..
            } = init
            {
                let place = emit_expr(target, ctx);
                let op = if *is_inc { "+" } else { "-" };
                let t = ty
                    .as_ref()
                    .map(dream_ty_to_wgsl)
                    .unwrap_or_else(|| infer_wgsl_ty(init, ctx));
                ctx.locals.borrow_mut().insert(name.text.clone(), t.clone());
                if *prefix {
                    out.push_str(&format!("{}{} = {} {} 1;\n", p, place, place, op));
                    out.push_str(&format!("{}var {}: {} = {};\n", p, name.text, t, place));
                } else {
                    out.push_str(&format!("{}var {}: {} = {};\n", p, name.text, t, place));
                    out.push_str(&format!("{}{} = {} {} 1;\n", p, place, place, op));
                }
                return;
            }
            let t = ty
                .as_ref()
                .map(dream_ty_to_wgsl)
                .unwrap_or_else(|| infer_wgsl_ty(init, ctx));
            let init_s = coerce_expr_to_wgsl_ty(init, &t, ctx);
            ctx.locals.borrow_mut().insert(name.text.clone(), t.clone());
            out.push_str(&format!(
                "{}var {}: {} = {};\n",
                p,
                name.text,
                t,
                init_s
            ));
        }
        StatementNode::Assignment(name, value) => {
            let lhs = ctx.rewrite_ident(&name.text);
            let want = ctx
                .locals
                .borrow()
                .get(&name.text)
                .cloned()
                .unwrap_or_else(|| infer_wgsl_ty(value, ctx));
            let rhs = coerce_expr_to_wgsl_ty(value, &want, ctx);
            out.push_str(&format!("{}{} = {};\n", p, lhs, rhs));
        }
        StatementNode::IndexAssignment(arr, idx, value) => {
            let arr_s = emit_expr(arr, ctx);
            let idx_s = emit_expr(idx, ctx);
            let val_s = emit_expr(value, ctx);
            let atomic = matches!(arr, ExpressionNode::Identifier(n) if ctx.is_atomic_buf(&n.text));
            if atomic {
                out.push_str(&format!(
                    "{}atomicStore(&{}[u32({})], {});\n",
                    p, arr_s, idx_s, val_s
                ));
            } else {
                out.push_str(&format!("{}{}[u32({})] = {};\n", p, arr_s, idx_s, val_s));
            }
        }
        StatementNode::MemberAssignment(obj, member, value) => {
            out.push_str(&format!(
                "{}.{} = {};\n",
                emit_expr(obj, ctx),
                member.text,
                emit_expr(value, ctx)
            ));
        }
        StatementNode::Return(None) => out.push_str(&format!("{}return;\n", p)),
        StatementNode::Return(Some(_)) => out.push_str(&format!("{}return;\n", p)),
        StatementNode::IfElse(cond, then_b, elifs, else_b) => {
            out.push_str(&format!("{}if ({}) {{\n", p, emit_expr(cond, ctx)));
            emit_stmts(then_b, out, wg, indent + 1, ctx, diagnostics, kernel);
            out.push_str(&format!("{}}}\n", p));
            for (c, body) in elifs {
                out.push_str(&format!("{}else if ({}) {{\n", p, emit_expr(c, ctx)));
                emit_stmts(body, out, wg, indent + 1, ctx, diagnostics, kernel);
                out.push_str(&format!("{}}}\n", p));
            }
            if let Some(eb) = else_b {
                out.push_str(&format!("{}else {{\n", p));
                emit_stmts(eb, out, wg, indent + 1, ctx, diagnostics, kernel);
                out.push_str(&format!("{}}}\n", p));
            }
        }
        StatementNode::While(cond, body) => {
            out.push_str(&format!("{}loop {{\n", p));
            out.push_str(&format!(
                "{}  if (!({})) {{ break; }}\n",
                p,
                emit_expr(cond, ctx)
            ));
            emit_stmts(body, out, wg, indent + 1, ctx, diagnostics, kernel);
            out.push_str(&format!("{}}}\n", p));
        }
        StatementNode::DoWhile(body, cond) => {
            out.push_str(&format!("{}loop {{\n", p));
            emit_stmts(body, out, wg, indent + 1, ctx, diagnostics, kernel);
            out.push_str(&format!(
                "{}  if (!({})) {{ break; }}\n",
                p,
                emit_expr(cond, ctx)
            ));
            out.push_str(&format!("{}}}\n", p));
        }
        StatementNode::For(init, cond, step, body) => {
            if let Some(i) = init {
                emit_stmt(i, out, wg, indent, ctx, diagnostics, kernel);
            }
            out.push_str(&format!("{}loop {{\n", p));
            if let Some(c) = cond {
                out.push_str(&format!(
                    "{}  if (!({})) {{ break; }}\n",
                    p,
                    emit_expr(c, ctx)
                ));
            }
            emit_stmts(body, out, wg, indent + 1, ctx, diagnostics, kernel);
            if let Some(s) = step {
                emit_stmt(s, out, wg, indent + 1, ctx, diagnostics, kernel);
            }
            out.push_str(&format!("{}}}\n", p));
        }
        StatementNode::Break(_) => out.push_str(&format!("{}break;\n", p)),
        StatementNode::Continue(_) => out.push_str(&format!("{}continue;\n", p)),
        StatementNode::Labeled(_, inner) => emit_stmt(inner, out, wg, indent, ctx, diagnostics, kernel),
        StatementNode::Switch(subject, cases, default) => {
            // Lower to if-else chain (WGSL switch is more limited).
            let sub = emit_expr(subject, ctx);
            let mut first = true;
            for (labels, body) in cases {
                let conds: Vec<String> = labels
                    .iter()
                    .map(|l| format!("({}) == ({})", sub, emit_expr(l, ctx)))
                    .collect();
                let kw = if first { "if" } else { "else if" };
                first = false;
                out.push_str(&format!("{}{} ({}) {{\n", p, kw, conds.join(" || ")));
                emit_stmts(body, out, wg, indent + 1, ctx, diagnostics, kernel);
                out.push_str(&format!("{}}}\n", p));
            }
            if let Some(db) = default {
                out.push_str(&format!("{}else {{\n", p));
                emit_stmts(db, out, wg, indent + 1, ctx, diagnostics, kernel);
                out.push_str(&format!("{}}}\n", p));
            }
        }
        StatementNode::FunctionInvocation(name, _, args)
        | StatementNode::MethodInvocation(_, name, _, args) => {
            let call = emit_call(&name.text, args, ctx);
            out.push_str(&format!("{}{};\n", p, call));
        }
        StatementNode::ExpressionStatement(e) => {
            out.push_str(&format!("{}{};\n", p, emit_expr(e, ctx)));
        }
        StatementNode::ForEach(..)
        | StatementNode::AwaitStmt(_)
        | StatementNode::Lock(..)
        | StatementNode::TupleDeclaration { .. } => {
            let kind = match stmt {
                StatementNode::ForEach(..) => "for-each",
                StatementNode::AwaitStmt(_) => "await",
                StatementNode::Lock(..) => "lock",
                StatementNode::TupleDeclaration { .. } => "tuple declaration",
                _ => "statement",
            };
            diagnostics.report_error(
                format!(
                    "@compute kernel '{kernel}' contains unsupported {kind}; remove it or rewrite with supported control flow"
                ),
                stmt_span(stmt),
            );
        }
    }
}

fn emit_call(name: &str, args: &[ExpressionNode<'_>], ctx: &EmitCtx<'_>) -> String {
    let args_s: Vec<String> = args.iter().map(|a| emit_expr(a, ctx)).collect();
    match name {
        "workgroup_barrier" => "workgroupBarrier()".into(),
        "storage_barrier" => "storageBarrier()".into(),
        "atomic_load" => {
            let buf = args_s.first().cloned().unwrap_or_else(|| "buf".into());
            let idx = args_s.get(1).cloned().unwrap_or_else(|| "0".into());
            format!("atomicLoad(&{buf}[u32({idx})])")
        }
        "atomic_store" => {
            let buf = args_s.first().cloned().unwrap_or_else(|| "buf".into());
            let idx = args_s.get(1).cloned().unwrap_or_else(|| "0".into());
            let val = args_s.get(2).cloned().unwrap_or_else(|| "0".into());
            format!("atomicStore(&{buf}[u32({idx})], {val})")
        }
        "atomic_add" => {
            let buf = args_s.first().cloned().unwrap_or_else(|| "buf".into());
            let idx = args_s.get(1).cloned().unwrap_or_else(|| "0".into());
            let val = args_s.get(2).cloned().unwrap_or_else(|| "0".into());
            format!("atomicAdd(&{buf}[u32({idx})], {val})")
        }
        "atomic_exchange" => {
            let buf = args_s.first().cloned().unwrap_or_else(|| "buf".into());
            let idx = args_s.get(1).cloned().unwrap_or_else(|| "0".into());
            let val = args_s.get(2).cloned().unwrap_or_else(|| "0".into());
            format!("atomicExchange(&{buf}[u32({idx})], {val})")
        }
        "texture_load" => {
            let tex = args_s.first().cloned().unwrap_or_else(|| "tex".into());
            let x = args_s.get(1).cloned().unwrap_or_else(|| "0".into());
            let y = args_s.get(2).cloned().unwrap_or_else(|| "0".into());
            format!("textureLoad({tex}, vec2<i32>({x}, {y}), 0)")
        }
        "texture_store" => {
            let tex = args_s.first().cloned().unwrap_or_else(|| "tex".into());
            let x = args_s.get(1).cloned().unwrap_or_else(|| "0".into());
            let y = args_s.get(2).cloned().unwrap_or_else(|| "0".into());
            let r = args_s.get(3).cloned().unwrap_or_else(|| "0.0".into());
            let g = args_s.get(4).cloned().unwrap_or_else(|| "0.0".into());
            let b = args_s.get(5).cloned().unwrap_or_else(|| "0.0".into());
            let a = args_s.get(6).cloned().unwrap_or_else(|| "1.0".into());
            format!(
                "textureStore({tex}, vec2<i32>({x}, {y}), vec4<f32>({r}, {g}, {b}, {a}))"
            )
        }
        "texture_sample_level" => {
            let tex = args_s.first().cloned().unwrap_or_else(|| "tex".into());
            let samp = args_s.get(1).cloned().unwrap_or_else(|| "samp".into());
            let u = args_s.get(2).cloned().unwrap_or_else(|| "0.0".into());
            let v = args_s.get(3).cloned().unwrap_or_else(|| "0.0".into());
            let level = args_s.get(4).cloned().unwrap_or_else(|| "0.0".into());
            format!("textureSampleLevel({tex}, {samp}, vec2<f32>({u}, {v}), {level})")
        }
        "min" => format!(
            "min({}, {})",
            args_s.first().cloned().unwrap_or_else(|| "0".into()),
            args_s.get(1).cloned().unwrap_or_else(|| "0".into())
        ),
        "max" => format!(
            "max({}, {})",
            args_s.first().cloned().unwrap_or_else(|| "0".into()),
            args_s.get(1).cloned().unwrap_or_else(|| "0".into())
        ),
        "abs" => format!(
            "abs({})",
            args_s.first().cloned().unwrap_or_else(|| "0".into())
        ),
        "sqrt" => format!(
            "sqrt({})",
            args_s.first().cloned().unwrap_or_else(|| "0.0".into())
        ),
        "clamp" => format!(
            "clamp({}, {}, {})",
            args_s.first().cloned().unwrap_or_else(|| "0.0".into()),
            args_s.get(1).cloned().unwrap_or_else(|| "0.0".into()),
            args_s.get(2).cloned().unwrap_or_else(|| "0.0".into())
        ),
        "floor" => format!(
            "floor({})",
            args_s.first().cloned().unwrap_or_else(|| "0.0".into())
        ),
        "ceil" => format!(
            "ceil({})",
            args_s.first().cloned().unwrap_or_else(|| "0.0".into())
        ),
        "sin" => format!(
            "sin({})",
            args_s.first().cloned().unwrap_or_else(|| "0.0".into())
        ),
        "cos" => format!(
            "cos({})",
            args_s.first().cloned().unwrap_or_else(|| "0.0".into())
        ),
        "tan" => format!(
            "tan({})",
            args_s.first().cloned().unwrap_or_else(|| "0.0".into())
        ),
        "asin" => format!(
            "asin({})",
            args_s.first().cloned().unwrap_or_else(|| "0.0".into())
        ),
        "acos" => format!(
            "acos({})",
            args_s.first().cloned().unwrap_or_else(|| "0.0".into())
        ),
        "atan" => format!(
            "atan({})",
            args_s.first().cloned().unwrap_or_else(|| "0.0".into())
        ),
        "atan2" => format!(
            "atan2({}, {})",
            args_s.first().cloned().unwrap_or_else(|| "0.0".into()),
            args_s.get(1).cloned().unwrap_or_else(|| "0.0".into())
        ),
        other => format!("{}({})", other, args_s.join(", ")),
    }
}

fn literal_text(ty: &Type) -> String {
    match ty {
        Type::Integer(t)
        | Type::Float(t)
        | Type::Double(t)
        | Type::Long(t)
        | Type::UInt(t)
        | Type::ULong(t)
        | Type::Byte(t)
        | Type::Boolean(t)
        | Type::Char(t)
        | Type::String(t) => {
            let mut s = t.text.clone();
            if matches!(ty, Type::Float(_) | Type::Double(_))
                && !s.contains('.')
                && !s.contains('e')
                && !s.contains('E')
            {
                s.push_str(".0");
            }
            s
        }
        _ => "0".into(),
    }
}

fn emit_expr(expr: &ExpressionNode<'_>, ctx: &EmitCtx<'_>) -> String {
    match expr {
        ExpressionNode::Literal(ty) => literal_text(ty),
        ExpressionNode::Identifier(t) => ctx.rewrite_ident(&t.text),
        ExpressionNode::Binary(l, op, r) => {
            let op_s = match op.kind {
                TokenKind::PlusToken => "+",
                TokenKind::MinusToken => "-",
                TokenKind::StarToken => "*",
                TokenKind::SlashToken => "/",
                TokenKind::ModulusToken => "%",
                TokenKind::EqualEqualToken => "==",
                TokenKind::NotEqualToken => "!=",
                TokenKind::SmallerThanToken => "<",
                TokenKind::SmallerThanEqualToken => "<=",
                TokenKind::GreaterThanToken => ">",
                TokenKind::GreaterThanEqualToken => ">=",
                TokenKind::AmpersandAmpersandToken => "&&",
                TokenKind::PipePipeToken => "||",
                TokenKind::BitWiseAmpersandToken => "&",
                TokenKind::BitWisePipeToken => "|",
                _ => "+",
            };
            let ls = emit_expr(l, ctx);
            let rs = emit_expr(r, ctx);
            // Logical ops stay bool/bool; everything else needs matching WGSL scalar types.
            if matches!(
                op.kind,
                TokenKind::AmpersandAmpersandToken | TokenKind::PipePipeToken
            ) {
                return format!("({ls} {op_s} {rs})");
            }
            let lt = infer_wgsl_ty(l, ctx);
            let rt = infer_wgsl_ty(r, ctx);
            let common = common_numeric_wgsl_ty(&lt, &rt);
            format!(
                "({} {} {})",
                cast_wgsl_if_needed(ls, &lt, &common),
                op_s,
                cast_wgsl_if_needed(rs, &rt, &common)
            )
        }
        ExpressionNode::Unary(op, e) => {
            let op_s = match op.kind {
                TokenKind::MinusToken => "-",
                TokenKind::BangToken => "!",
                TokenKind::TildeToken => "~",
                _ => "-",
            };
            format!("({}{})", op_s, emit_expr(e, ctx))
        }
        // Statement `i++`/`++i` are desugared to Assignment before emission. Value-producing
        // forms in kernels are expanded in `emit_stmt` for declarations; nested uses fall back
        // to the place (side effect must be written as `i = i + 1` in kernels).
        ExpressionNode::IncDec { target, .. } => emit_expr(target, ctx),
        ExpressionNode::Parenthesized(e) => format!("({})", emit_expr(e, ctx)),
        ExpressionNode::IndexAccess(arr, idx) => {
            let arr_s = emit_expr(arr, ctx);
            let idx_s = emit_expr(idx, ctx);
            let atomic = matches!(arr, ExpressionNode::Identifier(n) if ctx.is_atomic_buf(&n.text));
            if atomic {
                format!("atomicLoad(&{arr_s}[u32({idx_s})])")
            } else {
                format!("{arr_s}[u32({idx_s})]")
            }
        }
        ExpressionNode::MemberAccess(obj, member) => {
            let base = emit_expr(obj, ctx);
            if member.text == "length" {
                format!("i32(arrayLength(&{}))", base)
            } else {
                format!("{}.{}", base, member.text)
            }
        }
        ExpressionNode::FunctionCall(name, _, args) => emit_call(&name.text, args, ctx),
        ExpressionNode::MethodCall(obj, method, _, args) => {
            if method.text == "length" {
                format!("i32(arrayLength(&{}))", emit_expr(obj, ctx))
            } else {
                emit_call(&method.text, args, ctx)
            }
        }
        ExpressionNode::Call(callee, _, args) => match &**callee {
            ExpressionNode::Identifier(n) => emit_call(&n.text, args, ctx),
            ExpressionNode::MemberAccess(obj, method) => {
                if method.text == "length" {
                    format!("i32(arrayLength(&{}))", emit_expr(obj, ctx))
                } else {
                    emit_call(&method.text, args, ctx)
                }
            }
            _ => "0".into(),
        },
        ExpressionNode::Ternary(c, t, e) => format!(
            "select({}, {}, {})",
            emit_expr(e, ctx),
            emit_expr(t, ctx),
            emit_expr(c, ctx)
        ),
        ExpressionNode::Cast(ty, e) => {
            let wty = dream_ty_to_wgsl(ty);
            format!("{}({})", wty, emit_expr(e, ctx))
        }
        ExpressionNode::NamedArg(_, inner) | ExpressionNode::RefArgument(inner) => {
            emit_expr(inner, ctx)
        }
        _ => "0".into(),
    }
}
