//! `.wgsl` sidecar join + `"gpu"` ABI JSON fragment.

use super::types::GpuKernelInfo;

/// Concatenate all kernels into a single WGSL module (shared by the `.wgsl` sidecar).
pub fn join_wgsl_module(kernels: &[GpuKernelInfo]) -> String {
    let mut s = String::from("// Generated by Dream @compute\n\n");
    for k in kernels {
        s.push_str(&k.wgsl);
        s.push('\n');
    }
    s
}

/// JSON fragment for the `"gpu"` section of `.abi.json` (no outer braces).
/// Each kernel embeds its own WGSL `source` so the browser host can create one shader module per
/// kernel (joined modules cannot reuse `@binding(N)` across entry points).
pub fn gpu_abi_json(kernels: &[GpuKernelInfo]) -> String {
    let mut entries = Vec::new();
    for k in kernels {
        let binds: Vec<String> = k
            .bindings
            .iter()
            .map(|b| {
                format!(
                    "{{ \"name\": \"{}\", \"binding\": {}, \"kind\": \"{}\", \"type\": \"{}\", \"read_write\": {}, \"atomic\": {} }}",
                    json_escape(&b.name),
                    b.binding,
                    b.kind,
                    json_escape(&b.wgsl_ty),
                    b.read_write,
                    b.atomic
                )
            })
            .collect();
        entries.push(format!(
            "{{ \"name\": \"{}\", \"entry\": \"{}\", \"workgroup\": [{}, {}, {}], \"bindings\": [{}], \"source\": \"{}\" }}",
            json_escape(&k.name),
            json_escape(&k.entry),
            k.workgroup.0,
            k.workgroup.1,
            k.workgroup.2,
            binds.join(", "),
            json_escape(&k.wgsl)
        ));
    }
    format!("\"kernels\": [{}]", entries.join(", "))
}

fn json_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out
}
