[package]
name = "dream-host-net"
version = "0.1.0"
edition = "2021"

[lib]
name = "dream_host_net"
crate-type = ["cdylib"]

[dependencies]
dream-host-core = { path = "../dream-host-core" }
dream-host-abi = { path = "../dream-host-abi" }
dream-abi = { path = "../dream-abi" }
indexmap = "2"
reqwest = { version = "0.12", features = ["blocking", "json"] }
tokio = { version = "1", default-features = false, features = ["rt-multi-thread", "net", "sync", "time", "macros"] }
hyper = { version = "1", default-features = false, features = ["http1", "server"] }
hyper-util = { version = "0.1", default-features = false, features = ["tokio", "server-auto", "http1"] }
http-body-util = { version = "0.1" }
bytes = { version = "1" }
serde_json = { version = "1" }
serde = { version = "1", features = ["derive"] }
tungstenite = { version = "0.24", default-features = false, features = ["handshake", "native-tls"] }
tokio-tungstenite = { version = "0.24", default-features = false }
multer = { version = "3" }
futures-util = { version = "0.3" }
rustls = { version = "0.23", default-features = false, features = ["std", "tls12", "ring"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["ring"] }
rustls-pemfile = { version = "2" }
pollster = { version = "0.4" }


[dev-dependencies]
rcgen = "0.13"
