//! Writes generated sources to `<generated dir>/<entry>/<generator>/<path>` so diagnostics,
//! the debugger and the language server point at real files. Files are rewritten only when
//! their text changes, and files a generator stopped emitting are removed.

use super::apply::GeneratedFile;
use std::path::{Path, PathBuf};

pub fn header(generator: &str) -> String {
    format!(
        "// @generated by generator '{generator}'; do not edit, it is rewritten on every build.\n"
    )
}

/// The on-disk text of a generated file (header + source).
pub fn materialized_text(file: &GeneratedFile) -> String {
    format!("{}{}", header(&file.generator), file.source)
}

/// `entry_dir` is the per-entry folder; `ran` lists generators that produced a result this
/// build (their folders are pruned to exactly `files`). Write failures are not fatal: the
/// compile uses the in-memory text, only tooling loses the on-disk copy.
pub fn materialize(
    entry_dir: &Path,
    ran: &[String],
    files: &[GeneratedFile],
) -> Vec<(PathBuf, String)> {
    let out = located(entry_dir, files);
    for (path, text) in &out {
        let unchanged = std::fs::read_to_string(path).is_ok_and(|old| old == *text);
        if !unchanged {
            if let Some(parent) = path.parent() {
                let _ = std::fs::create_dir_all(parent);
            }
            let _ = std::fs::write(path, text);
        }
    }
    for generator in ran {
        let dir = entry_dir.join(generator);
        let keep: Vec<&PathBuf> = out
            .iter()
            .map(|(p, _)| p)
            .filter(|p| p.starts_with(&dir))
            .collect();
        for stale in crate::driver::rt_stamp::files_under(&dir) {
            if !keep.contains(&&stale) {
                let _ = std::fs::remove_file(&stale);
            }
        }
    }
    out
}

/// Where each file lives on disk and its text, without touching the disk.
pub fn located(entry_dir: &Path, files: &[GeneratedFile]) -> Vec<(PathBuf, String)> {
    files
        .iter()
        .map(|f| (entry_dir.join(&f.generator).join(&f.path), materialized_text(f)))
        .collect()
}

/// Folder for one entry's generated files.
pub fn entry_dir(generated_root: &Path, entry_file: &str) -> PathBuf {
    let stem = Path::new(entry_file)
        .file_stem()
        .map(|s| s.to_string_lossy().into_owned())
        .unwrap_or_else(|| "main".to_string());
    generated_root.join(stem)
}
