//! `.wgsl` sidecar join + `"gpu"` ABI JSON fragment.

use super::types::{GpuEmitResult, GpuKernelInfo, GpuShaderInfo};
use indexmap::IndexSet;

/// Concatenate all GPU shaders into a single WGSL module (shared by the `.wgsl` sidecar).
///
/// Stages of one pipeline share declarations — the vertex/fragment interface struct, `@gpu`
/// helpers, the matrix-inverse intrinsics — and each stage's source carries its own copy because
/// it has to stand alone as a shader module. Concatenating them verbatim would redeclare those,
/// so identical top-level items are emitted once. Module-scope resources are already prefixed
/// per entry point, so those never collide in the first place.
pub fn join_wgsl_module(result: &GpuEmitResult) -> String {
    let sources = result
        .kernels
        .iter()
        .map(|k| k.wgsl.as_str())
        .chain(result.shaders.iter().map(|sh| sh.wgsl.as_str()));

    // `enable` has to precede every declaration in a module, so directives are hoisted out of
    // the per-stage sources rather than left where they appear.
    let mut directives: IndexSet<String> = IndexSet::new();
    let mut items: IndexSet<String> = IndexSet::new();
    for src in sources {
        for item in top_level_items(src) {
            if item.starts_with("enable ") || item.starts_with("requires ") {
                directives.insert(item);
            } else {
                items.insert(item);
            }
        }
    }

    let mut s = String::from("// Generated by Dream GPU shaders\n\n");
    for d in &directives {
        s.push_str(d);
        s.push('\n');
    }
    if !directives.is_empty() {
        s.push('\n');
    }
    for item in &items {
        s.push_str(item);
        s.push_str("\n\n");
    }
    s
}

/// Split a WGSL module into its top-level items (directives, structs, globals, functions).
///
/// This tracks brace depth rather than parsing: an item ends at the `;` or closing `}` that
/// brings depth back to zero. Comments are skipped for depth purposes but kept with the item
/// that follows them, which keeps identical declarations textually identical so they deduplicate.
fn top_level_items(src: &str) -> Vec<String> {
    let mut items = Vec::new();
    let mut current = String::new();
    let mut depth = 0usize;
    let mut chars = src.chars().peekable();

    while let Some(c) = chars.next() {
        if c == '/' {
            match chars.peek() {
                Some('/') => {
                    current.push(c);
                    for l in chars.by_ref() {
                        current.push(l);
                        if l == '\n' {
                            break;
                        }
                    }
                    continue;
                }
                Some('*') => {
                    current.push(c);
                    let mut prev = '\0';
                    for l in chars.by_ref() {
                        current.push(l);
                        if prev == '*' && l == '/' {
                            break;
                        }
                        prev = l;
                    }
                    continue;
                }
                _ => {}
            }
        }

        current.push(c);
        match c {
            '{' => depth += 1,
            '}' => {
                depth = depth.saturating_sub(1);
                if depth == 0 {
                    push_item(&mut items, &mut current);
                }
            }
            ';' if depth == 0 => push_item(&mut items, &mut current),
            _ => {}
        }
    }
    push_item(&mut items, &mut current);
    items
}

fn push_item(items: &mut Vec<String>, current: &mut String) {
    let text = current.trim();
    if !text.is_empty() {
        items.push(text.to_string());
    }
    current.clear();
}

/// JSON fragment for the `"gpu"` section of `.abi.json` (no outer braces).
pub fn gpu_abi_json(result: &GpuEmitResult) -> String {
    let kernels = kernels_json(&result.kernels);
    let shaders = shaders_json(&result.shaders);
    format!("\"kernels\": [{kernels}], \"shaders\": [{shaders}]")
}

fn kernels_json(kernels: &[GpuKernelInfo]) -> String {
    let mut entries = Vec::new();
    for k in kernels {
        let binds = bindings_json(&k.bindings);
        entries.push(format!(
            "{{ \"name\": \"{}\", \"entry\": \"{}\", \"workgroup\": [{}, {}, {}], \"bindings\": [{binds}], \"uniform_size\": {}, \"source\": \"{}\" }}",
            json_escape(&k.name),
            json_escape(&k.entry),
            k.workgroup.0,
            k.workgroup.1,
            k.workgroup.2,
            k.uniform_size,
            json_escape(&k.wgsl)
        ));
    }
    entries.join(", ")
}

fn shaders_json(shaders: &[GpuShaderInfo]) -> String {
    let mut entries = Vec::new();
    for sh in shaders {
        let binds = bindings_json(&sh.bindings);
        let buffers: Vec<String> = sh
            .vertex_buffers
            .iter()
            .map(|b| {
                let attrs: Vec<String> = b
                    .attributes
                    .iter()
                    .map(|a| {
                        format!(
                            "{{ \"location\": {}, \"format\": \"{}\", \"offset\": {} }}",
                            a.location,
                            json_escape(a.format),
                            a.offset
                        )
                    })
                    .collect();
                format!(
                    "{{ \"stride\": {}, \"step_mode\": \"{}\", \"attributes\": [{}] }}",
                    b.stride,
                    b.step_mode,
                    attrs.join(", ")
                )
            })
            .collect();
        entries.push(format!(
            "{{ \"name\": \"{}\", \"stage\": \"{}\", \"entry\": \"{}\", \"bindings\": [{binds}], \"vertex_buffers\": [{}], \"interface\": \"{}\", \"color_targets\": {}, \"uniform_size\": {}, \"source\": \"{}\" }}",
            json_escape(&sh.name),
            sh.stage,
            json_escape(&sh.entry),
            buffers.join(", "),
            json_escape(&sh.interface_ty),
            sh.color_targets,
            sh.uniform_size,
            json_escape(&sh.wgsl)
        ));
    }
    entries.join(", ")
}

fn bindings_json(bindings: &[super::types::GpuBinding]) -> String {
    bindings
        .iter()
        .map(|b| {
            format!(
                "{{ \"name\": \"{}\", \"group\": {}, \"binding\": {}, \"kind\": \"{}\", \"type\": \"{}\", \"read_write\": {}, \"atomic\": {}, \"view_dimension\": \"{}\", \"sample_type\": \"{}\", \"multisampled\": {}, \"storage_format\": \"{}\", \"storage_access\": \"{}\" }}",
                json_escape(&b.name),
                b.group,
                b.binding,
                b.kind,
                json_escape(&b.wgsl_ty),
                b.read_write,
                b.atomic,
                b.view_dimension,
                b.sample_type,
                b.multisampled,
                b.storage_format,
                b.storage_access
            )
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn json_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out
}
