//! `.wgsl` sidecar join + `"gpu"` ABI JSON fragment.

use super::types::{GpuEmitResult, GpuKernelInfo, GpuShaderInfo};

/// Concatenate all GPU shaders into a single WGSL module (shared by the `.wgsl` sidecar).
pub fn join_wgsl_module(result: &GpuEmitResult) -> String {
    let mut s = String::from("// Generated by Dream GPU shaders\n\n");
    for k in &result.kernels {
        s.push_str(&k.wgsl);
        s.push('\n');
    }
    for sh in &result.shaders {
        s.push_str(&sh.wgsl);
        s.push('\n');
    }
    s
}

/// JSON fragment for the `"gpu"` section of `.abi.json` (no outer braces).
pub fn gpu_abi_json(result: &GpuEmitResult) -> String {
    let kernels = kernels_json(&result.kernels);
    let shaders = shaders_json(&result.shaders);
    format!("\"kernels\": [{kernels}], \"shaders\": [{shaders}]")
}

fn kernels_json(kernels: &[GpuKernelInfo]) -> String {
    let mut entries = Vec::new();
    for k in kernels {
        let binds = bindings_json(&k.bindings);
        entries.push(format!(
            "{{ \"name\": \"{}\", \"entry\": \"{}\", \"workgroup\": [{}, {}, {}], \"bindings\": [{binds}], \"source\": \"{}\" }}",
            json_escape(&k.name),
            json_escape(&k.entry),
            k.workgroup.0,
            k.workgroup.1,
            k.workgroup.2,
            json_escape(&k.wgsl)
        ));
    }
    entries.join(", ")
}

fn shaders_json(shaders: &[GpuShaderInfo]) -> String {
    let mut entries = Vec::new();
    for sh in shaders {
        let binds = bindings_json(&sh.bindings);
        let layout: Vec<String> = sh
            .vertex_layout
            .iter()
            .map(|a| {
                format!(
                    "{{ \"location\": {}, \"format\": \"{}\", \"offset\": {} }}",
                    a.location,
                    json_escape(a.format),
                    a.offset
                )
            })
            .collect();
        entries.push(format!(
            "{{ \"name\": \"{}\", \"stage\": \"{}\", \"entry\": \"{}\", \"bindings\": [{binds}], \"vertex_layout\": [{}], \"vertex_stride\": {}, \"interface\": \"{}\", \"source\": \"{}\" }}",
            json_escape(&sh.name),
            sh.stage,
            json_escape(&sh.entry),
            layout.join(", "),
            sh.vertex_stride,
            json_escape(&sh.interface_ty),
            json_escape(&sh.wgsl)
        ));
    }
    entries.join(", ")
}

fn bindings_json(bindings: &[super::types::GpuBinding]) -> String {
    bindings
        .iter()
        .map(|b| {
            format!(
                "{{ \"name\": \"{}\", \"binding\": {}, \"kind\": \"{}\", \"type\": \"{}\", \"read_write\": {}, \"atomic\": {} }}",
                json_escape(&b.name),
                b.binding,
                b.kind,
                json_escape(&b.wgsl_ty),
                b.read_write,
                b.atomic
            )
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn json_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out
}
