[package]
name = "dream-abi"
version = "0.1.0"
edition.workspace = true

[lib]
name = "dream_abi"
path = "src/lib.rs"

[dependencies]
dream-types = { path = "../dream-types" }
dream-syntax = { path = "../dream-syntax" }
dream-diagnostics = { path = "../dream-diagnostics" }
dream-text = { path = "../dream-text" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
target-lexicon = "0.12.16"
