[package]
name = "dream-host-core"
version = "0.1.0"
edition = "2021"
links = "dream_host_core"

[lib]
name = "dream_host_core"
crate-type = ["rlib", "cdylib"]

[dependencies]
dream-host-abi = { path = "../dream-host-abi" }

[dev-dependencies]
dream-abi = { path = "../dream-abi" }
dream-stdlib = { path = "../dream-stdlib" }
